### ISSUE TITLE
[1.1.4] Maven build plugin for OpenJDK 11

### ISSUE THREAD

**Issue by kevin-innorules** [RaiMan/SikuliX1#105]
Hi!

Recently, I should had to build with OpenJDK 11.
When I built with maven with the OpenJDK 11, I encountered some problems related in build plugin and it's configurations.
So, I googled and then I could be find the approximate solve as follows.

With Open JDK 11, You must change maven-compiler-plugin to 3.8.0 and configurations as follows.

----- pom.xml ----
<build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <release>11</release>
        </configuration>
      </plugin>
    </plugins>
  </build>

Is the above right?
How about your opinion?

**Comment by RaiMan** [comment]
not sure what the problem is.

this works for me with OpenJDK 11

```
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

SikuliX is still at language level 8 (source 1.8) and should run on Java 8+ (target 1.8)

**Comment by kevin-innorules** [comment]
> not sure what the problem is.
> 
> this works for me with OpenJDK 11
> 
> ```
>       <plugin>
>         <artifactId>maven-compiler-plugin</artifactId>
>         <version>3.1</version>
>         <configuration>
>           <source>1.8</source>
>           <target>1.8</target>
>         </configuration>
>       </plugin>
> ```
> SikuliX is still at language level 8 (source 1.8) and should run on Java 8+ (target 1.8)

I see your answer.
This version works on JDK11 as like as mentioned in README 
I just only have tested it.

Thank you.

**Comment by RaiMan** [comment]
ok
