### ISSUE TITLE
[1.1.4] full path to script needed when invoked with -r switch --- fixed 2019-04-07 build#272

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#108]
Hi Raimund,

Thank you very much for your years of continuous work on Sikuli! I notice a change in behaviour between v1.1.4 and v1.1.3 when invoking script via command line. Not sure if that is by design or not. In v1.1.3 a script can be invoked by by its filename from the current directory.

In v1.1.4, if the full path is not included in the filename, Sikuli will assume the full path to be /Users/username/filename and throw error. If the full path is included and has a space in the directory name, Sikuli works when " or ' is used to enclose the full path.

Below is the replication case (macOS v10.14.4) when sample.sikuli exists in the same directory - 

```
java -jar sikulix.jar -r sample.sikuli -d 3
[error] Runner: Script file not found: /Users/username/sample.sikuli
```

I've checked Launchpad and Github and found this is not yet raised, so I created this issue.

**Comment by RaiMan** [comment]
Thanks for reporting. I will test and fix it.

**Comment by RaiMan** [comment]
should work now again.

**Comment by kensoh** [comment]
Thanks Raimund :) I tested on macOS and confirm it to be working with build 272.

**Comment by kensoh** [comment]
I confirm that it also works on Windows (8 or 10, my friend's laptop) and Linux (CentOS 6.9).

Thanks Raimund for the great work that you do! Also, I added a credits section to the TagUI project that I'm contributing to and link to SikuliX homepage and your GitHub profile.

Previously I only credit and mention SikuliX. I think that was insufficient to appreciate the amount of work in maintaining this great project. Now I mention your name and where you are from.

https://github.com/kelaberetiv/TagUI#credits

**Comment by kensoh** [comment]
Hi @RaiMan updating you that I've recently created a Python package for above TagUI project.

I've also credited SikuliX and you on the credits section of the project -
https://github.com/tebelorg/TagUI-Python#about--credits

Thank you so much for your work on SikuliX, you make it possible and easy for developers to build UI automation solutions with computer vision and OCR capabilities! 🚀

**Comment by RaiMan** [comment]
Again thanks and all the best.
