### ISSUE TITLE
Error java.lag.noclass

### ISSUE THREAD

**Issue by charliedaps1** [RaiMan/SikuliX1#110]
Hello everyone,

I use Sikulix under Windows without problem.

I just installed it on ubuntu 18. Some things do not work.

For example, when I ask him to click on a screenshot, I have the following error.

[error] java.lang.NoClassDefFoundError ( java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindImput2)

I start in linux. 

java -version
openjdk version "11.0.1" 2018-10-16

Thanks for your help

**Comment by charliedaps1** [comment]
now i have a different message

error] RunTimeAPI: loadLib: opencv_java not usable: 
java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
[error] script [ mubuntu1 ] stopped with error in line 1
[error] java.lang.ExceptionInInitializerError ( java.lang.ExceptionInInitializerError )

Thanks for your help

**Comment by RaiMan** [comment]
do the steps according to
https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#version-1-1-4-special-for-linux-people
