### ISSUE TITLE
[1.1.4] build#284: run script from command with -r --- getting Java NPE --- fixed build#285

### ISSUE THREAD

**Issue by hophamducnguyen** [RaiMan/SikuliX1#111]
I tried to run a simple script, print('test') by using command
`java -jar sikulix.jar -v -r tmp.sikuli`
But I got this error
`[debug] Jython: sikuli: Sikuli: ending init
[debug] Jython: use as default region: R[0,0 1920x1080]@S(0)
[error] script [ tmp ] stopped with error at line --unknown--
[error] Error caused by: java.lang.NullPointerException`

The script worked perfectly if running by using IDE. Just failed when running with argument "-r" 

My environment: (run in a docker container)
ubuntu 16.04, jdk 11, OpenCV 3.2, Tesseract 3.0.4, jython-standalone-2.7.1, VNC, fluxbox and Xvfb
sikilix 1.1.4 get from (https://raiman.github.io/SikuliX1/sikulix.jar) (1.1.4-SNAPSHOT-#284-2019-04-15)

You can see the full log in the attachment.
[sikuli.log](https://github.com/RaiMan/SikuliX1/files/3088424/sikuli.log)

Please guide me how to fix it. Thanks

**Comment by RaiMan** [comment]
I will fix that asap. Sorry.
