### ISSUE TITLE
Read File Error: zlib.error ( java.util.zip.DataFormatException: invalid code lengths set )

### ISSUE THREAD

**Issue by ProgramAPE** [RaiMan/SikuliX1#113]
When I read a image from the folder I get:

[error] script [ operation ] stopped with error in line 117
[error] zlib.error ( java.util.zip.DataFormatException: invalid code lengths set )
[error] --- Traceback --- error source first
line: module ( function ) statement 
244: zlib ( flush ) File "/home/dmicheal/.Sikulix/Extensions/jython-standalone-2.7.1.jar/Lib/zlib.py", line 281, in _get_inflate_data
343: response ( _flush_decoder ) return buf + self._decoder.flush()
679: response ( read_chunked ) decoded = self._flush_decoder()
490: response ( stream ) for line in self.read_chunked(amt, decode_content=decode_content):
750: models ( generate ) for chunk in self.raw.stream(chunk_size, decode_content=True):
750: models ( generate ) for chunk in self.raw.stream(chunk_size, decode_content=True):
828: models ( content ) self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
686: sessions ( send ) r.content
533: sessions ( request ) resp = self.send(prep, **send_kwargs)
60: api ( request ) return

session.request(method=method, url=url, **kwargs)
75: api ( get ) return request('get', url, params=params, **kwargs)
158: base ( _auth ) obj = self.__client.get(self.__accessTokenUrl, verify=False, params={
89: base ( _request ) authObj = self._auth()
89: base ( _request ) authObj = self._auth()
88: ocr ( basicGeneral ) return self._request(self.__generalBasicUrl, data)
31: main ( getAnswers ) response = client.basicGeneral(img)
[error] --- Traceback --- end -------------

**Comment by RaiMan** [comment]
code snippet?

**Comment by ProgramAPE** [comment]
def get_file_content(image):
    with open(image,'rb') as fp:
        return fp.read()


def getAnswers(image):
    print(image)
    answers = []
    img = get_file_content(image)

    response = client.basicGeneral(img)
    for i in range(response['words_result_num']):
        answers.append(response['words_result'][i]['words'])
    return answers


The purpose of this code is : read a image and send it to a cloud api.

**Comment by RaiMan** [comment]
Apparently has nothing to do with SikuliX.

Jython/Python problem.

You have to make sure first, that your solution works with Jython (best use a locally installed Jython to test independently).
