### ISSUE TITLE
capturing screenshots: bit depth

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#119]
Hello!

As default screenshots taken by capture-function are created with a bit depth of 24. Is there of possibility / can you implement such to configure the depth? - For our purposes a depth of 32 would be desirable.

**Comment by balmma** [comment]
We use `java.awt.Robot.createScreenCapture(Rectangle screenRect)` to capture the screen. This method returns a 24 bit BufferedImage. But anyway, a 32 bit image is basically just a 24 bit image with additional 8 bits for the alpha channel. So I don't see any advantage to have 32 bit images here.

What's your specific use case?

**Comment by balmma** [comment]
> Therefore we´d like to be able to optimize the quality of the pngs

32 bit PNGs do not provide better quality. Just additional 8 bits for the alpha channel. PNGs are already lossless, you just can't get better quality here.

What's your intention using JPEGs? Improving quality or saving disk space?

**Comment by balmma** [comment]
Can you provide an example screenshot which doesn't have the desired quality?

**Comment by PfrLisBerndt** [comment]
I just looked up png-vs-jpg infos. - Forget about my jpg-suggestion ;)

There are various ui-elements - Not sure about copy-right issues, therefore I won't provide any screenshots here, sorry. 

The range goes from grey-black named and iconed buttons (120x 100pixels) over bigger (410 x145 pixels) messageboxes, to black, blue and grey colored total screenshots of the ui (480x800 pixels), with white colored icons and names.

**Comment by balmma** [comment]
> The range goes from grey-black named and iconed buttons (120x 100pixels) over bigger (410 x145 pixels) messageboxes, to black, blue and grey colored total screenshots of the ui (480x800 pixels), with white colored icons and names.

OK, and what type of quality issues do you have exactly?

**Comment by balmma** [comment]
If you'd like you can send me an example by E-Mail to mat at balmi dot net

**Comment by balmma** [comment]
@RaiMan 
I think you can close this issue. I see no way to improve quality of screenshots further because there is in fact no better quality. Quality can't get better than what you see on the screen at the time of the screenshot.

**Comment by PfrLisBerndt** [comment]
Noted. Thank you!
