### ISSUE TITLE
Problem not solved yet ^^

### ISSUE THREAD

**Issue by xfran1998x** [RaiMan/SikuliX1#12]
Sorry for open a new issue but the problem still happening.

If you go to the closed issue you will see my last post but I give a summary:

Is possible when sikulix fails to click, find or wait, jump to the next line code? And not exit the script. Or maybe start from 0 the script.

Example:

Click(image 1)
Find(image 2) 
Wait(image 3, 40)

If image 1 is not available jump to find, if find its over and image 2 not exists jump to wait, etc. Just not close the scripts and continue running. hahaha

**Comment by RaiMan** [comment]
as mentioned:

> Ask such basic questions on [Launchpad](https://answers.launchpad.net/sikuli) (you might have to wait for answers ;-)

... and if you think, something should be reopened, then do it there (#11)
