### ISSUE TITLE
Windows: JRuby: Starting Sikulix depends on monitor - might get NPE

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#120]
Hello again,
I´ve got an curious issue for you. I´m working with three monitors. I have found out, if a drag my ide to one other monitor, sikulix does not start. - I get a null-pointer-exception: 

> LoadError: load error: sikulix/sikulix -- java.lang.NullPointerException: null
           require at org/jruby/RubyKernel.java:984
           require at C:/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
            <main> at C:/jruby-9.2.6.0/lib/ruby/gems/shared/gems/sikulix-1.1.4.0/lib/sikulix.rb:4
           require at org/jruby/RubyKernel.java:984
            (root) at C:/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
            <main> at C:/jruby-9.2.6.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:135
           require at org/jruby/RubyKernel.java:984`

When I drag the ide back to the monitor with the test-object, it works as usual.

Definitely this behavior didn´t occur with the former sikulix-api-versions. --> More precise: this problem is combined with the gem; when I ran the api with other tools, there is no problem.

**Comment by RaiMan** [comment]
Thanks for finding. Will take a while (probably next week). Currently other priorities.

**Comment by petrukhnov** [comment]
I was able to always replicate problem on win10 with 3 monitors:
Start sikulix, where app for testing is on (or will be loaded) 1st screen, but mouse is on 3rd screen.

If mouse is on 1st or 2nd screen, and app on 1st or second screen, then no error, and everything works.

If app on 3rd screen, and mouse on any screen, then also it works.

(number of screens is how Windows handle them).

Screen.initScreens():
    Mouse.init() is where error happens to me.

**Comment by balmma** [comment]
PR #211 solves this.

**Comment by balmma** [comment]
Which version are you currently using?

**Comment by PfrLisBerndt** [comment]
It´s the current version from the download-site, 2.0.0

**Comment by balmma** [comment]
Fix is in 2.0.1 which is not released yet.

@RaiMan
Any estimates when 2.0.1 will be available?

**Comment by RaiMan** [comment]
release 2.0.1: planned for Friday, Nov. 22nd
