### ISSUE TITLE
1.1.4-SNAPSHOT at the OSS Sonatype repo is broken

### ISSUE THREAD

**Issue by CoeJoder** [RaiMan/SikuliX1#139]
The pom.xml and sources.jar for the sikulixapi artifact are both out of date with the main .jar.  It's causing runtime errors because pom.xml refers to the old 4.x ''jna-platform'' dependency but distribution .jar relies on the 5.x version. It is also missing the org.reflections.reflections dependency.

https://oss.sonatype.org/content/repositories/snapshots/com/sikulix/sikulixapi/1.1.4-SNAPSHOT/

**Comment by balmma** [comment]
Can confirm this.
@RaiMan 
Any idea why the top level .pom file doesn't get updated?

**Comment by RaiMan** [comment]
fixed (build 307)
https://oss.sonatype.org/content/repositories/snapshots/com/sikulix/sikulixapi/1.1.4-SNAPSHOT/sikulixapi-1.1.4-20190617.155428-194.pom
