### ISSUE TITLE
compiler errors when running sikulisetup on Ubuntu 18.04

### ISSUE THREAD

**Issue by jnweiger** [RaiMan/SikuliX1#15]
`java -jar sikulixsetup-1.1.3-20180711.082147-40-forsetup.jar` hangs in the RunBuild script compiling sources.
When I start /home/testy/.Sikulix/sikulixlibs/linux/runBuild I get the following error messages:
```
/home/testy/.Sikulix/sikulixlibs/linux/Build/Source/vision.cpp: In static member function ‘static void sikuli::Vision::initSParameters()’:
/home/testy/.Sikulix/sikulixlibs/linux/Build/Source/vision.cpp:489:4: error: ‘_sparams’ was not declared in this scope
    _sparams["OCRLang"] = "eng";
    ^~~~~~~~
...
----- pyramid-template-matcher.cpp
In file included from /home/testy/.Sikulix/sikulixlibs/linux/Build/Source/pyramid-template-matcher.h:14:0,
                 from /home/testy/.Sikulix/sikulixlibs/linux/Build/Source/pyramid-template-matcher.cpp:7:
/home/testy/.Sikulix/sikulixlibs/linux/Build/Source/vision.h:84:16: error: ‘map’ in namespace ‘std’ does not name a template type
    static std::map<std::string, float> _params;
                ^~~
```
This is with g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
and also the same with g++ (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424

The setup jar hangs, as the compiler is run behind pipes, so that its stderr is redirected to some other process, that apparently does not read (all of) the output. Guessing that much from poking around with strace.

**Comment by RaiMan** [comment]
I know, that Ubuntu 18 makes problems.

To get a step further, I decided to make a 1.1.4 version, that does not have the more than 6 years old C++ stuff any more (backport from version 2).

You will get the latest OpenCV and revised text/OCR features with Tess4J implemented completely in Java. 

Mac and Windows versions are nearly ready, Ubuntu has to be tested. A nightly build will be available the next days. So watch out.

**Comment by RaiMan** [comment]
Things will hopefully get easier with 1.1.4 ;-)
