### ISSUE TITLE
[Question] Does Pattern support text search?

### ISSUE THREAD

**Issue by rainmanwy** [RaiMan/SikuliX1#155]
@RaiMan , i got a issue [104](https://github.com/rainmanwy/robotframework-SikuliLibrary/issues/104) to implement a method to click text.

And i am not sure whether Pattern support text? As i could see in Image.java
```
private static Image get(String fName) {
        if (fName != null && !fName.isEmpty()) {
            Image image = null;
            if (fName.startsWith("\t") && fName.endsWith("\t")) {
                fName = fName.substring(1, fName.length() - 1);
                image = new Image();
                image.setIsText(true);
            } else {
```
there is "imageIsText" in this class, not sure whether Pattern support OCR. And currently i haven't environment to verify it.

**Comment by RaiMan** [comment]
You should create a keyword `clickText` and then internally use `findText()` to create the match and then `click(match)`.

**Comment by rainmanwy** [comment]
ok, thanks!
