### ISSUE TITLE
multi monitor issue

### ISSUE THREAD

**Issue by sachinkademane** [RaiMan/SikuliX1#16]
Hi team,

i want to extend my primary screen display by using dragdrop option in sikuli to secondary screen, does sikuli 1.1.3 supports this feature?

ex: if i am running a youtube in chrome and i want to drag and drop this chrome tab to secondary monitor, when i tried this sikuli didn't allow me to capture image to drop tab in secondary screen

How can we try to resolve this issue?

**Comment by RaiMan** [comment]
please ask on launchpad.
