### ISSUE TITLE
Run the java -jar sikulixapi.jar -s

### ISSUE THREAD

**Issue by JayenLee** [RaiMan/SikuliX1#161]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/10287391/61016206-6d57d880-a3c1-11e9-856c-006ee7217d11.png">

java sdk 12.0.1

**Comment by breyesitrs** [comment]
@JayenLee 
Im assuming you want to run the SikuliX IDE

- I'd like to point you to this page https://raiman.github.io/SikuliX1/downloads.html
- Download the sikulix.jar and any of the intepreter ( jython or jruby)  and put them in a directory
- Then run the command `java -jar sikulix.jar`

Note: 
> the sikulixapi.jar  is for use on a Java classpath or for Java programming in mature IDEs as library jar.

Enjoy!
