### ISSUE TITLE
Python: using jpype: images cannot be loaded - not on image path 

### ISSUE THREAD

**Issue by march-lee** [RaiMan/SikuliX1#162]
import unittest
import jpype
import os
class LoginCase(unittest.TestCase):
    def setUp(self):

        print("开始case")
        # 获取JVM的路径
        self.jvmpath = jpype.getDefaultJVMPath()
        self.jarpath = os.path.join(os.path.abspath('.'), 'D:/')  # 指定jar包路径
        jpype.startJVM(self.jvmpath, '-Djava.class.path=%s' % (self.jarpath + 'sikulixapi.jar'))
        self.system = jpype.java.lang.System  # 为System调用定义一个变量，方便后面使用
        self.system.out.println("javaJVM hase be start")
        Screen = jpype.JClass('org.sikuli.script.Screen')  # 引入SikuliX中的Screen类
        print("load sikuli packge")
        self.s = Screen()

    def tearDown(self):
        print("end")

    def test_01(self):
        print("01test")
        self.s.doubleClick("image/node.png")
if __name__ == '__main__':
   unittest.main()

----------------------------console  output----------------------------------
[error] ImagePath: find: not on image path: image/node.png
E
======================================================================
ERROR: test_01 (__main__.LoginCase)
----------------------------------------------------------------------
Traceback (most recent call last):
end
  File "D:/CCB_Maneger/test/case/LoginCase.py", line 23, in test_01
    self.s.doubleClick("image/node.png")
jpype._jclass.org.sikuli.script.FindFailed: image/node.png not loaded

**Comment by RaiMan** [comment]
Looks like running plain Python using package jpype, to access the SikuliX Java API. 

For the images you either have to use absolute paths or you use the ImagePath features.
See docs.

**Comment by march-lee** [comment]
I'm have use abspath,but it's filed.i am don't kown how to do,i search all method,nothing to do.

**Comment by RaiMan** [comment]
Is it still saying:
jpype._jclass.org.sikuli.script.FindFailed: <absolute-path>/image/node.png not loaded

.. or something else?
