### ISSUE TITLE
ImagePath: add with class reference not working

### ISSUE THREAD

**Issue by march-lee** [RaiMan/SikuliX1#163]
What are the rules of use ImagePath?my project can't find image,exception:FindField.
Screen screen = new Screen();
String name = SikuliTest.class.getCanonicalName();
String[] path = ImagePath.get();
for (int i = 0; i <path.length ; i++) {
System.out.println(path[i]);
}
System.out.println(name);

    ImagePath.add(name + "/imagePackge");
My project pathis :com.ccb.SikuliTest,,com.ccb.imagePackge
Error message:[error] ImagePath: add: not valid: com.ccb.SikuliTest/imagePackge

**Comment by RaiMan** [comment]
I will check.

**Comment by RaiMan** [comment]
The rules are:
 - having `ImagePath.add(class + "/path");`
 - `class` must be the fully qualified class name (as returned by myClass.class.getCanonicalName())
 - `path` must be the complete relative path to the root of the jar or to the folder containing the compiled classes (this usually is the case, when using the Maven project folder concept)

So if you really have your images folder down in the package together with the Java sources, then it has to be: `ImagePath.add(name + "/com/ccb/imagePackge")`

But IMHO this is not recommended, since with Maven projects (and similar build concepts) one has one folderstructure for the Java sources (src/min/java) and one for other resources (src/main/resources).

**Comment by march-lee** [comment]
Thinks,Raiman.I just try it

**Comment by breyesitrs** [comment]
I encountered the same need and created this solution by traversing to the project directory. Its not the most elegant IMHO but it serves its purpose.

       public static void loadResourceImages(){	
		String resource = System.getProperty("user.dir") + "/resources";
		addToImagePath(new File(resource));
	  }
	
	private static void addToImagePath(File directory) {
		if (directory.isDirectory()) {
	        File[] subDirectories = directory.listFiles();
	        add(directory.getPath());
	        for (File file : subDirectories) {
	        	addToImagePath(file);
	        }
	    }		
	}`

Hope this helps others.

**Comment by march-lee** [comment]
> The rules are:
> 
> * having `ImagePath.add(class + "/path");`
> * `class` must be the fully qualified class name (as returned by myClass.class.getCanonicalName())
> * `path` must be the complete relative path to the root of the jar or to the folder containing the compiled classes (this usually is the case, when using the Maven project folder concept)
> 
> So if you really have your images folder down in the package together with the Java sources, then it has to be: `ImagePath.add(name + "/com/ccb/imagePackge")`
> 
> But IMHO this is not recommended, since with Maven projects (and similar build concepts) one has one folderstructure for the Java sources (src/min/java) and one for other resources (src/main/resources).

I think I've found a problem：when i Init Screen in my project and start this，but the window don't system desktop.
When I tried IDE, I opened several programs and the window diden't make the destktop,when it was on start,it's exception FindField.
my question is :How to let the screen capture in the desktop when i starting my debugger applacation.At API document i am not find about method.
Thanks,RaiMan.
Thank you for always answering my questions.

**Comment by march-lee** [comment]
Look the exception ,my image can be find ,but this window not system desktop,How to do it?current screen is desktop.
FindFailed: node.png: (112x103) in R[0,0 1280x720]@S(0)
  Line 2340, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:2340)
	at org.sikuli.script.Region.wait(Region.java:2358)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3385)
	at org.sikuli.script.Region.doubleClick(Region.java:4090)
	at org.sikuli.script.Region.doubleClick(Region.java:4075)
	at Test.main(Test.java:18)

Process finished with exit code 0

**Comment by RaiMan** [comment]
If you have more than one screen/monitor attached, then look into the docs about multimonitor handling.
SikuliX can only find what is currently visible in the foreground on the respective screen.

**Comment by march-lee** [comment]
> If you have more than one screen/monitor attached, then look into the docs about multimonitor handling.
> SikuliX can only find what is currently visible in the foreground on the respective screen.

Dear RaiMan:
         I'm always can't impelement click or doubleClick events,but i don't my problem, i am use Jython compute,PyCharmIDE, setup sikuliapi as CLASSPATH,and import org.sikuli.script.SikulixForJython,my project can be running,but don't look click result and events;
         I'm use JAVA api,nothing result yet.
my codeing:
import org.sikuli.script.SikulixForJython
from sikuli import *
if __name__ == '__main__':
    print "hello world"
    x = 1
    print x
    s = Screen(0)
    s.click("img\\1111.PNG")


my exception:
D:\softSetup\jython2.7.0\bin\jython.exe -Dpython.path=D:\CCBPY D:/CCBPY/test.py
[error] RunTimeINIT: *** BE AWARE: Running on Java 8+ *** Please report problems ***
hello world
1
Traceback (most recent call last):
  File "D:/CCBPY/test.py", line 17, in <module>
    s.click("img\\1111.PNG")
  Line 2761, in file Region.java
	at org.sikuli.script.Region.wait(Region.java:2761)
	at org.sikuli.script.Region.find(Region.java:2326)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3220)
	at org.python.proxies.sikuli.Sikuli$Screen$6.getLocationFromTarget(Unknown Source)
	at org.sikuli.script.Region.click(Region.java:3718)
	at org.sikuli.script.Region.click(Region.java:3703)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
org.sikuli.script.FindFailed: FindFailed: img/1111.PNG: (113x44) in S(0)[0,0 1280x720] E:Y, T:3.0
  Line 2761, in file Region.java


Process finished with exit code -1

**Comment by RaiMan** [comment]
Still the image is not visible on the screen, when you run your script from the PyCharms IDE.
Again: You must SEE the image on the screen in foreground in that moment.

Have a look at the App features to get the window with your image into foreground.

BTW: please ask such beginners questions on Launchpad. The audience there is much bigger.
