### ISSUE TITLE
Memory leak until crash from OpenCV error (-4) Failed to allocate X bytes

### ISSUE THREAD

**Issue by OdedRadi** [RaiMan/SikuliX1#181]
The program starts with ~130M RAM usage.
When I run the script, the memory usage jump to ~160M (which seems OK), but keep growing by ~2M every few seconds.
After ~10 minutes, the memory usage is ~600M.
Stopping the script make the leak stop growing (the memory usage is still ~600M).
Starting the script again continues the growth.

After few hours, the following exception is thrown:

![sikuli crash](https://user-images.githubusercontent.com/16279940/63216336-60ef3a00-c13c-11e9-9a41-bcbd953b4869.png)

**Comment by RaiMan** [comment]
I made some tests with a simple script looping around one image search.
I used VisualVM to track the memory consumption and the heap behaviour.
I could not find any unexpected behaviour.

While the IDE is doing nothing, the heap consumption is constantly growing.
But if the IDE is running a script, then the heap usage is reduced at start and the in average stays constant (GC seems to work).

What version of SikuliX are you using? You seem to work on Windows 10.

Do you have your own OpenCV library installation?

You might restrict the heap size with the java command to a suitable value for your system.

Or you might try to run the script directly from command line.

**Comment by OdedRadi** [comment]
I don't have my own OpenCV library.
SikuliX version is 1.1.2.

How can I run the script directly from command line?

This is the RAM usage when the IDE is opened:
![image](https://user-images.githubusercontent.com/16279940/63288789-4052eb80-c2c6-11e9-9c67-ab956e0917eb.png)

This is the RAM usage when the scrips started:
![image](https://user-images.githubusercontent.com/16279940/63288816-4ba61700-c2c6-11e9-8b34-e6336b05f0da.png)

This is the RAM usage after 40 seconds:
![image](https://user-images.githubusercontent.com/16279940/63288864-6d070300-c2c6-11e9-9725-58a1b34090d8.png)

This is the RAM usage after 5 minutes:
![image](https://user-images.githubusercontent.com/16279940/63289181-2b2a8c80-c2c7-11e9-9144-b16bc3a580fe.png)

This is the RAM usage when stopping the script (stopped growing):
![image](https://user-images.githubusercontent.com/16279940/63289216-41384d00-c2c7-11e9-8ae4-df19c5b958e6.png)

This is the RAM usage when starting the script again (keeps growing):
![image](https://user-images.githubusercontent.com/16279940/63289288-6fb62800-c2c7-11e9-9fbc-20b8e9d978ac.png)

**Comment by balmma** [comment]
Have you already tried it with 1.1.4?

**Comment by OdedRadi** [comment]
Now I did.
The memory usage is growing very fast to 1GB memory usage in 1 min, but then its jumps back to 500M, and growing to 1Gb again, over and over.
Maybe this is ok?

Starts IDE with stable 386M usage:
![image](https://user-images.githubusercontent.com/16279940/64207600-9e2a2a80-cea5-11e9-846d-5a78ea40cb0b.png)

Start script jump to 550M:
![image](https://user-images.githubusercontent.com/16279940/64207644-b8640880-cea5-11e9-8ddb-c98c3c136f6c.png)

After 30 seconds:
![image](https://user-images.githubusercontent.com/16279940/64207676-cade4200-cea5-11e9-8b9a-dd5ccadf0b58.png)

After 1 min:
![image](https://user-images.githubusercontent.com/16279940/64207741-ed705b00-cea5-11e9-8b22-a376c21852df.png)

**Comment by balmma** [comment]
>The memory usage is growing very fast to 1GB memory usage in 1 min, but then its jumps back to 500M, and growing to 1Gb again, over and over.

AFAICS this looks like the usual Java behavior where the garbage collector only kicks in from time to time.

**Comment by OdedRadi** [comment]
Ok ty
