### ISSUE TITLE
Copy Paste in IDE can throw error when images have dash in name

### ISSUE THREAD

**Issue by pilotdude** [RaiMan/SikuliX1#193]
When using the copy paste functionality to copy and paste an image from one project to another in the IDE if the image name for the image you are copying has a dash in it ( - ) and another image with the same name already exists in the project that you are copying to the IDE will throw a (not very helpful) error and not allow you to paste. 

The error that is given is: [error] EditorPane: MyTransferHandler: importData: Problem pasting text For input string: "{PORTION OF THE IMAGENAME AFTER THE DASH}"

As an example of this if I already had an image called Menu - Option 1 in the project and I tried to paste the same image in again (maybe because I wanted to click in the same place again later in the script. The paste would not complete and I would get an error saying: [error] EditorPane: MyTransferHandler: importData: Problem pasting text For input string: " Option 1"

**Comment by RaiMan** [comment]
Thanks for reporting. I will check and fix.

**Comment by RaiMan** [comment]
Please test with latest build #380+
... should work now

**Comment by pilotdude** [comment]
Works now, Brilliant! Thanks!!
