### ISSUE TITLE
click issue in sikulixapi 1.1.4-SNAPSHOT

### ISSUE THREAD

**Issue by kumarkrish85** [RaiMan/SikuliX1#196]
Hi,

I am using Java 11 and trying to click the word "Doodle 4 Google" in google.co.in page through click API in Region class. Following exception trace i got

> FindFailed: Doodle 4 Google.png not loaded
  Line 2284, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:2284)
	at org.sikuli.script.Region.wait(Region.java:2302)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3329)
	at org.sikuli.script.Region.click(Region.java:3982)
	at org.sikuli.script.Region.click(Region.java:3958)

It was working fine earlier Sikuli builds like 1.1.2 . Please help me to resolve the issue.

**Comment by balmma** [comment]
We need some more information here:

- Are you using the IDE or the API?
- Can your provide example code?
- Where is your image located?
- Do you have an example image?
- Exact URL of the website you want to find the image?

**Comment by kumarkrish85** [comment]
Thanks :) i changed it like below. `SCREEN.click(SCREEN.findText("Doodle 4 Google"));`

**Comment by balmma** [comment]
I would prefer:

`SCREEN.findText("Doodle 4 Google").click();`

findText() returns a Match instance which provides a click() method itself. Just a bit less redundancy :-)

**Comment by kumarkrish85** [comment]
Thanks 👍
