### ISSUE TITLE
[discussion] change handling for foreign sources in the project

### ISSUE THREAD

**Issue by RaiMan** [RaiMan/SikuliX1#199]
currently we have the following foreign sources in the project (different reasons)

- jkeymaster
- ...

What are the alternatives?

**keymaster**
https://github.com/tulskiy/jkeymaster
@balmma Last release from JKeyMaster is from January 2016. It is not even compatible with the latest JNA anymore. We've already done some modifications to get it working with it. Seems that there was some effort recently in the JKeyMaster repo to get it up to date. 

- Would say, here we have to keep the status quo until they decide to release a new version to maven.

**Comment by balmma** [comment]
> keymaster

Last release from JKeyMaster  is from January 2016. It is not even compatible with the latest JNA anymore. We've already done some modifications to get it working with it. Seems that there was some effort recently in the JKeyMaster repo (https://github.com/tulskiy/jkeymaster/commits/master) to get it up to date. Would say, here we have to keep the status quo until they decide to release a new version to maven.

**Comment by balmma** [comment]
> OpenCV
There is no jar as Maven dependency available. Integrating as jar is more complex, then just having the sources.

Unfortunately I have to agree here :-( Would need quite some effort to make it work seamlessly.

**Comment by RaiMan** [comment]
OpenCV is now separated to its own package sikulix2opencv (current stable 4.1.1)

**Comment by balmma** [comment]
> OpenCV is now separated to its own package sikulix2opencv (current stable 4.1.1)

Amazing.

Can confirm that it works with a freshly compiled OpenCV 4.1.1 on Ubuntu 18.04. From the IDE and the packed JAR version.

**Comment by RaiMan** [comment]
Great thanks!

**Comment by balmma** [comment]
Doesn't seem to work on Windows though:
`[error] RunTime:libsExport: libopencv_java.dll: failed: null`

**Comment by balmma** [comment]
It seems to have a general problem exporting files to SikulixLibs.

**Comment by RaiMan** [comment]
Thanks. Just pushed a fix.

**Comment by RaiMan** [comment]
... and sikulix2opencv::4.1.1 is on MavenCentral.

**Comment by balmma** [comment]
> Thanks. Just pushed a fix.

Looks much better :-)
