### ISSUE TITLE
[1.1.4] IDE: attempting to use Find throws an error --- currently switched off

### ISSUE THREAD

**Issue by blkeller** [RaiMan/SikuliX1#20]
**Sikuli version:** 1.1.4, build 2018-08-23_12:18
**Platform:** Windows 8.1, 64-bit
```
>java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

When attempting to use the "Find" function in the IDE, either through `Edit` -> `Find` -> `Find...`, or via CTRL-F, the IDE throws an error:
`[error] IDE: Problem when trying to invoke menu action doFind Error: null`

No further activity occurs, and "Find" cannot be used.

**Comment by RaiMan** [comment]
Sorry, forgot to mention: currently switched off due to problems with latest Java and the search field.

I will add a bug on launchpad.

**Comment by RaiMan** [comment]
see 
https://bugs.launchpad.net/sikuli/+bug/1788811
