### ISSUE TITLE
"Export as runnable jar" no longer available --- workaround

### ISSUE THREAD

**Issue by ahm3dhany** [RaiMan/SikuliX1#201]
After exporting project "XYZ" as a runnable jar using "File > Export as jar" it gives me a jar file name "XYZ.jar".
Now the problem is.. when I run this jar file like this:
`java -jar XYZ.jar`
it gives me this error:

> Error: Invalid or corrupt jarfile XYZ.jar 

Other details:
sikuliX IDE 1.1.4
Windows 7

**Comment by balmma** [comment]
The JAR exported by "Export as jar" is not runnable itself. It only contains the compiled python source code. You have to run it using the sikulix.jar:
`java -jar sikulix.jar -r XYZ.jar`

**Comment by ahm3dhany** [comment]
so there is no way to include the sikuliX in the runnable jar itself and run it as one runnable jar?

**Comment by balmma** [comment]
We once had this feature but we deactivated it 6 months ago. Can't exactly remember why, but I guess we had some issues with it and considered it not useful enough to fix. It anyway produces huge JAR files (around 90 MB) which are quite a bit impractical. Probably @RaiMan can say more about it.

**Comment by RaiMan** [comment]
All said by @balmma - does not make sense.

But with the latest 1.1.4 you can do the following:

- put the script (or the exported jar), the sikulixapi.jar or sikulix.jar and the script support jar (jython or jruby) in one folder
-  create an executable zip-file, that on unpack runs the command:
java -jar sikulixapi.jar -r script.jar
- the zip you get has about 120 - 130 MB

If you would make your scripts in JavaScript you would save the script support (Jython/Jruby) (about 30 - 40 MB).

If you set up your solution as a Java project you could create a tailored jar, by leaving out parts of the SikuliX jar, that would not be needed by your script and/or on the target system.

Nevertheless the minimal jar you would get currently would always be about 50 MB.

... and such a solution only makes sense, if you pack all your scripts on one system into one jar, to not have multiple copies of the SikuliX stuff on one system (10 scripts would be about 1GB ;-)
