### ISSUE TITLE
Linux: App close is not working

### ISSUE THREAD

**Issue by kumarkrish85** [RaiMan/SikuliX1#217]
*** possibly related #144 

I am using Sikuli 1.1.4 SNAPSHOT build in my tool. The App.open is working fine, but when i try to close an using "App.close( )" is not closing the app. The issue is observed on both Windows and Linux.
Tried on simple calc application.

**Comment by RaiMan** [comment]
Sorry, known problem - accepted as bug.

possible workaround:
close the app visually (Windows: type::ALT-F4, Linux: ...)

**Comment by kumarkrish85** [comment]
Thanks for the confirmation @RaiMan

**Comment by RaiMan** [comment]
At least for Windows it works now after fix 2.1.0:https://github.com/RaiMan/SikuliX1/commit/63cf0bfa1896ea8efa35677bacad2da080dcdbc6 2.0.2:https://github.com/RaiMan/SikuliX1/commit/adbcec1f7d9ca0016ba062176d5b9e6696a1bb18

**Comment by RaiMan** [comment]
fixed 2019-12-26 in 2.0.2 and 2.1.0
