### ISSUE TITLE
command line option -i removed (interactive Jython) 

### ISSUE THREAD

**Issue by xklyx** [RaiMan/SikuliX1#222]
In the version 2.0.0, the parameter "-i" to launch interactive Jython session in the command line is removed

**Comment by RaiMan** [comment]
The interactive Jython session is no longer available as command line parameter -i

Use on Windows:
java -cp <path-to>\sikulixapi.jar;<path-to>\jython-standalone-2.7.1.jar org.python.util.jython 

Use on Mac/Linux:
java -cp <path-to>/sikulixapi.jar:<path-to>/jython-standalone-2.7.1.jar org.python.util.jython

**Comment by xklyx** [comment]
Thanks, I tested and it worked, but I need to add this snippet to load sikuli first

```
import org.sikuli.script.SikulixForJython
from sikuli.Sikuli import *
```

**Comment by RaiMan** [comment]
I accept this as an enhancement bug (-i should be brought back)
