### ISSUE TITLE
Cannot stop execution of the script in IDE

### ISSUE THREAD

**Issue by xklyx** [RaiMan/SikuliX1#223]
The function that allows to stop exeuction in IDE by pres Alt + Shift + C is removed since version 2.0.0, but there is no alternative method to do so in the new version.

**Comment by RaiMan** [comment]
Just tested on Win10 and macOS: works as expected.

So give more details.

run from commandline to get debug infos:
`java -jar <path-to>\sikulix.jar -v -c`

**Comment by RaiMan** [comment]
no reaction
