### ISSUE TITLE
SikuliX 2.0 Install Problem...

### ISSUE THREAD

**Issue by bartclark** [RaiMan/SikuliX1#224]
I cannot get the new SikuliX 2.0 to install.  Admittedly I am not as versed in these matters as I wished.  But I have used SikuliX 1.1 to GREAT effect for several years and now need to install SikuliX 2.0 on a new Windows 10 machine in order to automate a bunch of work on a deadline....

When I  go to https://raiman.github.io/SikuliX1/downloads.html and download the "ready to use SikuliX .jar file (IDE) and place it in a folder with the Jython installer download (as I will operate in Python using the included SikuliX IDE) the following happens when I double click on the SikuliX 2.0 .jar file:
1.  The Jython installer disappears and then.... nothing else happens.

I have tried this on 4 different Windows 10 Pro computers and I keep getting this same response.  I have tried saving the SikuliX .jar file and the Jython file in various directories but as long as they are in the same folder, this same thing occurs: Jython disappears and then....nothing else happens!

ANY help would be greatly appreciated as I have tons of scripts from Sikulix 1.1 and I'm under a deadline on the needed work....  I never dreamed I'd run into this problem and am willing to install SikuliX 1.? if needed so I can get back to work.

Thanks in advance for ANY help or thoughts or questions...

Sincerely,

Bart Clark
Dallas, Texas

I am using Windows 10 Pro 64 bit with latest updates installed. (on all four computers, and no version of SikuliX had not been installed on any of them
I am using latest Java build as of 11/06/2019.
I am downloading the SikuliX 2.0 IDE .jar file and the Jython install file from https://raiman.github.io/SikuliX1/downloads.html\

**Comment by bartclark** [comment]
Also, FYI I have, out of desperation tried to launch the Jython installer manually just to see if Java is working properly and each machine would launch the installer.

**Comment by RaiMan** [comment]
Not sure what you downloaded from where.

Just verified on my Windows 10 the steps mentioned on the downloadpage 
https://raiman.github.io/SikuliX1/downloads.html

- step 1: download the IDE to some folder:
clicked the link: Download the ready to use sikulix.jar (SikuliX IDE)

- step 2: downloaded the Jython jar to the same folder:
clicked the link: The Jython interpreter 2.7.1 for python scripting (the default)

now I have 2 jars in the folder:
- sikulix-2.0.0.jar
- jython-2.7.1-standalone.jar

now by double-clicking the sikulix jar or running `java -jar <path-to>\sikulix-2.0.0.jar` the iDE starts.

... and the Jython jar is moved to the SikuliX/Extensions folder (as mentioned in the download page)

The Jython installer is simply wrong.

**Comment by RaiMan** [comment]
In doubt delete everything you had before including the SikuliX <app-data> path.

**Comment by bartclark** [comment]
Thank You so much for the response!  (and for continuing to work on SikuliX!)  I have sent you a modest token of appreciation via PayPall....  Even though I am currently having difficulties... I LOVE SikuliX and it has allowed me to do the work it would take a week of TEN of me to do....in a single evening!

I will delete everything and try again.  And I will try again on a Windows 10 computer that has never had SikuliX installed.  I will video a screen cast of exactly what I am doing so perhaps my error will be evident?

**Comment by bartclark** [comment]
OK.  I have again tried to follow the instructions precisely but must be doing something wrong?  

I have included a couple of 480p screen recording files so you can see EXACTLY what I am doing.

Though this was done on a Mac running VMWare Fusion, I have tried this on half a dozen regular Windows 10 Pro regular PCs at the office with the same result:

1.  Latest Windows 10 Pro build

2.  Fresh instal of latest Java 64 bit

3. goto: https://raiman.github.io/SikuliX1/downloads.html

4.  download the IDE to download folder:
clicked the link: Download the ready to use sikulix.jar (SikuliX IDE)

5. downloaded the Jython jar to the same folder:
clicked the link: The Jython interpreter 2.7.1 for python scripting (the default)

6.  Ensure both files are in the same folder and double-click SikuliX IDE .jar file

7.  Result is always the same on all different Windows 10 Pro PCs and the Mac VMWare Fusion PC: after double-click on SikuliX IDE .jar file the Jython Installer file disappears as is intended...but then NOTHING else will happen.

Please look at screen recordings and let me know what I am doing wrong?  Thank you in advance for your time and help....I feel like an idiot but cannot see what I am doing wrong on all of the PCs I've tried to instal SikuliX 2.0

(had to reduce screen recording quality a bit for GitHub file size limitations)

Sincerely,

Bart Clark

[Screen Recording Sikuli 2.0 Install 1.mov.zip](https://github.com/RaiMan/SikuliX1/files/3821803/Screen.Recording.Sikuli.2.0.Install.1.mov.zip)
[Screen Recording SikuliX 2.0 Install 2.mov.zip](https://github.com/RaiMan/SikuliX1/files/3821805/Screen.Recording.SikuliX.2.0.Install.2.mov.zip)

**Comment by bartclark** [comment]
The above 'PC', like the real PCs at the office all had never had SikuliX or Jython installed.  

Also, if you again double-click on the SikuliX 2.0 IDE .jar file....nothing appears to happen at all.

**Comment by RaiMan** [comment]
Ok, looks odd - even the startup badge does not come up.

Please open a command line window.

what do you get with:
`java -version`

should give something like this:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

If this does not work:
- where did you get your Java and what version?
- how and where did you install it?

Please paste your output here.

Then try with:
`java -jar <path-to>\sikulix-2.0.0.jar -v -c`

I myself tested all this with the latest Java 8 installed.

IMHO there are no installers for OpenJDK 9+ anymore. So double-clicking the sikulix jar should only work with Java 8.

Tests with Java 13 I always run from a command line.

I guess this is not clear from the docs right now.

**Comment by bartclark** [comment]
A thousand thanks for your response: I will carefully follow your instructions and I will report exact results ASAP when I can this afternoon!

**Comment by bartclark** [comment]
<img width="457" alt="java version 111119" src="https://user-images.githubusercontent.com/57495813/68623867-16f7c500-049b-11ea-98ad-e8a5d976ab17.png">
<img width="1281" alt="Java Install Page 111119" src="https://user-images.githubusercontent.com/57495813/68623878-1bbc7900-049b-11ea-8397-ba5ef33c5cbc.png">

**Comment by bartclark** [comment]
Aha!  I see it is saying I need 64 bit java (which is what I thought I have been installing!)  

I will work on solving this while I wait for you to respond (you are probably asleep when I am awake!)

:)

bc

**Comment by bartclark** [comment]
Success!

It must have been the particular Java screen I was going to for the Java updates....?  I would have THOUGHT it would auto-install the most capable version of Java.  But once I MANUALLY selected to 'offline' Java 64bit install and downloaded it....  PRESTO!  Success!

Thank You so much for your continued work on SikuliX and for your assistance in walking me through my potential errors....  Your instructions allowed me to see there was an issue with Java...leading me to try the manual 64bit installation of Java!

<img width="970" alt="SikuliX 2 0 success" src="https://user-images.githubusercontent.com/57495813/68629406-5a593000-04a9-11ea-912d-4590e9251748.png">

**Comment by RaiMan** [comment]
Fine. Finally. 

I have to admit, that I did not see this possible pitfall from beginning (I am always testing with -v to see everything).

I will add a popup, so the wrong-java problem is always visible, even if you double-click the jar.

Thanks for your patience and all the best.

**Comment by bartclark** [comment]
Thanks…  An additional popup would for sure solve the problem for future people experiencing the same issue (though I dare say MOST are experienced enough NOT to have the persistent problem that I had….).

bc

**Comment by anggafsahid** [comment]
successfully installed java and run sikulix smoothly. i also can run sikulix with "run" icon
the problem is when i already exported file as jar so i can run independently without sikulixIde. The save.jar cannot run and its said
"Error: Invalid or Corrupt jar file C:\SIKULI\SaveFile\save.jar"

**Comment by RaiMan** [comment]
@anggafsahid 
Please do not ask questions in posts with unrelated topic or even closed ones. 
Write your own new post in such cases.

at your question:
There is currently no solution, to run SikuliX stuff without sikulixide/sikulixapi jar (-r parameter on command line).

Scripts in whatever form (.sikuli, .skl, .py, .jar) have all to be run from command line so:
https://sikulix-2014.readthedocs.io/en/latest/faq/010-command-line.html#how-to-run-sikulix-from-command-line

A solution to pack a script as a standalone executable jar (no SikuliX needed on the executing machine) will only be available in 2.0.5

**Comment by anggafsahid** [comment]
I am Sorry for asking questions with unrelated topic and closed ones.

Thank you so much for the answer. now everything is clear,
good luck for the SikuliX 2.0.5

**Comment by kodi-beta** [comment]
Nice thread I had similar issue, Installed 64-bit java 8 version and now SikuliX started working.
