### ISSUE TITLE
Sikulix IDE 2.0 vs Prior IDE

### ISSUE THREAD

**Issue by bartclark** [RaiMan/SikuliX1#225]
This one should be an easy question but I cannot figure out how to get the 'Mouse Actions' and 'KeyBoard Actions' area of the IDE to show up in SikuliX 2.0

I have included a couple of screen shots for comparison.....
<img width="249" alt="SikuliX Find Mouse Actions Keyboard Actions" src="https://user-images.githubusercontent.com/57495813/68637792-5a672900-04c5-11ea-91fe-4ef618d2d0cf.png">

See in the above IDE you have a area to the left that begins with "Settings", then "Find", then "Mouse Actions", and finally "Keyboard Actions"

Yet with the SikuliX 2.0 IDE I cannot find this area....

![Sikulix 2 0 IDE where is mouse actions panel](https://user-images.githubusercontent.com/57495813/68637891-900c1200-04c5-11ea-842d-9c3233706aa3.png)

Thanks for any suggestions!

bc

**Comment by bartclark** [comment]
I see that the Command Window is temporarily not activated since SikuliX 1.4

Has anyone found a good workaround?  I use the listed commands ALOT.  I would not like to go back to 1.3 but can if that is the only solution.

Thanks,

bc

**Comment by RaiMan** [comment]
@bartclark 
Sorry for the inconvenience (removing the commandbar from the IDE).

Version 2.1.x will have a more general autocompletion feature (in a while ;-).

Versions up to 1.1.4 are no longer supported.
