### ISSUE TITLE
IDE: Make some changes, get blank Delete images on save dialog

### ISSUE THREAD

**Issue by balmma** [RaiMan/SikuliX1#229]
Transferred from https://bugs.launchpad.net/sikuli/+bug/1842156.

does not happen all the time, but i was working with a project and made some changes, then I get a blank Delete images on save dialog. The only way out is to use Task manager and kill java. See png.

1.1.4 on Win10 Pro

**Comment by balmma** [comment]
This seems to happen when there are syntax errors in your script. I'm currently anyway working on the image/screenshot handling for the new recorder feature and will fix this with one of my next PRs to master.

**Comment by balmma** [comment]
BTW not all syntax errors. Mainly not properly closed Strings. Something like Pattern("12345.png"").

**Comment by balmma** [comment]
Found the bug. It is only indirectly releated to the syntax error. The problem is that the syntax error (incomplete String) triggers a popup and the popup (SX class) is then opened outside the UI thread. Will provide a separate PR for this shortly.
Issue should be transfered to Github.

**Comment by balmma** [comment]
Solved with #230

@RaiMan  
BUT I ask myself if it is a good idea in general to ask the user whether he wants to delete the images or not. Furthermore the message and the question are confusing anyway. The user simply has no other option than saying "yes" (yes in this case means "do NOT delete"), saying no seems to be too dangerous. So the popup doesn't make too much sense here. I would prefer omitting the popup entirely and just do not delete the images in such a case. If you agree I will implement this together with the new screenshot handling.

**Comment by RaiMan** [comment]
@balmma 
Since the whole scan logic with "delete not used images" is only about finding "someImage.png" patterns, the only reason for getting this popup is the uncomplete String situation (no closing on the same line).
... and usually this only happens in commented lines, since normal syntax errors like uncomplete string should not be there, if the script has been run before.
I will have look into it and in a first step revise the popup, so it makes more sense.
Then I will check, wether the scan can be fixed, to only ignore this line/comment.
IMO the user should be informed, that the intended "delete images on save" had a problem, that should be fixed (with the information about the line where to start the examination). 

Made a separate issue for that: #231

**Comment by balmma** [comment]
> IMO the user should be informed, that the intended "delete images on save" had a problem, that should be fixed

Agreed. But IMHO it should rather just be an info popup without the option to delete the images anyway. Something like:

The automatic image cleanup went wront due to an incomplete string on the following line. 
... 
| OK |

 Klicking "no" (and  delete the images anyway) in the current popup might just be a bad choice and this option should not even be given to the user.

**Comment by balmma** [comment]
Or probably the error message on the console is already enough.

**Comment by RaiMan** [comment]
> Or probably the error message on the console is already enough.

Not in the cases where there is no console (jar double-clicked and problem is during quit processing)

**Comment by balmma** [comment]
> Not in the cases where there is no console

I mean the EditorConsolePane on the right side. Does this ever happen during quit processing?

**Comment by RaiMan** [comment]
> Does this ever happen during quit processing?

yes, if there is something left to be saved and you confirm/save.

**Comment by RaiMan** [comment]
.... but I will check this anyways and finally decide ;-)

**Comment by balmma** [comment]
> yes, if there is something left to be saved and you confirm/save.

OK yes, good point
