### ISSUE TITLE
Why does my IDE have no api instructions（such as “rightClick” or “doubleClick”)   on the left side（mac os 10.14.5）

### ISSUE THREAD

**Issue by Chersh-Pan** [RaiMan/SikuliX1#235]
Why does my IDE have no api instructions（such as “rightClick” or “doubleClick”)   on the left side（mac os 10.14.5）

**Comment by RaiMan** [comment]
With 2.0.x this feature is no longer available.

2.1.0 will bring it back as a more general solution (auto-complete)
