### ISSUE TITLE
java.lang.IllegalArgumentException: Key: Not supported character: m

### ISSUE THREAD

**Issue by Revarye** [RaiMan/SikuliX1#241]
This only started happening from version 2.0.0.
I was using 1.1.4 previously.

My SikuliX Java program is started through a Windows .bat file.
If I run it from the command prompt, it's ok.
However, if I double-click to run the .bat, this exception is thrown:
![Capture](https://user-images.githubusercontent.com/7857107/69290122-cff79580-0c39-11ea-8556-f9a98ee2f888.PNG)

The line in my program is `S.type("m", Key.WIN);`

**Comment by Revarye** [comment]
Hello,
I resolved the problem by adding English (United States) to my list of languages. The first language in my list is another variant of English.

**Comment by balmma** [comment]
For which variant of English it doesn't work?

**Comment by Revarye** [comment]
Specifically, English (Singapore) and English (United Kingdom).

**Comment by balmma** [comment]
And which keyboard layout?

**Comment by balmma** [comment]
The key you want to type has to be present on the defined keyboard layout.

**Comment by Revarye** [comment]
US keyboard:
![Capture](https://user-images.githubusercontent.com/7857107/69347615-c27cf280-0caf-11ea-8e19-90fd13b0c256.PNG)

I typed the Windows key and m, nothing special.

**Comment by balmma** [comment]
Allright, this combination seems to work flawlessly on my side. Are you on Windows 10 or Windows 7? Don't you have `Settings.AutoDetectKeyboardLayout = False`, do you?

**Comment by Revarye** [comment]
It works for me when I add English (United States). If it's only English (Singapore) and/or English (United Kingdom), I get the exception. Could you please try it without English (United States) on your side?

I'm on Windows 10 and `Settings.AutoDetectKeyboardLayout` is the default which is `true`.

**Comment by balmma** [comment]
NOW I finally got what your setup is. You just added US English but still used the Singapore English layout?

Still can't reproduce it on my machine. Even when I remove the en_US layout and reboot, it still works flawlessly. Probably because it was installed once? Can you still reproduce the issue if you remobe en_US now?

**Comment by Revarye** [comment]
Yup, I'm still using English (Singapore). I didn't have English (United States) in my language list for versions 1.1.4 and below. Only added it because I encountered the exception in 2.0.0 and was troubleshooting.

As long as English (United States) is in my language list, it works fine. If I remove English (United States), I can reproduce the exception every time when double-clicking to run the .bat

It may be something specific to my machine, since you don't get the exception on your side. Thanks for your investigation and testing.

**Comment by Deliaz** [comment]
I had the same issue in macOS 10.15
After installing jdk-13.0.1_osx-x64_bin from the official website it has been fixed.

**Comment by jdwilliamsDXCAS** [comment]
I had the same problem with English Canada.  I switched to English United States as my keyboard layout and all is working again.
