### ISSUE TITLE
Auto delete images accidentally on save, no way to revert

### ISSUE THREAD

**Issue by balmma** [RaiMan/SikuliX1#243]
This has already happened to me (and my Engineers) several times.

The main problem here is, that I automatically press ctrl+s probably every 20 keystrokes (or after a block or paragraph, don't know exactly, this happens automatically due to muscle memory :-)). So it sometimes happens that I accidentally remove a pattern, press ctrl+s and want to undo it afterwards. But then the image is already gone and there is no (reasonable) way to get it back.

It would be nice to have kind of a trash for automatically deleted images where images can be restored from. The trash directory could live in the bundle directory (as .trash) and can be automatically deleted as soon as the SikuliX IDE gets terminated. I don't think that there is a need to keep it any longer.

@RaiMan 
You can assign this issue to me if you consider it useful. Will implement it after the other PRs are merged.

**Comment by RaiMan** [comment]
Good point - good idea.
Agreed and assigned :-)

**Comment by balmma** [comment]
Not needed anymore with measures from this dicussion:

https://github.com/RaiMan/SikuliX1/commit/6c6d468e71941034b81425859bcbc4cc9a5dae03#commitcomment-36085279
