### ISSUE TITLE
There was a problem executing the click method a second time

### ISSUE THREAD

**Issue by Chersh-Pan** [RaiMan/SikuliX1#249]
I run a script, such as:

import time
click("1.png")
time.sleep(5)
click("2.png")

the first click, click("1.png") can run normal, but click("2.png") invalid。

**Comment by RaiMan** [comment]
SikuliX version?
Java version?
What system?

What are the exact symptoms? Error messages?

**Comment by Chersh-Pan** [comment]
SikuliX 2.0.1
Java 8
macOS 10.14.5

I use SikulixIDE run script, no error messages, the phenomenon is the second time click can see find "2.png", but the mouse not click

**Comment by RaiMan** [comment]
On macOS this usually happens, if the target application does not have the focus (the click only gives focus, but is ignored - subsequent clicks will work)

Try with switchApp() or doubleClick() (only the first click going to the app not having focus).
