### ISSUE TITLE
[1.1.4] JRuby: sikulixapi.jar: NameError: missing classname: ImageFinder 

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#25]
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
`jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [mswin32-x86_64]`

`sikulix v1.1.0.3 (gem)`

`Win10 pro (64bit)`

Using the latest version I get the following exception: 

> NameError: missing class name (`org.sikuli.script.ImageFinder')
    method_missing at org/jruby/javasupport/JavaPackage.java:258
  <module:Sikulix> at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:23
            <main> at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/sikulix-1.1.0.3/lib/sikulix/sikulix.rb:7

The elder sikulixapi.jar worked/works reliably.

**Comment by RaiMan** [comment]
Added dummy classes for ImageFinder/ImageFind (had been deleted due to being obsolete).

The actual build from today should work (#72)

**Comment by RaiMan** [comment]
Uuups, one more thing ... ;-)

... try build #73 in some minutes.

**Comment by RaiMan** [comment]
What version has this working "elder sikulixapi.jar"?

**Comment by RaiMan** [comment]
ok, added a dummy for class Keys.

as mentioned: build #73

The working version must have been a 1.1.0 or 1.1.1 !?

**Comment by PfrLisBerndt** [comment]
Cannot definitly say, I mean it was 1.1.2.

Btw Since Your last fix it´s working, but now I got an issue with setautowaittimeout-method; apparently not working. Will open a new issue.

**Comment by RaiMan** [comment]
ok, thanks.

Version does not matter anymore ;-)
