### ISSUE TITLE
Sikuli writes dll in temp dir during startup and can therefore not be whitelisted

### ISSUE THREAD

**Issue by whustedt** [RaiMan/SikuliX1#251]
Hi, I have to use Windows 10 Device Guard at work, so executables have to be whitelisted to be usable. 
Unfortunately Sikuli writes executable code (a dll file) in a temporary directory during Startup, so there is no way to whitelist that. 

Could you prevent this or put this dll in a static place? For me this is a blocker and I cannot use this application anymore. 

![1BE9255A-3A4D-4E3A-B7DB-E4E2DBEBA595](https://user-images.githubusercontent.com/3454347/70145358-289a4a00-16a0-11ea-96eb-a01f670125a4.gif)

**Comment by balmma** [comment]
Those are DLLs extracted automatically by JNA. You can specify the path for temporary files using the `jna.tmpdir` property.

e.g. `java -Djna.tmpdir=C:/temp` -jar sikulix.jar`

Do you have to whitelist individual DLLs or can you also whitelist a directory?

**Comment by balmma** [comment]
BTW. if you want all temporary files to be written to a specific location you can also set the `java.io.tmpdir` property.

e.g. `java -Djava.io.tmpdir=C:/temp -jar sikulix`

**Comment by whustedt** [comment]
Thank you for the quick assistance! 
I was able to whitelist all necessary dlls.
