### ISSUE TITLE
Problem updating sikuli to sikuli 2.0.1. Vision package does not exist. 

### ISSUE THREAD

**Issue by angelvillalobos303** [RaiMan/SikuliX1#253]
```
Sikuli version: 2.0.1
OpenJDK
Windows 64-bits
```

I used _Vision_ to set Parameter of target Size:

```
> from org.sikuli.natives import Vision
> 'Vision.setParameter("MinTargetSize", 18)'
```
However, when I have updated Sikuli to work with openJDK, I realized that there is no Vision. 
Please, how can I fix this problem?
Thank you.

**Comment by RaiMan** [comment]
Since the OpenCV usage is completely revised against 1.1.x (no more native code - everything at the Java level), there is no more Vision module.

Just remove this setting. It did never really make sense anyways.
