### ISSUE TITLE
[1.1.4] setAutoWaitTimeout apparently not working

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#26]
Sikulix doesn´t wait the specified time anymore; immediately cancels when a picture is not on screen.

**Comment by RaiMan** [comment]
might be with find() 
see:
https://sikulix-2014.readthedocs.io/en/latest/news.html#revision-of-the-find-api

**Comment by PfrLisBerndt** [comment]
Got it!
- Simply put wait(...) before click(...)
Thanks, nice WE!

**Comment by RaiMan** [comment]
Oh no, that was not intended: click and all the other action features with an internal find op should respect the autoWaitTimeout setting. I have to revise that.

My recommendation: Do not change anything for now - wait for the new build latest on Monday.

Thanks for finding and nice WE also.

**Comment by RaiMan** [comment]
ok, fixed.
mouse and key actions now wait again according to autoWaitTimeout settings.
