### ISSUE TITLE
HighDPI support

### ISSUE THREAD

**Issue by firestar9114** [RaiMan/SikuliX1#27]
**see bug:**
https://bugs.launchpad.net/sikuli/+bug/1730645

**some insights with Java 8 and 13**

If you know the scaling factor, that has to be applied to all images, to work in the new environment, then you can use
`Settings.AlwaysResize = <factor>`
where `<factor>` is a decimal denoting the scaling to be applied.
Internally the scaling will be applied to every image before it is used in search.

Tested on Windows 10:
- with Java 8 having taken images with a scaling factor of 100% (Windows screen settings) a factor of 1.2 helps, when running the script with scaling of 125%.

- with Java 13 nothing has to be done in this scenario. The search works and even the mouse position is correct.

Still I do not have an environment to test with a hiDPI display.

---------------
**original statement**

Um, so it looks like the program doesn't support scaling right.  Please add a way to scale the GUI so it is usable on highDPI displays.  I've included a screenshot below: 

https://i.imgur.com/TjJ2cAd.png

**Comment by RaiMan** [comment]
Try with Java 10: 
the net says, that Java 10 now automatically scales Java apps like SikuliX IDE run as
``java -jar sikulix.jar``

I cannot test it, since I do not have a hiDPI display.

But I can confirm, that on my MacBook Pro Retina the scaling worked since Java 7 and now with Java 10 everything is clear and non-blurry (hence something has again changed to even better).

**Comment by RaiMan** [comment]
see bug:
https://bugs.launchpad.net/sikuli/+bug/1730645

**Comment by bartclark** [comment]
Has anyone with a hiDPI display and newer versions of Java tried this?  Wow!  This would be incredibly useful (even if you had to match 'factors' of scaling....as in the past switching to my MacBook Pro 15" broke most scripts).

bc

**Comment by RaiMan** [comment]
@bartclark 
If you know the scaling factor, that has to be applied to all images, to work in the new environment, then you can use
`Settings.AlwaysResize = <factor>`
where `<factor>` is a decimal denoting the scaling to be applied.
Internally the scaling will be applied to every image before it is used in search.

Just tested on Windows 10:

- with Java 8 having taken images with a scaling factor of 100% (Windows screen settings) a factor of 1.2 helps, when running the script with scaling of 125%.

- with Java 13 nothing has to be done in this scenario. The search works and even the mouse position is correct.
(if you are interested in using Java 13 on Windows 10, come back for the HowTo)

I now really have to find a way now to understand all this, be able to test it and tell SikuliX how to deal with it - and talk about in the docs finally.

**Comment by RaiMan** [comment]
no longer relevant with Java 11+
