### ISSUE TITLE
Setup Development Environment 

### ISSUE THREAD

**Issue by mcoderr** [RaiMan/SikuliX1#274]
Hi,

How to setup development Environment for SikuliX1 contribution  ?
I have windows machine, java8, Eclipse IDE.

Thank you in advance.

**Comment by RaiMan** [comment]
Just setup a Maven project with the existing sources and the pom's from a fork.

**Comment by PfrLisBerndtHome** [comment]
Few weeks ago I tried to get the API project by the eclipse IDE. I got the most sources, but some with „tulskiy"(or similar) in the directory name are missing. Therefore I gave up for the moment. 
Do I have to add them by hand? (Yet not that familiar with git version control)

**Comment by RaiMan** [comment]
@PfrLisBerndtHome 
Nothing else needed - the sources on GitHub are complete.

Just start by simply downloading the .zip.

You might step into forking later, when you have your project set up.
see my comment above.

**Comment by PfrLisBerndtHome** [comment]
Ok, I set up from the zip a maven project.
But two questions came up to me: 

a) How do I test my changes quickly? - e.g. I change Sikulix.java; How do I execute the program directly out of the ide? 
When I set up for that purpose a java project pointing at the local repository I'm facing my former problem that the tulskiy-sources are not included and the program is not executable.

b) How do I commit my changes? Participating the git way I see the corresponding options (though I cannot execute the program as well). But as maven project I see no possibility to update, commit and so on.

**Comment by PfrLisBerndt** [comment]
Well, by trying out I found out, that I have to import the sources as java project.
Now, it seems, I could commit changes I make so question b) is obsolete.

Still question a) is not fully cleared. -How to stat the API by the Eclipse IDE? - Running/Debugging SikulixAPI.java , I get the following error: 

> [ERROR] org.sikuli.script.SikulixAPI: unauthorized use. Use: org.sikuli.script.Sikulix


Using Sikulix.java returns:
>Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 84
Exception Details:
  Location:
    org/sikuli/basics/Debug.endTiming(Ljava/lang/String;Z[Ljava/lang/Object;)J @84: ldc_w
  Reason:
    Type uninitialized 70 (current frame, stack[2]) is not assignable to uninitialized 66 (stack map, stack[2])
  Current Frame:
    bci: @75
    flags: { }
    locals: { 'org/sikuli/basics/Debug', 'java/lang/String', integer, '[Ljava/lang/Object;', long, long_2nd, long, long_2nd }
    stack: { uninitialized 66, uninitialized 66, uninitialized 70, uninitialized 70, integer }
  Stackmap Frame:
    bci: @84
    flags: { }
    locals: { 'org/sikuli/basics/Debug', 'java/lang/String', integer, '[Ljava/lang/Object;', long, long_2nd, long, long_2nd }
    stack: { uninitialized 66, uninitialized 66, uninitialized 66, uninitialized 66 }
  Bytecode:
    0x0000000: 2ab4 009e 0994 9a00 1513 028d 04bd 0003
    0x0000010: 5903 2b53 b802 6314 0095 adbb 0221 59b7
    0x0000020: 0223 b602 3937 0416 042a b400 9e65 3706
    0x0000030: 1c9a 0008 2a09 b500 9e12 612b b600 ad9a
    0x0000040: 004c bb01 8259 bb01 8259 1c99 0009 1302
    0x0000050: 8fa7 0006 1302 91b8 0192 b701 9513 0293
    0x0000060: b601 97b6 019b 04bd 0003 5903 1606 8913
    0x0000070: 0295 6eb8 0296 53b8 01ca b801 92b7 0195
    0x0000080: 2bb6 0197 b601 9b2d b802 6316 06ad     
  Stackmap Table:
    same_frame(@27)
    append_frame(@57,Long,Long)
    full_frame(@84,{Object[#1],Object[#174],Integer,Object[#480],Long,Long},{Uninitialized[#66],Uninitialized[#66],Uninitialized[#66],Uninitialized[#66]})
    full_frame(@87,{Object[#1],Object[#174],Integer,Object[#480],Long,Long},{Uninitialized[#66],Uninitialized[#66],Uninitialized[#66],Uninitialized[#66],Object[#174]})
    same_frame(@139)

	at org.sikuli.script.support.RunTime.start(RunTime.java:59)
	at org.sikuli.script.Sikulix.main(Sikulix.java:21)

I don´t understand this message...

**Comment by RaiMan** [comment]
It does not make sense, to run the SikuliX API as main. You should setup tests in the project, which then can be used to develop/test/debug your changes/fixes.

About your problem: I do not understand it either.

I am using IntelliJ IDEA, which in my experience is less complex and more user friendly than Eclipse.
So I cannot help you with your dev situation.

> `at org.sikuli.script.support.RunTime.start(RunTime.java:59)`

It looks like you are not using the latest master version, since at this line there is no crashable statement.

Eclipse uses its own Java compiler. I always had problems with that even in IDEA.
So I generally use the javac compiler. Look for an option in your build setup.

**Comment by RaiMan** [comment]
No idea. I am using IntelliJ IDEA (switched from Eclipse some years ago) and had many problems using the Eclipse compiler (which is the standard in IDEA too) and switched to the Java`s own compiler javac. So look for an option in your build setup.

It does not make sense, to "start" the SikuliX API (only if you wanted to run scripts from commandline), but you have to "use" the API in your code.

The easiest is, to use the test environment in your project.

**Comment by ndinev** [comment]
I am facing some problems to build and run sikulixide 2.0.5

```
D:\work\SikuliX1>java -jar IDE\target\sikulixide-2.0.5.jar
no main manifest attribute, in IDE\target\sikulixide-2.0.5.jar
```

Here are some details:
Windows 10x64
Java13
SikuliX cloned from github and switched to release_2.0.x branch
mvn clean install -> green

Note: I was able to run build form master and start IDE, but it can't capture images (I know at the moment 2.1.x in not usable)

**Comment by RaiMan** [comment]
I will check and come back.

**Comment by RaiMan** [comment]
@ndinev 
You have to activate one of the `complete-jar` profiles or name the profile with the `mvn` command.

**Comment by ndinev** [comment]
Thanks! This worked

Just for reference i executed `mvn clean install -P complete-win-jar`

**Comment by RaiMan** [comment]
Exactly :-))

**Comment by ndinev** [comment]
I was successfully build v2.0.5 before but now just pulled latest changes and build failed with this error. Any Ideas how to fix it?
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for sikulix 2.0.6-SNAPSHOT:
[INFO]
[INFO] SikuliX API ........................................ FAILURE [  1.156 s]
[INFO] SikuliX IDE ........................................ SKIPPED
[INFO] sikulix ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.523 s
[INFO] Finished at: 2021-03-20T22:58:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sikulixapi: Could not resolve dependencies for project com.sikulix:sikulixapi:jar:2.0.6-SNAPSHOT: The following artifacts could not be resolved: com.sikulix:sikulix2tigervnc:j
ar:2.0.5, com.sikulix:sikulix2android:jar:2.0.5: Failure to find com.sikulix:sikulix2tigervnc:jar:2.0.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted un
til the update interval of central has elapsed or updates are forced -> [Help 1]

```

**Comment by RaiMan** [comment]
@ndinev 
Sorry for the temporary inconveniences. Too many things in parallel :-((

The 2.0.6-SNAPSHOT in fact does not really work in the moment.

The build problems you have are caused by the fact that the missing artifacts are not yet on MavenCentral.

If you really want to get it running in the moment, you have to fork the respective projects and build to your local repo.
This is how I do that in the moment.

After having fixed the basics during the next week hopefully, I will start again to have snapshot versions on push (GitHub action) available.

So I ask you to wait a bit. Thanks.

**Comment by ndinev** [comment]
Ani instructions would be helpful

**Comment by fz0000** [comment]
@ndinev try to checkout the repos ([sikulix2android](https://github.com/RaiMan/sikulix2android.git) and [sikulix2tigervnc](https://github.com/RaiMan/sikulix2tigervnc.git)) in your project, them maven install them.
And don't foget to configure SDK 1.8 for these 2 modules:
![image](https://user-images.githubusercontent.com/5061311/117559470-40a5a280-b0b8-11eb-9b5f-5124056318fa.png)
