### ISSUE TITLE
Java 11 (LTS) as minimum requirement

### ISSUE THREAD

**Issue by RaiMan** [RaiMan/SikuliX1#275]
Public support for Java 8 only until late 2020

**Comment by balmma** [comment]
Would really appreciate that as it would allow to ditch some hacks only needed for Java 8 backwards compatibility.

**Comment by balmma** [comment]
But should be done with SikuliX 3.0.0 because it is definitely a breaking change.

**Comment by RaiMan** [comment]
Sorry, did not want to disturb you on Christmas Eve ;-)

... yes agreed
... but I leave it for now ;-)

**Comment by balmma** [comment]
Have to turn off my issue watcher :-)

**Comment by RaiMan** [comment]
no longer relevant
