### ISSUE TITLE
Get the PythonInterpreter instance from JythonSupport

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [RaiMan/SikuliX1#276]
With version 1.1.4-SNAPSHOT it was possible to customize [`PythonInterpreter`](https://www.javadoc.io/static/org.python/jython-standalone/2.7.1/org/python/util/PythonInterpreter.html).

In version 2.0.1 [JythonSupport](https://github.com/RaiMan/SikuliX1/blob/master/API/src/main/java/org/sikuli/script/runnerSupport/JythonSupport.java) handles some behaviour of `PythonInterpreter`, like:

- interpreter.close()
- interpreter.setErr(), .setOut()
- interpreter.eval()
- interpreter.exec()
- .....

but I cannot call `interpreter.set()` for making accessible to my Jython scripts some internal Java objects.

I propose to add a new method to `JythonSupport` called `getInterpreter()`, otherwise I have to use relfection in order to access it, and will be denied in future Java versions.

I can provide a pull request if needed.

**Comment by RaiMan** [comment]
The internal implementation is completely revised and not really intended for public use.

But I accept your request and will add a method
`public org.python.util.PythonInterpreter interpreterGet() {...}`
(naming according to the revised state)

To use it, you will have to use it so:
JythonSupport.get().interpreterGet()

Will be available in 2.0.2 and in 2.1.0 nightly the next days.

**Comment by RaiMan** [comment]
added: 2019-12-26 in 2.0.2 (https://github.com/RaiMan/SikuliX1/commit/f1f78a87da574959a2df61f4b3b698501b43b19e) and 2.1.0 (https://github.com/RaiMan/SikuliX1/commit/2a0c3923070d72e0fa0f22775c3e46200545a58e)

**Comment by DavidPerezIngeniero** [comment]
Thanks once more RaiMan!
Of course you can change non-public APIS whenever is needed.
