### ISSUE TITLE
Instruction for installing open cv 4 on linux are missing

### ISSUE THREAD

**Issue by ndinev** [RaiMan/SikuliX1#279]
I was redirected here after starting Sikuli 2 and trying to work with images to in order to configure opencv: https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-Libraries-for-OpenCV-4

However The Linux part seems uncompleted. Since 2.x is official I would expect to have instruction for installing opencv4

**Comment by balmma** [comment]
On Ubuntu 18.04 I installed OpenCV following the steps provided here: https://www.learnopencv.com/install-opencv-4-on-ubuntu-18-04/?_gl=1*hzofr5*_ga*YW1wLVA3SkUxdlVEZXduZERmVmJ0c0xIcndKdkdLWWxLVHZ5Z3pGNFFnT2FWd05pM3hLbVluMUFOUE5sMTRfckxvRHk.

**Comment by balmma** [comment]
For SikuliX you don't need the contrib stuff BTW.

**Comment by balmma** [comment]
And you should set cvVersion to 4.1.1 instead of master.

**Comment by RaiMan** [comment]
I have revised the mentioned page.
thanks to @ndinev and @balmma
