### ISSUE TITLE
[1.1.4] error RunTimeAPI on VM native libraries not found

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#28]
Hello again!

I got problems using sikulixapi.jar for textrecognition on a vm.

> [error] RunTimeAPI: *** terminating: TextRecognizer: start: native libraries not found.

On my local pc it´s working fine.

System properties of the vm: 

> WIN7 Prof 64bit, SP1, Java Version: 1.8.0_181 Java SE Runtime Environment, jruby 9.2.0.0

It´s definitely no occasional problem; all my vms show the same behavior. But I can´t except for my windows version identify differences concerning the system properties.

**Comment by RaiMan** [comment]
Can you run the IDE on such a VM using
`` java -jar sikulix.jar -v -c``  
from a commandline
and then in the IDE run this one line
`` print selectRegion().text()`` 

If running the IDE GUI is not possible, make a .sikuli and run as
`` java -jar sikulix.jar -v -r test.sikuli``

... send the debug output to my mail  (see: https://github.com/RaiMan)

**Comment by PfrLisBerndt** [comment]
Your hint helped me!
To the others: Ensure the latest Visual C++ Red. Pack. (>=2013) being installed!

**Comment by RaiMan** [comment]
Thanks for confirmation. I put it in the docs.
