### ISSUE TITLE
Trying to build with Maven and JavaFX11

### ISSUE THREAD

**Issue by BUCKFAE** [RaiMan/SikuliX1#282]
Hello,
i am trying to build a JavaFX Desktop app using Sikulix as well as JavaFX on Java11. I want to export the project so someone can either install it on their system (i don't even know if this is needed) or just run the project. As far as i know 'mvn clean javafx:jlink' would be the way to go for this?

However if i try this i get the following error: <br>
```
[WARNING] Required filename-based automodules detected. Please don't publish this project to a public artifact repository!
Required filename-based automodules detected. Please don't publish this project to a public artifact repository!


Error: automatic module cannot be used with jlink: sikulixapi from file:/<path hidden>/.m2/repository/com/sikulix/sikulixapi/2.1.0-SNAPSHOT/sikulixapi-2.1.0-SNAPSHOT.jar
[ERROR] Command execution failed.
Command execution failed.

```

My pom.xml
```xml
   <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.openjfx</groupId>
                    <artifactId>javafx-maven-plugin</artifactId>
                    <version>0.0.3</version>
                    <configuration>
                        <source>11</source>
                        <target>11</target>
                        <release>11</release>
                        <mainClass>myFirstProject.Main</mainClass>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <repositories>
        <repository>
            <id>sonatype-ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.6.0-RC1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11</version>
        </dependency>
    </dependencies>
```

I have an module-info as well:
```java
module myFirstProject{
    requires javafx.controls; // JavaFX
    requires sikulixapi; // Searching for images
    requires java.desktop;

    opens myFirstProject.ui to javafx.controls;
    exports myFirstProject.ui to javafx.graphics;
}
```

I'd like to apologize in advance, english is not my first language and i am new to building javaFX projects with maven (usally i am using gradle, but gradle did not seem to work with sikulix?)

**Comment by RaiMan** [comment]
sikulixapi currently is not modularized in the sense of Java 9+.

Try without the 
` requires sikulixapi;`

**Comment by BUCKFAE** [comment]
If i do that in the class that uses sikuli
```
import org.sikuli.script.FindFailed;
import org.sikuli.script.Match;
import org.sikuli.script.Screen;
```

Can't be imported.

**Comment by RaiMan** [comment]
for new projects take care, that source level and target level are set to Java 8 (minimum).

For the JavaFX and using Java modules I cannot help you further - look into appropriate help forums.

**Comment by BUCKFAE** [comment]
I've just managed to fix it using the maven shade plugin. I assume that you will modularize the project sooner or later right? 

Thank you for your great work!

**Comment by danielemaddaluno** [comment]
> I've just managed to fix it using the maven shade plugin. I assume that you will modularize the project sooner or later right?
> 
> Thank you for your great work!

@BUCKFAE  can you please give more precise details about how you solved the problem with maven shade plugin?

**Comment by BUCKFAE** [comment]
> > I've just managed to fix it using the maven shade plugin. I assume that you will modularize the project sooner or later right?
> > Thank you for your great work!
> 
> @BUCKFAE can you please give more precise details about how you solved the problem with maven shade plugin?

@danielemaddaluno i am sorry but I didn't use neither Sikuli nor JavaFX for quite some time now. Unfortunately i did not properly backup my old projects (as they weren't anythin serious, i was just playing a bit around) and I am not entierely sure anymore what resolved my issue. 

If i recall correctly i did not get it to work with Java 11 and switched back to Java 8 (but not to sure about that). I am however pretty sure that i used the maven shade plugin to create a fat-jar. The fat-jar packs all dependencies the user could possibly need in one jar file.

If you don't explicitly need java you may have a look at PyAutoGUI. This is what i ended up using back then as i wanted to familiarize myself with python. 


I am sorry for not beeing able to provide a proper solution.

**Comment by RaiMan** [comment]
@danielemaddaluno 
Are you playing around with the current state of the SikuliX GitHub repo (fork)?
If yes: branch master not useable - use the branch release... 
`mvn clean install` at project level should build fat jars api and ide.
Be aware: you then have version 2.0.5, which is not ready yet and has quirks.

Another option are the sources of the tag 2.0.4.
