### ISSUE TITLE
click does not work

### ISSUE THREAD

**Issue by RIn1314** [RaiMan/SikuliX1#283]
hello！pls！
I recognized the picture and clicked the game parcel button on the PC, but it didn't open. Is it the game's recognition mechanism or something else? Is it caused by clicking too fast?

**Comment by RaiMan** [comment]
You might better ask your question on [Launchpad ](https://answers.launchpad.net/sikuli).

There is a more adequate audience. Here is more about development.

Add information about your system, the Java version and the SikuliX used.
