### ISSUE TITLE
Documentation Errors 

### ISSUE THREAD

**Issue by pschaeffer** [RaiMan/SikuliX1#284]
Hi,

I just started a SikuliX project and noticed a couple of things.

Page https://sikulix-2014.readthedocs.io/en/latest/ has the following
“NOTE on Java usage The features in SikuliX at the bottom line are implemented with Java. So you might as well use SikuliX at this Java API level in your Java projects or other Java aware environments (see how to). Though this documentation is targeted at the scripting people it contains basic information about the Java level API as well at places, where there are major differences between the two API level.
Additionally you might look through the [JavaDocs (latest version)](https://raiman.github.io/SikuliX1/javadocs/overview-summary.html).”

The link to the JavaDocs does not work. Where are the actual SikuliX JavaDocs?

Page https://sikulix-2014.readthedocs.io/en/latest/faq/030-java-dev.html has the followin
“Other valuable information
Be aware, that some method signatures in the Java API differ from the scripting level.
•	Javadoc of SikuliX (latest version).”
The link to the JavaDocs does not work. Where are the actual SikuliX JavaDocs?

Actually, a link to the scripting API would be helpful as well. The “Complete Guide to Sikuli Script” link does not seem to work. 

Thank you

**Comment by RaiMan** [comment]
Thanks for the findings. I will try to do my very best ;-)

A workaround if you are programming in Java: In the Maven context there is a javadoc jar available

The heading `Complete Guide to Sikuli Script` is a bit too high in the sky ;-) There are some areas in the docs that have not been touched for years. Sorry.

In general it is recommended in any case, to at least read through the docs, to learn about the features available. 
For a start the Python level API descriptions are enough and can be adapted to the Java level easily.

**Comment by pschaeffer** [comment]
Mr. Hocke,

 

Sorry about posting in multiple place. I wasn’t sure which one to use. Which one should I use? Outlook.com? Github? Some other place? 

 

Thank you for the information below.

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Mr. Hocke,

 

I pulled the Javadoc.jar from the Maven site and extracted it. Works nicely.

 

Thank you

 

Peter Schaeffer

 

From: Peter Schaeffer [mailto:peter_schaeffer@yahoo.com] 
Sent: Monday, January 13, 2020 11:20 AM
To: 'RaiMan/SikuliX1'; 'RaiMan/SikuliX1'
Cc: 'Author'
Subject: RE: [RaiMan/SikuliX1] Documentation Errors (#284)

 

Mr. Hocke,

 

Sorry about posting in multiple place. I wasn’t sure which one to use. Which one should I use? Outlook.com? Github? Some other place? 

 

Thank you for the information below.

 

Peter Schaeffer

**Comment by RaiMan** [comment]
Choose a place that suites you best - but only one ;-)

... and please do not mail to GitHub and LaunchPad, butz edit the posts directly - it simply is nicer and easier

**Comment by RaiMan** [comment]
BTW: the javadocs are now back online also.

**Comment by pschaeffer** [comment]
Mr. Hocke,

 

Thank you

 

Peter Schaeffer
