### ISSUE TITLE
Problems reading the ratio of a video

### ISSUE THREAD

**Issue by Samuel98-f** [RaiMan/SikuliX1#285]
Hi 
I am currently working on a Project and therefore i want to calculate the aspectRatio of a Video. I`ve tried to use your libary and i got this far:
    public void getVideoRatio(String path) {
        int width = 1;
        int height = 1;
        EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        MediaPlayer mediaPlayer = mediaPlayerComponent.mediaPlayer();
        boolean prepare = mediaPlayer.media().prepare("path");
        boolean parse = mediaPlayer.media().parsing().parse();
        List<VideoTrackInfo> videoTrackInfo = mediaPlayer.media().info().videoTracks();
        List<TitleDescription> titles = mediaPlayerComponent.mediaPlayer().titles().titleDescriptions();
        for (VideoTrackInfo v : videoTrackInfo) {
            height = v.height();
            width = v.width();
            System.out.println(height + "\n" + width);
        }
        for (TitleDescription t : titles) {
            System.out.println(t.name());
        }

        float ratio = (float) width / height;
        System.out.println(ratio + Boolean.toString(parse && prepare)+ titles.size()+videoTrackInfo.size());
        video.setAspectRatio(ratio);
    }
The Problem i am facing at the moment is that my lists a empty although prepare and parse are true.
I am testing with a 1 sec long  .mp4 with a Resolution  of 342x182px 
Please help

**Comment by balmma** [comment]
I have no idea what project this code is for, but the bad line is most probably `mediaPlayer.media().prepare("path");`. Here you pass the String "path" instead of the variable. But this issue is most probably in the wrong project anyway :-)

**Comment by Samuel98-f** [comment]
oh my god im so sorry i dont know what happend i wanted to post this in the issues of the vlcj project

**Comment by balmma** [comment]
No worries. But did my suggestion help?

**Comment by balmma** [comment]
No worries. But did my suggestion help?

**Comment by Samuel98-f** [comment]
well the Suggestion to post this issue on the other Project did help indeed
https://github.com/caprica/vlcj/issues/914
but using the variable instead of its name is always a great idea ^^
thank you

**Comment by balmma** [comment]
:+1:
