### ISSUE TITLE
IDE: Run line selection does exclude images

### ISSUE THREAD

**Issue by tbussmann** [RaiMan/SikuliX1#288]
The "run selection" feature from #36 is very helpful. Unfortunately, I had to realise that if the selected code does contain an image (eg. a `click(<image>)` command) that image is not passed to the interpreter and an empty `click( )` is performed instead. The normal Run or "run to line" do work as expected. I can reproduce this with 2.0.1 on OSX 10.9.5 using Java 12.0.2+10 and on macOS 10.13.6 using Java 13.0.1+9

**Comment by RaiMan** [comment]
fixed with commit: https://github.com/RaiMan/SikuliX1/commit/9df17665fcb525933d1c2f1722526021a1678a09
