### ISSUE TITLE
macOS 10.9: IDE: interaction with line number column not possible

### ISSUE THREAD

**Issue by tbussmann** [RaiMan/SikuliX1#289]
#36 did bring some new feature in a popup menu which opens if you right click on the line numbers left to the code. Unfortunately, this does not work in 2.0.1 on OX 10.9.5 with Java 12.0.2+10. The only thing that the sidebar containing the line numbers does is to get darker on mouseover and to present a tooltip. Neither single nor double do perform any action nor does a right click present a context menu. Is there anything I can do to track this down? It does however work as documented in macOS 10.13.6 with Java 13.0.1+9

**Comment by RaiMan** [comment]
what about running Java 8?

**Comment by tbussmann** [comment]
Thanks for taking care! I did a test with Java 1.8.0_242-b08 without any change in behaviour. That machine is a VMware Fusion VM with the VMware Tools installed, if that makes any difference.

**Comment by tbussmann** [comment]
Oh - I just realise that you mention OSX 10.10 as a minimum system requirement on the [Quickstart page](http://sikulix.com/quickstart/) so my setup is likely unsupported at all. Bummer. I just was happy to get tesseract compiled there. My target application does not support anything higher, so I'm in kind of a deadlock. Thankfully the remaining parts of the IDE and Sikuli itself seem to work just fine on OSX 10.9.5.
