### ISSUE TITLE
macOS: KeyModifier mapping to wrong keys and Key not supported

### ISSUE THREAD

**Issue by tbussmann** [RaiMan/SikuliX1#290]
I'm having some trouble with the Modifier Keys in the `keyDown` and `click` methods on macOS using 2.0.1 (both on OSX 10.9.5 with Java 12.0.2+10 as well on macOS 10.13.6 with Java 13.0.1+9). I'm using the "Swiss German" input source. 

For debugging I'm showing the "Keyboard Viewer" window of the OS (To activate go to `System Preferences`, `Keyboard` and activate `Show Keyboard & Character Viewers in menu bar` then from the icon in menu bar `Show Keyboard Viewer`)

From the [docs](https://sikulix-2014.readthedocs.io/en/latest/keys.html) I've learned there are three variants to refer to the modifier keys:
1. newest: `Key.ALT`
2. older: `ModifierKey.ALT`
3. oldest: `KEY_ALT`

For this test I focus on the `ALT` key but I have seen others to misbehave as well. 

```
keyDown(Key.ALT) # ALT
wait(1)
keyUp(Key.ALT) 
type("aaaaaaaaa", Key.ALT) # ALT
#click(Location(107, 10), Key.ALT) #throws exception: TypeError: click(): 2nd arg can't be coerced to java.lang.Integer

keyDown(KeyModifier.ALT) # BACKSPACE!
wait(1)
keyUp(KeyModifier.ALT) 
type("aaaaaaaaa", KeyModifier.ALT) # ALT
click(Location(107, 10), KeyModifier.ALT) #ALT

keyDown(KEY_ALT) # BACKSPACE!
wait(1)
keyUp(KEY_ALT) 
type("aaaaaaaaa", KEY_ALT) # ALT
click(Location(107, 10), KEY_ALT) #ALT
```

So I have to use the oder `KeyModifier.ALT` with `click` while for `keyDown` the modern `Key.ALT` is the one that works. Unfortunately, my target application does even then not recognise the modifier key with `click` so I have to do it manually: 
```
keyDown(Key.ALT)
click(Location(130, 152))
wait(1)
keyUp(Key.ALT)
```
But as far as I can see that is not Sikuli's fault, maybe it's some kind of timing issue...

**Comment by balmma** [comment]
In 2.0.x only the ModifierKey.* method is allowed for mouse actions. In 2.1.0 this has already been fixed to also allow the Key.* method as well (PR #266). For keyboard actions both methods are already possible in 2.0.x.

So in 2.0.x the following options work:
```
keyUp(Key.ALT)
keyDown(Key.ALT)
click(Location(107, 10), KeyModifier.ALT) 
type("aaaaaaaaa", KeyModifier.ALT)
type("aaaaaaaaa", Key.ALT)
```

In 2.1.0 you can also use:
```
click(Location(107, 10), Key.ALT)
```

Those are invalid use cases and won't work as expected:
```
keyDown(KeyModifier.ALT)
keyUp(KeyModifier.ALT) 
```

**Comment by tbussmann** [comment]
Thank you for your explanations and the upcoming fix!

**Comment by balmma** [comment]
@RaiMan 

> keyDown(KeyModifier.ALT)
> keyUp(KeyModifier.ALT) 

Those two are using the following methods of Region:
```
public void keyDown(int keycode)
public void keyUp(int keycode)
```
Where keycode is the AWT key code. When we pass a modifier mask from KeyModifier, it is in fact mapped to a AWT key code. In the above case we pass `8` which is the same as `KeyEvent.VK_BACK_SPACE`.

Question is: Do we want to keep the methods where we can pass the key code? Are they really useful or rather confusing? Interestingly, we don't have those for the `type` method either.
