### ISSUE TITLE
getting NameError after edit of imported module

### ISSUE THREAD

**Issue by hulihlad** [RaiMan/SikuliX1#296]
I found a weird behavior of SikuliX + Python. My main application runs without any problems... But if i do any changes in imported module i got error

**NameError: name 'myLib' is not defined**

**If i restart my SikuliX program everything is okey again**... It is very annoning bug.. I rlly dont know how deal with that.. I will describe my situation more detailed:

.......................................................................

I have folder with my sikulix project:
`C:\project\ `
I have folder with main application:
`C:\project\application.sikuli`
I have folder with my module: (which i am importing to main application)
`C:\project\myLib.sikuli`

content of my module myLib:
```
from sikuli import *

def myFunc1():
    print(" myFunc1 ")
```

content of my main application:
```
import sys
sys.path.append("C:\project\myLib.sikuli")
from myLib import *

myFunc1()
```
.......................................................................

- If i run main application, " myFunc1 " is printed. Everything is okey without any problems.

- If i run my module myLib, nothing happens. Everything is okey without any problems.

- If i made any irrelevant changes in myLib module (for example, a new line at the end of a file) i m getting error:
```

Traceback (most recent call last):
  File '<string>', line 1, in <module>
NameError: name 'myLib' is not defined
[error] IDE: Run Script: internal error:
```

- I m getting this error if i run main application and also if i try to run myLib.

**If i restart my SikuliX everything is okey again.**.. New line at the end of myLib is not problem anymore.

Windows 10 64b
SikuliX IDE 2.0.1

**Comment by RaiMan** [comment]
This is normal behavior, since the IDE only has a static context for the Jython interpreter (not completely reset on restart of scripts in the same IDE session, to save the start-up time of some seconds).

[There is a note in the docs](https://sikulix-2014.readthedocs.io/en/latest/scripting.html#importing-other-sikuli-scripts-reuse-code-and-images) 
in the section `Some comments on general rules for Python import`

In your case using 
```
import myLib
from myLib import *
```

instead of only
```
from myLib import *
```
should help to trigger the reload on script rerun.

**Comment by hulihlad** [comment]
I confirm that this solution has helped. I'm sorry I was wasting your time. 
Thank you very much and have a nice day

task - invalid

**Comment by RaiMan** [comment]
accepted ;-)
