### ISSUE TITLE
Recorder: ... does not work properly for SHIFT key

### ISSUE THREAD

**Issue by RaiMan** [RaiMan/SikuliX1#297]
if I record my typing with shift I always got something like this:

type(u" ", Key.SHIFT + Key.SHIFT + Key.SHIFT + Key.SHIFT + Key.SHIFT + Key.SHIFT + Key.SHIFT + Key.SHIFT)

it always happen if I use any SHIFT/ALT/... key wit alfanumberic keys.

Please fix it. it is enoying that I have to delete in another editor.

Thank you for nice feature

[originally filed on Launchpad](https://bugs.launchpad.net/sikuli/+bug/1861285)

**Comment by balmma** [comment]
> Please fix it. it is enoying that I have to delete in another editor.

@RaiMan: You can assign this one to me :-)

**Comment by balmma** [comment]
Fixed with PR #301
