### ISSUE TITLE
RobotDesktop.keyUp() method throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by licham** [RaiMan/SikuliX1#298]
Hi!

I had some problems while using the keyUp() method. Before it, I called keyDown(int) method.
I suppose the problem is here (RobotDesktop class, 356 line):

    @Override
    public void keyUp(int code) {
        if (heldKeyCodes.contains(code)) {
            doKeyRelease(code);
            heldKeyCodes.remove((Object) code); //here is attemption to modify the collection while foreaching it
        }
    }

    @Override
    public void keyUp() {
        keyUp(heldKeys);
        for (int code : heldKeyCodes) { //here is foreach loop
            keyUp(code);
        }
    }

Isn't it better to iterate through the copy of the heldKeyCodes array?

**Comment by licham** [comment]
By the way, there is a #290 issue, where @balmma asks for the necessity of methods, that accepts key codes. Actually, I'm working with Japanese keyboard, so I need to somehow press such keys as `VK_HIRAGANA`, `VK_KATAKANA` etc. Unfortunately, I failed to understand how to do it in right way, even though there is a mappings for this keys in the Key class. So I'm using `keyDown(int)` method, and pass the key codes to it.
Is there a better way to do it?

**Comment by balmma** [comment]
> I had some problems while using the keyUp() method

What exact problems you had?

> Isn't it better to iterate through the copy of the heldKeyCodes array?

Shouldn't be much of a problem as long as you use the stuff in a single threaded manner. Otherwise you might get a ConcurrentModificationException.

**Comment by balmma** [comment]
> What exact problems you had?

I mean: Can you provide some example code? As said, this should not happen in a single threaded application.

> Isn't it better to iterate through the copy of the heldKeyCodes array?

Probably it would be even better to use a ConcurrentList instead.

**Comment by balmma** [comment]
> Unfortunately, I failed to understand how to do it in right way, even though there is a mappings for this keys in the Key class. So I'm using keyDown(int) method, and pass the key codes to it.

Are you working on Windows, Mac or Linux?

**Comment by licham** [comment]
Here is the code example:

    import org.sikuli.script.Screen;

    public class Main {
        public static void main(String[] args) {
            Screen screen = new Screen();
            screen.keyDown(241);
            screen.keyUp();
        }
    }

I'm working on Windows

**Comment by balmma** [comment]
> Isn't it better to iterate through the copy of the heldKeyCodes array?

Oh man, you'r right. My bad :-)

Should really iterate over a copy. Or use a stream filter. We will fix this ASAP. For the time being you can just use `screen.keyUp(241);`

**Comment by licham** [comment]
Okay, thanks

**Comment by balmma** [comment]
Fixed in PR #300

**Comment by licham** [comment]
So is there any approach to press Japanese specific keys using Key class?

**Comment by balmma** [comment]
> So is there any approach to press Japanese specific keys using Key class?

Not using the Key class, unfortunately. The Key class only contains constants for Keys on the en_US keyboard layout (Java AWT can only really handle those). Since SikuliX 2.0.0 we handle keyboard layouts a bit differently on Windows, so you can use every character you can physically see on your current keyboard layout using keyDown(String key).

**Comment by licham** [comment]
Ok, thanks

**Comment by balmma** [comment]
Just for my personal education: 

What characters have the HIRAGANA and KATAKANA keys printed on?

Sorry. I'm not at all familiar with the Japanese keyboard layout :-)

**Comment by licham** [comment]
Well, Japanese has more than one alphabet. Two of them are named hiragana and katakana, and, of course, they have different symbols.
So, Japanese keyboard has Japanese characters for the hiragana/katakana key

カタカナ
ひらがな
ローマ字

All three strokes are printed on one key. The key sends different codes based on the current input mode.
It means, that if you are actually using hiragana input mode, pressing this key will lead to sending KATAKANA key code due to switch to katakana mode. And if you are using katakana, the same key will send HIRAGANA key code to switch to hiragana input mode. Also this code changes when ALT or CTRL+ALT modifiers are applied.

Besides, Japanese keyboard has more buttons with Japanese symbols. Some of them are alphabet, and some are special keys (such as previously mentioned hiragana/katakana key).

![Japanese keyboard](https://upload.wikimedia.org/wikipedia/commons/c/cb/Surface_type_cover_JIS_keyboard_layout_blue.jpg)
