### ISSUE TITLE
Mouse.click method throws exception with null location

### ISSUE THREAD

**Issue by licham** [RaiMan/SikuliX1#299]
Hi!

There is a

    protected static int click(Location loc, int buttons, Integer modifiers, boolean dblClick, Region region)

method in the Mouse class (247 line). It has check for necessity of mouse moving

    ...
    boolean shouldMove = true;
    if (loc == null) {
      shouldMove = false;
      loc = at();
    }
    ...

Well, if the `loc` is `null`, mouse won't move. That is exactly what I want. However, when I'm trying to pass the `null` value to the

    public static Location click(Location loc, String action, Integer... args)

method (Mouse class, 192 line), that calls previously mentioned `protected` method and can be called outside of this class, it throws `java.lang.NullPointerException`, because it immediately calls `loc.isOtherScreen()`

    public static Location click(Location loc, String action, Integer... args) {
        if (get().device.isSuspended() || loc.isOtherScreen()) {
          return null;
        }
        ...

Should there be check for `null`?

**Comment by licham** [comment]
> Well, if the loc is null, mouse won't move. That is exactly what I want.

I mean, I don't want to send mouse move message to Windows, which i'm working with.

**Comment by RaiMan** [comment]
Not really sure, what you want.

... but a possible null-parameter should be checked before used and throw an IllegalArgumentException to point at the problem (not only NPE).

Mouse.click() is intended to click at the given location.
Hence it must move before, if the current mouse pos is different. 

If you want to click at the current position of the mouse pointer: `Mouse.at()`

**Comment by RaiMan** [comment]
[NPE is now IllegalArgumentException](https://github.com/RaiMan/SikuliX1/commit/487b8a921d7ae8f0b862d215afa83a433138e7d0)

**Comment by licham** [comment]
> Not really sure, what you want.

I have next code

    Mouse.click(Mouse.at(), "L");

When run it, if I'll hook Windows messages (posted by Windows after Sikulix has send input messages to it) , I receive MouseMove event, followed by MouseDown and MouseUp.
In other words, even if I'll click at the current cursor position, it leads to changing cursor's position to its current value and notifying Windows about it.
Is there some valuable reason to do this? My suggestion is to prevent sending mouse move input to the target OS, if the location is the same as cursor's. Something like modifying the

    protected static int click(Location loc, int buttons, Integer modifiers, boolean dblClick, Region region)

method's code

    ...
    boolean shouldMove = true;
    if (loc == null) {
        shouldMove = false;
        loc = at();
    }
    else {
        if (loc.equals(at())) {
            shouldMove = false;
        }
    }
    ...

The reason to do it is to prevent confusing, because it is unexpected that mouse will move when clicking at its current position.

**Comment by RaiMan** [comment]
[ok, understood and fixed.](https://github.com/RaiMan/SikuliX1/commit/aa69dc2c5873b461a603cabb5f7fe58ff68ab085)
