### ISSUE TITLE
runsikulix command not available after setup on MacOS 10.11.6

### ISSUE THREAD

**Issue by qualisign** [RaiMan/SikuliX1#3]
I dowloaded and installed v. 1.1.2 SikuliX (the repo for that version is archived so I can't post issues).  I can use the IDE to create and run scripts, but I can't get it to work from the command line, as the `runsikulix` command doesn't work.

$ runsikulix
-bash: runsikulix: command not found

I also tried doing it this way: 

open ./Applications/SikuliX.app -r ./agilent/test.sikuli

and I got this response:

open: invalid option -- r

Can you give me a pointer?  Thanks for the help and the tool (I think I'll be using it all the time now)

**Comment by RaiMan** [comment]
according to the bash conventions you have to be in the folder and say
`./runsikulix`
or
`. runsikulix`
or not being in the folder
`<sikulix-setup-folder>/runsikulix`
