### ISSUE TITLE
Can't run jython standalone script

### ISSUE THREAD

**Issue by DimaKudosh** [RaiMan/SikuliX1#30]
I can't run jython standalone script, I'm using sikulixapi.jar for version 1.1.4.
My script has following lines at the beginning of script:
```python
import org.sikuli.script.SikulixForJython
from sikuli import *
```
But when I'm trying to execute this script with following command `jython -Dpython.path=path-to-jar/sikulixapi.jar script.py` I got this error:
`[error] RunTimeINIT:  *** terminating: no valid Java context for SikuliX available (java.security.CodeSource.getLocation() is null)`

**Comment by RaiMan** [comment]
sikulixapi.jar must be on the Java class path (environment variable CLASSPATH)
