### ISSUE TITLE
2.0.2: JRuby: TextRecognizer not backward compatible when running with jruby from commandline.

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#303]
I faced the issue that executing my sikulix-wrapper directly with jruby the execution fails when addressing the TextRecognizer class. The RubyMine IDE on the other hand can still use its deprecated methods.

I had to address the OCR class directly to set the ocr options.

Just as a note :)

**Comment by PfrLisBerndt** [comment]
The same with Region.waitText...

**Comment by PfrLisBerndt** [comment]
> The same with Region.waitText...
> But here I can´t work around in the same manner.

Command back!

This had a different cause: the tessdata was not found. I actually set the tessdata dir to .../[folderName]
But Sikulix obviously then expects the tessdata to be in .../[folderName]/tessdata

**Comment by balmma** [comment]
So you mean that you can also still use the deprecated TextRecognizer stuff from JRuby?

**Comment by PfrLisBerndtHome** [comment]
> So you mean that you can also still use the deprecated TextRecognizer stuff from JRuby?

Yes, when using the ide.

**Comment by balmma** [comment]
Do you get a stacktrace or similar?

**Comment by PfrLisBerndtHome** [comment]
> Do you get a stacktrace or similar when running directly from JRuby?

Something has obviousely changed regarding sikulix exceptions. So the wrapping ruby-gem exception method 'full_message'  does not longer work →  no stack trace in my debug log. And that's why identifying the bug had been already fairly hard.
I will try to give more details on monday.

**Comment by RaiMan** [comment]
@PfrLisBerndt 
I am sorry for any inconveniences.
From the Java perspective, I cannot see any reason for not being backwards compatible.
... but I have to admit, that I did not look into the JRuby scene at all (even not for the last 2-3 years).

It would help me a lot, if you could give me a short script example and the JRuby setup/environment needs, to run a SikuliX script from commandline.

I would like to have some basic test environment again for JRuby.
I have 9.2.9.0 on my macOS 10.15.

**Comment by PfrLisBerndtHome** [comment]
No experience with macOS, but on Windows given installed jruby, properly set java envs., and Path pointing to sikulix.jar, you furthermore have to install sikulix-gem -> console: "gem install sikulix"

A jruby script named main.rb would look like this:

> 	
	include Sikulix

		begin 

			textRecognizer = Sikulix.org.sikuli.script.TextRecognizer.start() #That already does not work.
			textRecognizer.setOEM(0) #Does not work. Had to use OCR.oem(0).

			region = Sikulix.org.sikuli.script.Region.new #Still works.
			region.waitText("Beispiel") # Does not not work.

		rescue Exception => exc

			puts exc.full_message #For stacktrace. Does not work.

		end


-> to run console: jruby [dir/]main.rb

**Comment by balmma** [comment]
@RaiMan 
Where is the source code for the gem? The Gem itself is most probably utterly  outdated. I just wonder that it is somewhat working 😀

**Comment by balmma** [comment]
Found it.

**Comment by RaiMan** [comment]
@PfrLisBerndt @balmma 
Yes, the gem is definitely outdated (as far as I remember it is somewhere at the level 1.1.3 or even before. Hence it should not be used with SikuliX 2.x+
I do not plan, to update the gem.

For running jruby scripts from command line with 2.x+ you need
 - ``sikulixapi-....jar`` on the java classpath (but sikulix....jar does no harm)
 - ``<sikulix-app-data>\Lib`` on JRuby's  library path
 -  have this at the top of your main script:
```
   # coding: utf-8
   require 'sikulix'
   include Sikulix
```

This is what we do in the IDE script runner.

**Comment by RaiMan** [comment]
@balmma 
We need some ``SikulixForJRuby``, that takes care for the prerequisites, if you want to run scripts with a standalone JRuby.
I will create an issue for 2.0.3.
