### ISSUE TITLE
2.0.2 OCR retrieved text from sample image over target image

### ISSUE THREAD

**Issue by xwvArmour** [RaiMan/SikuliX1#304]
Hi, since sikulixapi-2.0.2.jar I noticed the OCR text is retrieving text from the sample image instead of from the target.
sikulixapi-2.0.1.jar works correctly.

The scenario goes like this:
I have a sample image and a target image that look alike to each other, except they have different text.
The sample image has the text "Internet".
The target image text is unknown until displayed.
When I use sikulixapi-2.0.1.jar, with the sample image, I am able to identify the target image and retrieve the expected text.
When I use sikulixapi-2.0.2.jar, with the sample image, although it can identify the target image, but the text retrieved is always the sample image text "Internet".
Also tested with the nightly build up to 2-7-2020, same behavior as sikulixapi-2.0.2.jar.

**Comment by balmma** [comment]
Some sample code would be nice.

**Comment by xwvArmour** [comment]
Attached are the sample image and target image I used to find this problem.
I will supply automated test code shortly.
[targetImage](https://user-images.githubusercontent.com/50221398/74181264-cdcc2400-4bf5-11ea-8c69-f5028275e353.png)
![sampleImage](https://user-images.githubusercontent.com/50221398/74181266-ce64ba80-4bf5-11ea-8e14-816d4471a3fc.png)

**Comment by xwvArmour** [comment]
Hello,
test code is provided in my project
https://github.com/xyteam/xySikulixApi.git

manual test steps:
git clone https://github.com/xyteam/xySikulixApi.git
cd xySikulixApi && npm install
SikulixApiVer=2.0.1 npm run download
SikulixApiVer=2.0.2 npm run download

Expected case:
SikulixApiVer=2.0.1 node scripts/findTargetImage.js --onArea=onScreen --sampleImagePath=`pwd`/test_images/sampleImage.png --maxSimilarityOrText='Seen'

Failed case:
SikulixApiVer=2.0.2 node scripts/findTargetImage.js --onArea=onScreen --sampleImagePath=`pwd`/test_images/sampleImage.png --maxSimilarityOrText='Seen'

automated test code will be provided soon.

**Comment by RaiMan** [comment]
impressing ;-)

... but since I have no experience in the used node environment, I cannot see, where which SikuliX features are used, that might be the cause for your situation.

... and I cannot really understand what you mean by sample image and target image.

It would be helpful if you provide a sample using the relevant SikuliX API calls.

**Comment by balmma** [comment]
@xwvArmour 

Yes, with sample code I also mean the smallest possible test case to reproduce the issue. Preferably Jython packed into a .skl file.

**Comment by xywang68** [comment]
Hi, I have added java test code to the same project mentioned above. Please checkout the latest code, which should include a new directory called "test_java":
getTargetText.java: a small java source code that demonstrates this problem.
getTargetText.class: a compiled class of the same source code.

Prepare to demonstrates this problem:
1. copy both sikulixapi-2.0.2.jar and sikulixapi-2.0.2.jar to this folder.
2. use browser to open the mentioned target image (with text Databases) in the test_image directory;
When there is a match the GUI will flash a red rectangle.

To demonstrate a successful case using v2.0.1:
```
java -cp ./sikulixapi-2.0.1.jar:. getTargetText $(pwd)/../test_images/sampleImage.png Databases
```
where you will see the result
```
sampleImagePath : (current path)/../test_images/sampleImage.png
sampleText : Databases
[log] highlight M[123,182 275x120]On(0) S 9247 for 0.1 secs
find_text : Databases
Sessions Data First Seen (UTC)
489.8M 461B Jan 11, 2018 0:00
Services  Workload@ Last Seen (UTC)
9 23 Sep 3, 2019 23:00
```
which matches the text in browser displayed target image, and in the GUI you will see the red rectangle flashed at the right spot. 

To demonstrate a problem case using v2.0.2:
```
java -cp ./sikulixapi-2.0.2.jar:. getTargetText $(pwd)/../test_images/sampleImage.png Databases
```
which you will not see any result, and there is no flash of red rectangle.


To further demonstrate v2.0.2 always gets text from the sample image, run with this command:
```
java -cp ./sikulixapi-2.0.2.jar:. getTargetText $(pwd)/../test_images/sampleImage.png Sessions
```
You will it reports every match contains the same text. In the GUI you will see red rectangles flashes everywhere which is wrong.

repeat the same command with v2.0.1, you will see the expected result.

You can recompile the java problem with this command (both v2.0.1 and v2.0.2 will work):
```
javac -cp ./sikulixapi-2.0.2.jar getTargetText.java
```

Hope this information is helpful. Please let me know if you need additional info.
BTW, I really appreciate your work. My project is benefiting from yours. I would not mind helping to carry your project forward.

**Comment by xywang68** [comment]
Update:

Looks like there is a way to work around this issue, and this may not be a bug.

I read the sikulix doc carefully, and it indicated that a Match returned by the findAll() call is still based on the sample image, therefore the text() call on the Match directly could be getting the text from the sample image. The fact that v2.0.1 and before returns the text from target image could be wrong in the first place.

by creating a region from a Match return by the findAll() call then call text() I am able to get the text from the target image. 
I have tested 2.0.1, 2.0.2, 2.0.3 they all return the expected text.

I have updated my xySikulixApi project to use 2.0.3. You can close my issue.

**Comment by RaiMan** [comment]
Sorry, but I cannot reproduce this behaviour
- `Match.getText()` returns a text, that was found before using `findText()` features.
-  `Match.text()` tries to read the text (OCR) from the Region defined by the Match

`findAll()` as such does not return a list of matches, but a Finder object, that only has the features `hasNext()` and `next()`, to access the matches found by a previous `finder.find(img)`.

so this should work as expected:
```
finder = Finder(baseImage)
finder.find(targetImage)
if finder.hasNext():
    match = finder.next()
    print "text read:", match.text()
```

**Comment by RaiMan** [comment]
no feedback
