### ISSUE TITLE
MacOS: No left side menu

### ISSUE THREAD

**Issue by francesco1119** [RaiMan/SikuliX1#308]
I'm looking at this tutorial: 

https://www.youtube.com/watch?v=I-UYoezac4Q

but on mu machine there is no left side menu, how can a choose "find" or "click"?

![SikulixIDE-2 0 2 - Untitled 2020-02-11 13-00-43](https://user-images.githubusercontent.com/3397477/74235067-86fe2d00-4cce-11ea-9e15-d6b6798889ae.png)

**Comment by RaiMan** [comment]
not supported with SikuliX version 2.x any more.

Use a version up to 1.1.3 to have this feature.

Now you have to write:
`click(`
... then use the capture button and write the closing `)` to finally get:
`click(...some image...)`

The same goes for all the other features according to the docs.
