### ISSUE TITLE
Can't export project as runnable jar

### ISSUE THREAD

**Issue by DimaKudosh** [RaiMan/SikuliX1#31]
I tried to export my sikuli project as runnable jar, but got this error:
`[error] FileManager: makingScriptJar: sikulixapi.jar missing. run setup first!`
I treid to add sikulixapi.jar to directory with my sikulix.jar, but it didn't help me. 
I'm using sikuli 1.1.4

**Comment by mattrussmill** [comment]
copy the _sikulixapi.jar_ and the _jython-standalone-2.7.1.jar_ files to the following location after launching _sikuli.jar_ at least once so the file structure is generated:

`C:\Users\[your username]\AppData\Roaming\Sikulix\SikulixDownloads`

**Comment by RaiMan** [comment]
@DimaKudosh I have to check that.

**Comment by RaiMan** [comment]
checked: does not work with 1.1.4+ and does not make sense anymore.
Until I have another solution, I will hide this feature

**Comment by mattrussmill** [comment]
I am using 1.1.4 and that is how I got it to work properly
