### ISSUE TITLE
Sikuli Click function is not working with Java version 211 and 241

### ISSUE THREAD

**Issue by ravina2404** [RaiMan/SikuliX1#311]
What I want to achieve:
I want to Click using image of Logging.

 

Case 1:
 When I tried to use Java 8 Version 171  it is working fine for Lenovo ThinkPad laptops below are configuration of laptop:

 

1. Window Edition: Window 10 Enterprise.
2.Processor: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz 1.90 GHz
3.Memory: 8.00 GB (7.88 GB Usable)
4.System Type: 64-Bit Operating system, x64-based processor

 

Case 2:

 

When I tried to upgrade Java 8 Version to 211 and 241 it is not clicking on image instead of that it is clicking on below axis of screen.
CLICK on L(702,311)@S(0)[0,0 1280x720] (539 msec)

 

Laptop Configuartion used is:
1. Window Edition: Window 10 Enterprise.
2.Processor: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz 1.90 GHz
3.Memory: 8.00 GB (7.88 GB Usable)
4.System Type: 64-Bit Operating system, x64-based processor

 

Note: I have tried to use different images still its is clicking on same axis of screen, whereas type function of sikul is working fine.

 

Case 3:
when I tried to use same images to click on Dell laptops it is working fine as expected for all JAVA 8 version of 171,211 and 241.
Below is configuration of Dell laptop:

 

1. Window Edition: Window 10 Enterprise.
2.Processor: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz 2.71 GHz
3.Memory: 8.00 GB (7.88 GB Usable)
4.System Type: 64-Bit Operating system, x64-based processor
5.Latutude 5290

[Sikuli_Issue.docx](https://github.com/RaiMan/SikuliX1/files/4229616/Sikuli_Issue.docx)

**Comment by RaiMan** [comment]
already posted on launchpad and answered. Not a SikuliX bug.
