### ISSUE TITLE
Window size of SikulixIDE not set?

### ISSUE THREAD

**Issue by romangrothausmann** [RaiMan/SikuliX1#326]
[a first revision/fix (a hack to not allow too small IDE window)](https://github.com/RaiMan/SikuliX1/commit/59a94d084cae61b2d62b8c3b60a8bb313082967d)

----------------

At least for SikulixIDE-2.1.0 the size of the IDE window does not seem to be set (as used to be the case) such that the window has no size if started in Xvfb. This use to work before (https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/242792871/artifacts/file/start.png of https://gitlab.com/romangrothausmann/dind-sikuli/pipelines/68738581). I'm not sure if this is a problem of SikulixIDE or Java-11 or both.

**Comment by RaiMan** [comment]
thanks for the pointer. I will check.

BE AWARE: 2.1.0 is currently very unstable due to massive changes under the hood.
It is not recommended for  productive use.

The only reason you might want to use it currently is, if you are interested in  the new recorder feature of the IDE.

For running stuff in headless environments (probably docker based), you should use the stable versions 2.0.x (currently 2.0.3, upcoming 2.0.4)

**Comment by RaiMan** [comment]
BTW: what you are doing on GitLab in this `dind-sikuli`: what is it for? what is the magic behind?

**Comment by RaiMan** [comment]
The only difference against versions before 2.1.0 is, that the IDE initialisation now is run from the EventQueue with invokeLater() (to avoid possible hangUp's during IDE start).

Location and size are still tried to be set at the beginning of the initialisation.

But I noticed on Mac, that the defaults from the preferences are ignored, when I force the preferences to reset to the defaults: the window will have location/size as when I closed the IDE the last time, which is different from the defaults.

So I have to dig a bit deeper, to find out, what happens there.

> You said: such that the window has no size if started in Xvfb

what exactly do you notice? Any error messages?

**Comment by romangrothausmann** [comment]
Many thanks @RaiMan for your quick replies. 

> BE AWARE: 2.1.0 is currently very unstable due to massive changes under the hood.
It is not recommended for productive use.

I see, many thanks for that pointer. To be version number independent, I used the JARs from 
https://raiman.github.io/SikuliX1/sikulix.jar https://raiman.github.io/SikuliX1/sikulixapi.jar but if those do not point to the last stable version but the very newest, those should not be used for production, so with
https://gitlab.com/romangrothausmann/dind-sikuli/-/commit/c86b8118161af8277f559d8ab23ad2dff1858791
things are working again (https://gitlab.com/romangrothausmann/dind-sikuli/pipelines/124331002). Still it would be nice to have a version independent download URL that points to the latest stable version.

**Comment by romangrothausmann** [comment]
> BTW: what you are doing on GitLab in this `dind-sikuli`: what is it for? what is the magic behind?

It is basically a project that contains a [Dockerfile](https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/Dockerfile) to create a docker image with [GL-CI](https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/.gitlab-ci.yml). The docker image (DI) then contains sikulix and all its deps in an isolated environment. The DI can then be used to provide the environment for GL-CI automated GUI interaction test (smoke tests). Starting the SikulixIDE is used as an example GUI app in the tests (https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/.gitlab-ci.yml#L130-141). Since these GUI tests run on a GL-CI runner that does not have a monitor, Xvfb needs to be used instead. Interacting with a GUI that is not visible demands some automation for the interaction for which sikulix is my favorite choice.

**Comment by romangrothausmann** [comment]
> what exactly do you notice? Any error messages?

The window is only about 5x10 (or less, did not measure it) pixel in size, so already a challenge for a human to spot;-) and in any case not the size it used to be before in Xvfb (https://gitlab.com/romangrothausmann/dind-sikuli/-/jobs/463142990/artifacts/file/start.png) which causes the current test to fail (which just compares the screen shot of Xvfb with a reference). So I could change the [reference image](https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/comp/start.png) but letting the test succeed on comparing only 5x10 or so pixel makes hardly any sense.

**Comment by romangrothausmann** [comment]
> Many thanks @RaiMan for your quick replies.
> 
> > BE AWARE: 2.1.0 is currently very unstable due to massive changes under the hood.
> > It is not recommended for productive use.
> 
> I see, many thanks for that pointer. To be version number independent, I used the JARs from
> https://raiman.github.io/SikuliX1/sikulix.jar https://raiman.github.io/SikuliX1/sikulixapi.jar but if those do not point to the last stable version but the very newest, those should not be used for production, so with
> https://gitlab.com/romangrothausmann/dind-sikuli/-/commit/c86b8118161af8277f559d8ab23ad2dff1858791
> things are working again (https://gitlab.com/romangrothausmann/dind-sikuli/pipelines/124331002). Still it would be nice to have a version independent download URL that points to the latest stable version.

Which brings me now to the question: Is there still an URL to download `sikulix-1.1.3.jar` and `sikulixapi-1.1.3.jar`?

**Comment by RaiMan** [comment]
> it would be nice to have a version independent download URL that points to the latest stable version.

accepted. I will implement a solution and tell you here about it

> Is there still an URL to download sikulix-1.1.3.jar and sikulixapi-1.1.3.jar?

There have never been such download options, because up to 1.1.3, you had to run  a setup, to create the respective jars for your environment.

**Comment by romangrothausmann** [comment]
> There have never been such download options, because up to 1.1.3, you had to run a setup, to create the respective jars for your environment.

I see, just checked and the version reported for the last successful created DIs contains Sikulix-1.1.4 (snapshot of build # 316, 190630), which, I guess, is not available for download any more since it was a snapshot.

**Comment by RaiMan** [comment]
1.1.4 was never turned into final (no longer having a setup indeed started with 1.1.4).
It was just renamed to 2.0.0 and the released.

**Comment by RaiMan** [comment]
A fix for the wrong window size in cases of "first-use-of-SikuliX" on a system (which is the standard with docker images as far as I understand) will already available with the 2.0.4.

**Comment by RaiMan** [comment]
This will finally be revised in 2.1.0, when the Preferences store handling is revised

**Comment by RaiMan** [comment]
@romangrothausmann 

> it would be nice to have a version independent download URL that points to the latest stable version.

I am sorry, but I will not add a solution (as mentioned a few days ago).

All downloadable artefacts will always have a version reference in the file name:
- no additional effort for me
- in support cases it is always clear, what we are talking about
- a user can always see, where in the upgrade chain he is

It should be rather easy to solve this yourself.

**Comment by romangrothausmann** [comment]
No problem, I can understand your points.
