### ISSUE TITLE
JRuby: Working with remote desktop

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#335]
Hello!

Since I have to work with rdp, I notice a strange behavior. I suppose Sikulix is not to blame, but maybe you can give me a hint to the root cause.

My pc at work is working with three screens, on the center the automation is going on. My ruby-fw uses the sikulix-api (2.0.1) and a new Region is created out of coordinate-values taken from a config-file. 
My pc desktop is now displayed via rdp on my home laptop. Of course screen is now scaled down, and I knew that I have to adjust the coordinate-values.
For some purposes I have use a java program which uses the same sikulix-api and the same config file as well. 
BUT: Highlighting shows that a total different region is created.
The coordinates in the file are: 1380, 35, 490, 840
Output with ruby: [log] highlight R[1380,35 490x840]@S(0) for 5.0 secs
Output with java: [log] highlight R[1380,35 156x829]@S(0) for 5.0 secs -> this is out of my lap-top screen.

I have no idea from where the api is getting the 156,829- dimension.

I intended to attach some screenshots, but I notice that only the highlighting by ruby can be captured; the highlighting by the java bound in api cannot be captured.

Any ideas?

**Comment by RaiMan** [comment]
Rather difficult, to judge from your sayings only.

But a guess: Regions are clipped to fit into the Screen (monitor) where they have their top left corner.
So your current screen size in this case is (1380 + 156, 35 + 829).
No idea, wether this is possible in your case.

**Comment by PfrLisBerndtHome** [comment]
Thanks so far.

A guess by me: The only apparent difference is, java uses the api in its build path; ruby calls it by the windows classpath. Can this cause the different behavior?

**Comment by RaiMan** [comment]
Where the Region class is loaded from, does not make any difference.

Did you check my idea?

**Comment by PfrLisBerndt** [comment]
I solved the problem regarding to the dimension.- There is an offset about 0.8. Now the region is highlighted correctly. And as I mentioned, I´m not able the capture the highlighting. But that´s not the major problem. - Obviously sikulix does not recognize any pictures in there. In my company it works, but not remotely.
My ruby-implementation works fine, remotely and in my company.

**Comment by RaiMan** [comment]
What do you mean by `an offset about 0.8`?

What do you mean with: `not able the capture the highlighting`. 
Capture what and how?

I do not understand: `sikulix does not recognize any pictures in there`?
In what?

`My ruby-implementation`:  any details?

`Remotely`: what exactly is that? What is done where?

**Comment by PfrLisBerndtHome** [comment]
Head → desk... that I didn't get it earlier...!  - Maybe it's a candidate for your lessons learned part in the docs...

The factor 0.8 gave me thoughts: That could mean, that Sikulix of my remote pc looked for pictures that were 1.25 times bigger than the originals. No wonder that searching failed. I looked up the settings of my home laptop, and indeed, display scale was set to 125%!
Nevertheless I wonder why the ruby bound in api behaves in a different way than the Java bound in.
