### ISSUE TITLE
Unexpected folder SikulixAppDataNotAvailable created for 2.0.4

### ISSUE THREAD

**Issue by bswhb** [RaiMan/SikuliX1#337]
Hi there,

We're integrating SikuliX 2.0.4 into a jar library, and when I ran this jar we will find a folder named `SikulixAppDataNotAvailable` created in the same folder with the jar file. Here's the screenshot of this folder (The OS is `Win 10 v18363`, and JDK is `openjdk version "1.8.0_242"`):

![image](https://user-images.githubusercontent.com/1092670/77607030-18aabc80-6f54-11ea-86a1-10cacfba4a9d.png)

As I understand this folder should not be created in the latest 2.0.4 version. Kindly please help advise how to avoid it, thanks a lot!

p.s below I'm attaching the POM snippet  FYI.
```
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			<version>2.0.4</version>
		</dependency>
```

**Comment by RaiMan** [comment]
This happens on Windows at startup:
```
      runTime.fSikulixAppPath = new File("SikulixAppDataNotAvailable");
      ...
      String tmpdir = System.getenv("APPDATA");
      if (tmpdir != null && !tmpdir.isEmpty()) {
        runTime.fAppPath = new File(tmpdir);
        runTime.fSikulixAppPath = new File(runTime.fAppPath, "Sikulix");
      }
```

This means in your case the environment variable `APPDATA` is either not available or empty.

Usually it is the path of some folder in the user's application data store.

**Comment by bswhb** [comment]
Hi @RaiMan 

Thanks for your explanation, I will check the env variables when I invoked this jar application. By the way, I'm going to use this app in an intranet where internet access is not permitted, for both x64 and x86 hosts. How to bundle these `jawt.dll` files into the app, instead of downloading from internet at the first time usage? Thanks again in advance.

**Comment by RaiMan** [comment]
Sorry no, the newer SikuliX versions only support 64-Bit.

**Comment by bswhb** [comment]
Thanks for the information, right now perhaps I have to switch back to the older version. Do you have any plan to support x86?

**Comment by RaiMan** [comment]
Currently no plans .
But I will check the impacts and possibilities, to support x86, to at least give interested people some advice, how to make the environment ready for SikuliX.
I made a new issue: #339 and close this one.
