### ISSUE TITLE
Region existsText return match with wrong XY ( missing relocate )

### ISSUE THREAD

**Issue by seltix5** [RaiMan/SikuliX1#338]
match returned from Region existsText are not realocated ( like on the waitText ), because of this the XY coordinates are wrong.

https://github.com/RaiMan/SikuliX1/blob/3fe39064ae59c58bd684b1176a859b4dcf1d2c22/API/src/main/java/org/sikuli/script/Region.java#L2053

**Comment by RaiMan** [comment]
Thanks for finding. [Will be fixed in 2.0.5](https://github.com/RaiMan/SikuliX1/commit/cda681c5960a000f77069e89befb6d0ef859bdfc)
