### ISSUE TITLE
ADBScreen class not available currently

### ISSUE THREAD

**Issue by aino-gautam** [RaiMan/SikuliX1#34]
This might be more of a question. Somewhere in the site I saw reference to ADBScreen to work with android device / emulator but I couldn't import it from the jar. 

Am I missing something ?

**Comment by RaiMan** [comment]
To use it, you have to use 1.1.3 and Java 8.
In 1.1.4 it is switched off for now: [does not work with Java 11 (bug)](https://bugs.launchpad.net/sikuli/+bug/1788812) 

You might watch the bug to know, when it is fixed.

**Comment by aino-gautam** [comment]
@RaiMan I downloaded 1.1.3 setup for mac and ran it. It installed everything beautifully except 

- when I click on tools > menuToolAndroid, it gives me a popup, package adb not available. Must be installed for android support. 

Where can I find this android support package ?
<img width="1440" alt="screen shot 2018-09-26 at 20 28 43" src="https://user-images.githubusercontent.com/519118/46088843-eb4c4980-c1ca-11e8-8c17-bc404ffbb862.png">

**Comment by RaiMan** [comment]
The android support bundled with 1.1.3 only runs with Java 8 (the error is a bit misleading)

With version 1.1.4 it is currently indeed not available at all.

You might try with some VNC solution.

**Comment by RaiMan** [comment]
should stay open

**Comment by RaiMan** [comment]
fixed
https://bugs.launchpad.net/sikuli/+bug/1788812
