### ISSUE TITLE
Command sidebar is not displayed in the IDE

### ISSUE THREAD

**Issue by ugioni** [RaiMan/SikuliX1#341]
When using version 2.0.4 I noticed that the command sidebar is no longer being displayed as it was in version 1.1.3.

Was this feature removed in this release?

![sikuli_113](https://user-images.githubusercontent.com/50387966/78211132-8ee27e00-7482-11ea-809f-3dcce23a02c9.png)

![sikuli_204](https://user-images.githubusercontent.com/50387966/78211138-9013ab00-7482-11ea-9621-82daf297511a.png)

**Comment by RaiMan** [comment]
Yes, the feature is no longer available and will not come back this way.
