### ISSUE TITLE
NameError: name 'App' is not defined

### ISSUE THREAD

**Issue by AlexnderDoroshenko** [RaiMan/SikuliX1#342]
Am I doing something wrong ?
It works on 1.1.3 version, but not on 2.0.4 .

Exception in thread "Thread-29" Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "\\repository\Documentation\Testing\Scripts\sikuli\sikuli.sikuli\sikuli.py", line 61, in <module>
    myApp = App(r"bin\poi.bat")
NameError: name 'App' is not defined
2.0.4-2020-03-14_08:01/Windows10.0/Java8(64)1.8.0_211-b12

This is the second issue, if I close bug report dialog window an error occurs.
[error] IDE: Problem when trying to invoke menu action openBugReport
Error: null
![remmina_upi_192 168 1 48_202042-9429,854927](https://user-images.githubusercontent.com/23527168/78230927-b6653500-74da-11ea-8d95-6d5699b6a822.png)

**Comment by AlexnderDoroshenko** [comment]
def launch(myApp): # function that start an app
    if not myApp.isRunning(0):
        print("not running")
        myApp.open()
    else:
        print("already running")
    start = time.time()

def launchWindow():
    myAppName = App("POI")
    while not myAppName.window(0):
        myApp.open();
        wait(2)
        break

def login():
    reg = Region(449,0,1024,765)
    myApp.focus()
    wait("1563431103842.png", 60)
    doubleClick("1563441792267.png") 
    sleep(1)
    if exists("1585811672593.png"):
        checkLang()
    doubleClick("1563441792267.png")
    type("1")
    type(Key.ENTER)
    type("1")
    type(Key.ENTER)
    sleep(1)


def checkLang(): #function that check system language
    Region(1772,1054,34,22)
    type(key.ALT, KEY_SHIFT) #example of the the key down key up funtions.
    if not exists("1585731167925.png"):           
        checkLang()
    else:
        type(KEY_ALT)
        print("Language is OK!")
        
def appClose(): # function which close POI
    try:
        myAppName.close()
    except:
        print("can`t close, trying another way !")
        type(Key.F1)
        sleep(2)
        type("e")
        if exists("1585809951899.png"):    
            print("can`t close, trying another way !")
            click("1585746333491.png")
            sleep(1)
            click(find("1585809583996.png"))            
        elif exists("1585809951899.png"):
            click(find("1585809583996.png"))
    print("close script complete")
                    


myAppName = "POI"
myApp = App(r"C:\Progra~2\UPITec3\UPITec\JStore\bin\poi.bat")
launchWindow()
login()

appClose()

**Comment by RaiMan** [comment]
--- \repository\Documentation\Testing\Scripts\sikuli\sikuli.sikuli\sikuli.py
What is this?
How does it come into existence in your scriptrun?

**Comment by AlexnderDoroshenko** [comment]
This is a script from a local network repository, it was opened in sikuli UI and was run from it.

**Comment by RaiMan** [comment]
Tried with 2.0.5?
