### ISSUE TITLE
SikuliX 2.0.4 doesn’t work with Spring Boot 2.2.6

### ISSUE THREAD

**Issue by danielmenezesbr** [RaiMan/SikuliX1#344]
I got a error when using SikuliX 2.0.4 with Spring Boot 2.2.6:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.sikuli.natives.SXUser32.<clinit>(SXUser32.java:13)

The following method did not exist:

    'com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class, java.util.Map)'

The method's class, com.sun.jna.Native, is available from the following locations:

    jar:file:/C:/Users/danie/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar!/com/sun/jna/Native.class

It was loaded from the following location:

    file:/C:/Users/danie/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.sun.jna.Native


Process finished with exit code 1
```

Works  fine when:
  (a)	Replace SikuliX 2.0.4 by [SikuliX 1.1.2](https://github.com/danielmenezesbr/sikuli_bug/blob/master/sikuli_bug_with_springboot/pom.xml#L39) or;
  (b)	Remove Spring Boot.

To reproduce this behavior I create 2 projects:

[Sikuli 2.0.4 with Spring Boot 2.2.6 (doesn’t work)](https://github.com/danielmenezesbr/sikuli_bug/tree/master/sikuli_bug_without_springboot)

[Sikuli 2.0.4 without Spring Boot (work fine)](https://github.com/danielmenezesbr/sikuli_bug/tree/master/sikuli_bug_with_springboot)

OS: Windows 10
JDK: 11 and 1.8

java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

C:\desv\jdk-11.0.6+10\bin>java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

**Comment by RaiMan** [comment]
You have a conflicting jna-version on your classpath.

this is what SikuliX API needs:
``` 
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna-platform</artifactId>
      <version>5.4.0</version>
    </dependency>
```

**Comment by danielmenezesbr** [comment]
Thank's @RaiMan!

I added `net.java.dev.jna:jna:5.4.0` and `net.java.dev.jna:jna-platform:jar:5.4.0` and now [my project](https://github.com/danielmenezesbr/sikuli_bug/commit/b342038e98b5388e37b7c26d990d4177f909fa4e) works fine with Spring Boot 2.2.6 + SikuliX 2.0.4.
