### ISSUE TITLE
[2.0.4] match getTarget/getCenter chooses an incorrect screen

### ISSUE THREAD

**Issue by marattep** [RaiMan/SikuliX1#346]
Am getting a match-target on screen(0) when the match itself is on screen(1) [non-default]
I'm using 2,0.4 stable-release IDE with the below code.
Thanks!

```
print(r)
r = selectRegion()
if r.exists("1588191877930.png"):
   m = r.getLastMatch()    
   print(m, m.getScore(), m.getTarget(),m.getScreen(),m.getTargetOffset(),m.getCenter())
   r.click(m)

```

[debug] Jython: use as default region: R[0,0 1920x1200]@S(0)
[debug] Image: BufferedImage: (1920, 1200)
[debug] RunTime:loadlib: trying opencv_java342
[debug] OCR: start: Tess4J 4.4.1 using Tesseract 4.1.0
[debug] Finder2: makeMat: INT_RGB (813x386)
R[1637,180 813x386]@S(1)
[debug] Image: reused: 1588191877930.png 
[debug] Region: exists: waiting 3.0 secs for 1588191877930.png to appear in R[1637,180 813x386]@S(1)
[debug] Finder2: makeMat: INT_RGB (813x386)
[debug] Finder2: makeMat: 3BYTE_BGR (83x28)
[debug] Finder2: doFindImage: start (stdDev: 110.5529 mean: 512.962565)
[debug] Finder2: doFindImage: in original: %94.8807 (?70) 30 msec 
[debug] Finder2: doFindImage: end 30 msec
[debug] Region: exists: 1588191877930.png has appeared (M[1678,504 83x28]@S(1) S:0.95 C:1719,518 [68 msec])
(M[1678,504 83x28]@S(1) S:0.95 C:1719,518 [68 msec], 0.9488071799278259, L[1719,518]@S(0), R[1536,93 1536x864]@S(1), L[0,0]@S(0), L[1719,518]@S(0))
[debug] CLICK on L[1719,518]@S(0) (532 msec)

**Comment by RaiMan** [comment]
cannot be reproduced (Win10, Java 11, 2 monitors)
