### ISSUE TITLE
[1.1.4] Application won't launch if parameters are supplied using setUsing(parameterString)

### ISSUE THREAD

**Issue by FlamingGear** [RaiMan/SikuliX1#35]
When Launching my target application without parameters, it will launch fine. However, when supplying the parameters needed for my test cases, I find that the application does not launch. It appears that this is because the parameters are being split wrongly, despite the fact that the App instance has them correct. 

The App instance in question has the following:
`C:\Program Files\Unity\Editor\Unity.exe` as the executable
`-createProject C:\TestUnityProject\` as the options

When launched *with* the above options I am greeted with the following dialogue box:

![image](https://user-images.githubusercontent.com/3352118/46081858-7c083280-c195-11e8-9bd2-25bd3e37d60d.png)

I believe this to be a recent change, as my testbed uses the latest version available in Maven, and this was not true last time I ran this project before taking holiday (2 weeks ago)

**Comment by RaiMan** [comment]
Yes, back from holidays, the world might have changed ;-)

... and it has changed: I fixed some oddities in the class App and with this I revised the parameter handling: [look here for the options](https://sikulix-2014.readthedocs.io/en/latest/appclass.html#App.App)

**Comment by FlamingGear** [comment]
As far as I can tell, I'm using the new method of creating an `App` object and setting its parameters:
![direct code](https://user-images.githubusercontent.com/3352118/46219990-c1b52e80-c340-11e8-950a-d37b893c1f55.png)

I should note that running this full command from the command line works fine
(`"C:\Program Files\Unity\Editor\Unity.exe" -createProject C:\TestUnityProject\`)

The issue is that the first part of the parameter would appear (from the above dialogue box) to be being included in the path to the .exe, where it does not belong.

**Comment by RaiMan** [comment]
I guess I forgot to check setUsing().

So could you try:
parameters = "some stringy stuff"
appName = r"c:\Program Files\.......exe"
App unityApp = new App(appName + " -- " + parameters)

**Comment by RaiMan** [comment]
I checked with the latest 1.1.4 on Windows 10 with Java 11 with Firefox and setUsing(), which worked as expected.

**Comment by FlamingGear** [comment]
Utilising your suggestion above I get the following response, which appears to be similar in nature to the original issue; too many things being left in the path.

![launching unity via sikuli](https://user-images.githubusercontent.com/3352118/46289145-1692b800-c580-11e8-9fb8-4ab04bb44802.png)

Note: Currently I'm using Java 8 rather than 11 as the version available to me on our CI systems.

**Comment by RaiMan** [comment]
I revised the internal usage of the command ``start`` a little bit (seemed to make problems with blanks in the parameter string).

My tests with both parameter setting options worked.
So please try with latest build #96.

**Comment by FlamingGear** [comment]
Tested this with the latest build from Maven, the application now successfully launches but the parameters do not appear to be correctly passed to it. Using the same string being fed into the App (without the ' -- ' in the middle) launches the app into the expected state however.

As a note, I am launching the application using `appInstance.open(10);` rather than directly calling `start` at all.

**Comment by FlamingGear** [comment]
Tested this with the latest build from Maven, the application now successfully launches but the parameters do not appear to be correctly passed to it. Using the same string being fed into the App (without the ' -- ' in the middle) launches the app into the expected state however.

As a note, I am launching the application using `appInstance.open(10);` rather than directly calling `start` at all.

**Comment by FlamingGear** [comment]
```
String parameters = "-createProject " + RunFeaturesTest.testProjectPath;
String appName = "\"C:/Program Files/Unity/Editor/Unity.exe\"";

App unityApp = new App(appName);
unityApp.setUsing(parameters);
unityApp.open(10);
```

**Comment by RaiMan** [comment]
I think, I finally fixed the App behavior now.
I installed Unity on my Win10 and hence I am sure now, that it works ;-)
(brought me Visual Studio as a side-effect, into which I always wanted to have a look anyways) 

These are my test cases:

```
# parameter value without any blanks
project = "c:/TestUnity/Project"
parameters = "-createProject " + project

# parameter value containing blanks
# must have surrounding apostrophes (case 4)
project1 = "c:/TestUnity/my projects/Project"
parameters1 = "-createProject \"" + project1 + "\""

# app path contains blanks
# can be used as such in cases 1 and 2
appName = "C:/Program Files/Unity/Editor/Unity.exe"

# app path containg blanks with surrounding apostrophes
# must be used in case 3
appName1 = "\"" + appName + "\""

skip = True

if skip:
# Case 1: app path contains blanks - appName does not need apostrophes
    unityApp = App(appName)
    unityApp.setUsing(parameters)
    print "Case 1:", unityApp

if skip:
# Case 2: app path contains blanks - appName does not need apostrophes
    unityApp = App(appName + " -- " + parameters)
    print "Case 2:", unityApp

if skip:
# Case 3: app path contains blanks - appName needs apostrophes
    unityApp = App(appName1 + " " + parameters)
    print "Case 3:", unityApp

if skip:
# Case 4: parameter value containing blanks must be in apostrophes
    unityApp = App(appName + " -- " + parameters1)
    print "Case 4:", unityApp

if not skip:
    unityApp.open(10); exit()
```
It is ok, if you smile on the odd case selection ;-)

**Comment by RaiMan** [comment]
should work now

**Comment by c0da** [comment]
I'm having the same problem with version 2.0.5. I'm trying to open firefox in a private window, but it's not using the "--private-window" parameter. This is my code:
```
program = "firefox"
parameters ="--private-window"

browser = App(program)
browser.setUsing(parameters)

print(browser)
browser.open(10); exit()
```

Firefox is opening in a normal window, and my print result says: `[-1:firefox ()] firefox --private-window`. It also looks like the process is running as follows: `sh -c "firefox" &`

What am I doing wrong? thank you in advance!
