### ISSUE TITLE
macOS 10.15 - Java 14: Tess4J: JNA load library libtesseract.dylib fails

### ISSUE THREAD

**Issue by RaiMan** [RaiMan/SikuliX1#350]
`com.sun.jna.NativeLibrary.loadLibrary("tesseract", ...)`

gives:
`java.lang.UnsatisfiedLinkError: dlopen(libtesseract.dylib, 9): image not found`

works up to Java 13

**Comment by dtopuzov** [comment]
I hit the same error with Java11 too.

The first answer here helped me solve the problem:
https://stackoverflow.com/questions/21394537/tess4j-unsatisfied-link-error-on-mac-os-x

**Comment by RaiMan** [comment]
It is a Tess4J problem using the JNA java library to load the native tesseract library.

In 2.0.5 this will be fixed by setting/adding `/usr/local/lib` to the system property `jna.library.path`.
Hence `libtesseract.dylib/libtesseract.so` must be in that folder on Mac/Linux.

**Comment by ndinev** [comment]
When we can expect 2.0.5 to be available for download since this problem for MAC is annoying

**Comment by RaiMan** [comment]
Sorry for the delay. Other very private priorities currently.

You have to wait until later in February.

**Comment by plaurent** [comment]
On OS X, I'm running 2.0.5 and have libtesseract installed via brew and symlinked in /usr/local/lib, but am still getting the following error:

```
[error] Native library (darwin/libtesseract.dylib) not found in resource path (/Users/patryk/Desktop/Core/SikuliX/sikulixide-2.0.5.jar ( ikulixide-2.0.5.jar) )
```

Any suggestions?

**Comment by RaiMan** [comment]
I have macOS 12.4 (on Intel) with Tesseract 4.1.1 (installed using homebrew).
2.0.5 works as expected with Java 17.
