### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by RubyPiec** [RaiMan/SikuliX1#353]
I've already downloaded Jython, made an extensions.txt with the text

`# add absolute paths one per line, that point to other jars,`
`# that need to be available on Java's classpath at runtime`
`# They will be added automatically at startup in the given sequence`

`# empty lines and lines beginning with # or // are ignored`
`# delete the leading # to activate a prepared keyword line`

`# pointer to a Jython install outside SikuliX`
`# jython = c:/jython2.7.1/jython.jar`

`... more` in it, but it still does nothing

**Comment by RaiMan** [comment]
still open?

**Comment by RubyPiec** [comment]
Yea, still don't know.
