### ISSUE TITLE
Startup time when running a skl file from command line

### ISSUE THREAD

**Issue by pwab** [RaiMan/SikuliX1#354]
I have a simple (and working) script packaged as `test.skl`. Now I wanted to start it without the IDE. I used the `-r` parameter like so (with the test.skl right next to the sikulix.jar):

`java -jar sikulix.jar -q -r ./test.skl`

It works 👍. My only problem is the startup time. After pressing Enter the cursor in the CMD is blinking a few times and it seems something is loading in the background. The script then starts after about 5 seconds or so.

Is there some way the boot time can be reduced or am I doing something wrong here?

**Some system info:**
```
- SikuliX 2.0.4
- Windows 10 1909 x64
- openjdk version "12.0.2-ojdkbuild" 2019-07-16
- OpenJDK Runtime Environment 19.3 (build 12.0.2-ojdkbuild+9)
- OpenJDK 64-Bit Server VM 19.3 (build 12.0.2-ojdkbuild+9, mixed mode, sharing)
```

**Comment by RaiMan** [comment]
You have to live with that delay (startup time for Jython) with the first script.
Subsequent scripts in the same session will startup with no delay.

Why do you need a "no-delay" start-up?

**Comment by pwab** [comment]
Hey @RaiMan thanks for the quick response and also thank you for maintaining this awesome tool. Works great :)

> Why do you need a "no-delay" start-up?

I'm using SikuliX to automate a complicated login process (with a lot of buttons that have to be clicked). I only want to shorten the time I need to login because I have to do this several times a day. With using the script the login time decreased a lot and only the startup time is now the bottleneck.

> Subsequent scripts in the same session will startup with no delay.

Well I created a cmd-file with only that one line to automate the process. So I'm not using any subsequent scripts here. Not sure if this is a super rare use-case but still useful for me.

**Comment by RaiMan** [comment]
Ok, understood.

Though it is always a question, what you get if you invest and I do not know where you might have your "break even" ;-), this is a possible solution in your case:
- create another script
- define a hotkey 
- into the hotkey handler put your login workflow code
- at the end of the script put a loop like this:
```
while True:
    wait(1)
```

If you now start the script with your cmd-file, the script will sit in the background and wait for your hotkey press. The login workflow now starts immediately, after you have pressed the hotkey, the handler will do its job and the main script again waits in the background.

Statistically (min = 0, max = 1) you now have a delay of 0.5 seconds ;-)

All the best and thanks for the kind feedback.
