### ISSUE TITLE
TextRecognizer could not be initialized

### ISSUE THREAD

**Issue by sushanth-raj** [RaiMan/SikuliX1#357]
I am able to get text from the region when running the sikuli project from eclipse. But when I extract the source as runnable jar and its working in my computer for the same jar I am getting the error as "TextRecognizer could not be initialized" in different computer.

**Comment by RaiMan** [comment]
Make sure the prerequisites are in place on the different computer.

Run from command line with -Dsikuli.Debug=3 as a java option.
