### ISSUE TITLE
Why tag 2.0.4 require java 9 and not in branch release_2.0.x ?

### ISSUE THREAD

**Issue by qxo** [RaiMan/SikuliX1#360]
tag 2.0.4:
108f9acc 20200313_14:06 RaiMan tests: get images from jar on classpath [ci skip]
37eab0d6 20200312_15:52 RaiMan added: images [ci skip]
3dff8d97 20200312_12:51 RaiMan Merge remote-tracking branch 'origin/master'
e60cdab0 20200312_12:50 RaiMan added: images [ci skip]

**Comment by RaiMan** [comment]
I can see, that the tag pom file says source/target Java 9. Not sure how that happened.

The 2.0.4 released downloadable versions (even the artifact on Maven) are all built with source/target Java 8.

Anyways: 2.0.x versions are planned to be runnable on Java 8+

If you need to work with 2.0.4 tag, you may tweak it to your needs. 

Pull requests are only accepted against branches release_2.0.x or master (2.1.0).
