### ISSUE TITLE
Command line progress status

### ISSUE THREAD

**Issue by sabatale** [RaiMan/SikuliX1#365]
Is there any way to monitor the execution status in the command line?

After starting the -r command, there seems to be no information whether the execution actually started, finished or else, in the command prompt. Basically something similar to [https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner](https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner).

**Comment by RaiMan** [comment]
You can use the Python `print` statement or SikuliX's debug features to get printouts to the command line window.
