### ISSUE TITLE
App Open Not Functional for Linux

### ISSUE THREAD

**Issue by jdm12989** [RaiMan/SikuliX1#366]
When using App.open or openApp on Linux Mint 19.3 the application does not open.

Looking into LinuxUtil.java it appears the function runs the command:
``` shell
sh -c (<application>) &\necho -n $!
```

On my particular distro the parenthesis cause the command to fail. Also the echo is redundant because the PID is printed when using the "&". The proper formatting for me is:
``` shell
sh -c "<application>" &
```

Which outputs the PID in this format:
``` shell
[1] 30918
```

**Comment by RaiMan** [comment]
fixed with commit: https://github.com/RaiMan/SikuliX1/commit/5baab7ecf79c34456132e3157c0734647a25ea6a
