### ISSUE TITLE
usr_paths Issue noticed with the AdoptOpenJDK9 

### ISSUE THREAD

**Issue by AdminSujeet01** [RaiMan/SikuliX1#367]
[error] RunTime:checkJavaUsrPath: get
java.lang.NoSuchFieldException: usr_paths
[error] RunTime:Problems setting up on Windows - see errors - might not work and crash later

**Comment by RaiMan** [comment]
SikuliX version?

**Comment by AdminSujeet01** [comment]
its sikuli 2.0.2

**Comment by vidhijain11** [comment]
I also observed this issue on Sikuli2.0.2
Steps to reproduce - 
1) Launchj Sikuli IDE
2) Write code to click/find an image.
3) Run script.
After launching Sikuli IDE, this exception is thrown only once for first run. 
![usr_pathException](https://user-images.githubusercontent.com/24410314/88280898-505c2200-cd04-11ea-9f31-dc54914aecc0.jpg)

**Comment by RaiMan** [comment]
Possible to test with SikuliX 2.0.4?

**Comment by vidhijain11** [comment]
Tested on SikuliX 2.0.4 but facing same issue

**Comment by RaiMan** [comment]
ok, thanks.

Since it is not clear, whether the feature behind is still needed, simply ignore it for now.

I accept it as a low-prio-bug. Might be, that it is solved with 2.0.5.

**Comment by vidhijain11** [comment]
Thanks for confirmation

**Comment by RaiMan** [comment]
fixed with commit: https://github.com/RaiMan/SikuliX1/commit/d78f1fccc39f02b28a0b8411738a15b5f735059d

**Comment by AdminSujeet01** [comment]
Thanks Raiman,
Looking forward to it.
