### ISSUE TITLE
Textrecognition inconsistent result

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#368]
I´m facing the issue that the textrecognizer has problems to localize a text and return a result, though it is definitly able to recognize the in the specified region.

The specific patterns are attached.

I found out, that the success of localisation is depending on the search region (x1,y1,x2,y2) I define:  Defining

1440,114,1900,735 (whole screen of device under test) --> localisation success
1436,341,1877,388 ---> fail
1436,341,1878,388 ---> success
1437,341,1900,388 ---> success
1437,341,1878,388 ---> success
1437,341,1877,388 ---> fail
1438,341,1878,388 ---> success
1440,347,1594,370 (region as narrow as possible) --> FAIL

Searching for pattern "LoeschKande" gives on the other hand: Always success.

Snippet of my code: 
```
def recognizeText(textToRecognize)
	begin
		result          = region.waitText(textToRecognize).highlight(@HIGHLIGHT_DURATION, "green")
		@@logger.resultSuccess("Text: '" + textToRecognize + "' at (" + result.getCenter.getX.to_s + ', ' + result.getCenter.getY.to_s + ').')
	rescue => exc1 
		textRecognized1 = region.text
		@@logger.log(textRecognized1)			
		begin
			switchOcrMode	
			result = region.waitText(textToRecognize).highlight(@HIGHLIGHT_DURATION, "green")
			@@logger.resultSuccess("Text: '" + texttoRecognize + "' at (" + result.getCenter.getX.to_s + ', ' + result.getCenter.getY.to_s + ').')
		rescue => exc2
			textRecognized2 = region.text 

			if (!(result.nil?))
			     @@logger.resultError(textToRecognize + " instead: " + result)
			else
			     @@logger.log(textRecognized2) 
			end
								
			if (textRecognized1.include?(textToRecognize) || textRecognized2.include?(textToRecognize)) 
			    @@logger.resultSuccess("Text: '" + textToRecognize + "' (Localisation failed.)")
			    @@logger.debug("Text: '" + textToRecognize + "' is there, but could not be localized by ocr.")  <------ HERE I COME OUT.
			    return
			else
			    raise NotFoundException.new(textToRecognize, true)
			end
		end
	end
end

```
Sikulix-api 2.0.1 with ruby using deu.traineddata (15.076KB)

Update: Using 2.0.4 is always successful. But I already noticed several weeks ago, that 2.0.4 does not "like" some other words, therefore I was still using 2.0.1.

![LoeschKunde](https://user-images.githubusercontent.com/43057926/87769084-61e18d80-c81d-11ea-9ce2-d495b68763d0.PNG)

![LoeschKande](https://user-images.githubusercontent.com/43057926/87769113-6c038c00-c81d-11ea-94f9-e3500e8c7919.PNG)

**Comment by PfrLisBerndt** [comment]
Another example: 
![example](https://user-images.githubusercontent.com/43057926/93071444-72c54880-f680-11ea-925b-6cfaa653aa6c.PNG)

No matter how narrow the search area is, only a few times (appr. 2 out of 10 times) this word is recognized. 
This word on the other is recognized reliably. 

![example2](https://user-images.githubusercontent.com/43057926/93071850-f4b57180-f680-11ea-858a-08af97a08cf5.PNG)

**Comment by RaiMan** [comment]
The workaround in https://github.com/RaiMan/SikuliX1/issues/381 might help.

If interested, I can give you a pre-2.0.5 with the fix.

Also in 2.0.5 there is a new feature "light font on dark background" (https://github.com/RaiMan/SikuliX1/issues/369)

**Comment by PfrLisBerndt** [comment]
Thank you very much! 👍  But regarding to pure textrecognition without clicking my wrapper workaround can already cope with this issue, so that I can wait for the final release. :)

**Comment by RaiMan** [comment]
ok. thanks for feedback.

So I will close this for now.

**Comment by PfrLisBerndt** [comment]
Info ++++++++++++++++++++++ FINISH +++++++++++++++++++++++++++++
