### ISSUE TITLE
findText should work for light text on darker background

### ISSUE THREAD

**Issue by Pitibioup** [RaiMan/SikuliX1#369]
I have to check if the username is displayed, and it's white on a medium blue background.
text.find(usename) fails. I tested searching something else and it worked, so I think this is really due to the color of the text or maybe the font ?

**Comment by RaiMan** [comment]
The solution with 2.0.5 will be to use:
OCR.Options().lightFont()

... and then use one of the text read features on the respective region.

findText() will not be supported for this. You would have to evaluate the read text yourself.
