### ISSUE TITLE
2.0.4: Part of string of Textrecognizer-Exception message is null instead of text to read

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#370]
Function waitText
2.0.1: exception.message --> [String of text to read]+" as text"

2.0.4: exception.message --> null+" as text"

**Comment by RaiMan** [comment]
fixed with commit: https://github.com/RaiMan/SikuliX1/commit/4b447d4b72579e7f19d40355c683b1843958059b
