### ISSUE TITLE
Download Link Broken

### ISSUE THREAD

**Issue by indolering** [RaiMan/SikuliX1#371]
The [download link][download] in the primary [README.md][readme] is broken:

```
https://launchpad.net/sikuli/sikulix/2.0.4/+download/sikulix-2.0.4.jar
```

Should be:

```
https://launchpad.net/sikuli/sikulix/2.0.4/+download/sikulixide-2.0.4.jar
```

I would edit the README, but it looks like this is generated from a script?

[download]: https://launchpad.net/sikuli/sikulix/2.0.4/+download/sikulix-2.0.4.jar
[readme]: https://github.com/RaiMan/SikuliX1/blame/6161fb013595efd38e9af2446f19c897316a4de9/README.md#L31

**Comment by RaiMan** [comment]
thanks
