### ISSUE TITLE
Missing color support to evaluate a button's state

### ISSUE THREAD

**Issue by iridos** [RaiMan/SikuliX1#374]
Sikuli is not able to distinguish color at all, as far as I see from documentation and discussions on sites like stackoverflow.
I have buttons that indicate they were already pressed only by a (very visible) color change. Sikuli just cannot detect this at all. 
This cannot be an uncommon thing? How can there be not even a way to read out the color value of a pixel in the match? Or did I just not find it in documentation??

**Comment by RaiMan** [comment]
Though your above comment/question/statement reads like a recent Twitter post of Donald Trump about Kamala Harris, I am willing to give you some insights.

A match you get by a SikuliX image find op tells you with its score, how reliable the match is. Scores near 1.0 mean a (nearly) exact match.

So lets look at your case:
- you have a button, that shows its state by changing the color of some of its pixels
- you have an image of the button in its activated state
- using this image, you always find the button, no matter wether it is active or not
- you want to know, wether the button is active ore not

Now an example:
This is what we have on screen (active state)
<img width="110" alt="image" src="https://user-images.githubusercontent.com/586370/90134687-d7377400-dd71-11ea-9e27-66f771b47bdc.png">
This is what we have on screen (inactive state):
<img width="103" alt="image" src="https://user-images.githubusercontent.com/586370/90134803-051cb880-dd72-11ea-92d2-dd0cdb2dfece.png">

So we are talking about the 3 dots in the upper left.

To search for the button, I use this image (I name it activeBtn):
<img width="63" alt="image" src="https://user-images.githubusercontent.com/586370/90135034-55941600-dd72-11ea-81c1-22b0b6ad15d8.png">

Using this snippet:
```
activeBtn = "activeBtn.png"
match = find(activeBtn)
print match.getScore()
```
I get a FindFailed running it against the inactive state, which means, that the image could not be found with a score better than 0.7.

So I try this:
```
activeBtn = "activeBtn.png"
match = find(Pattern(activeBtn).similar(0.6))
print match.getScore()
```
... and get: 0.694596946239

... in the active state I get: 0.999999761581

So with the above Pattern, the button is found in both states.

Now I can decide about the state:
```
activeBtn = "activeBtn.png"
match = find(Pattern(activeBtn).similar(0.6))
if match.getScore() > 0.9:
    print "active"
else:
   print "inactive"
```

Hope it helps.
Come back, if you have more questions.

**Comment by ndinev** [comment]
Here is something that an be used to identify if button is grayed out or not. You need to provide element and offset where color to e verified. You get the RGB values of this point. In my tests I then have method that actually classify color like BLUE or GRAYED_BLUE ... etc. But those are specific to how particular AUT is implemented

`
    def GetElementColor(uiElement, dX, dY):
        import java.awt.Robot as JRobot
        myRobot = JRobot()
        find(uiElement).highlight(1)  # highlight the base element
        p = getLastMatch().getCenter().offset(dX, dY)  # create Location object for the needed point
        Region(p.x - 1, p.y - 1, 3, 3).highlight(1)  # highlight where the color will be verified
        btnColor = myRobot.getPixelColor(p.x, p.y)
        return btnColor
`
