### ISSUE TITLE
Run on selection - wait()  not working with Thumbnails 

### ISSUE THREAD

**Issue by southernal** [RaiMan/SikuliX1#376]
Using Jython when you run selection with thumbnails view active and selected code has the wait() function with a  thumbnail, run selection fail. The thumbnail is not recognized as an input.

**Comment by RaiMan** [comment]
Made several tests (Win10, Java 11, 2.0.4 and 2.0.5-pre): could not reproduce - worked as it should in various scenarios (saved, unsaved, whole script run before or not, ...).

So could you be more specific.

my example:
print "script start"
print "start"
print wait("1598971400392.png") # shown as thumbnail
print "end"
print "script end"

as selection I took the 3 lines in the middle

**Comment by southernal** [comment]
I am sorry, the problem is present only when using **try** **except**. This is the test case using your example:


print "script start"
print "start"
try:
   print wait("1598971400392.png") # shown as thumbnail
except:
   print "exception!"
print "end"
print "script end"

thank you for your great appreciated work!

**Comment by RaiMan** [comment]
Again: I do not have any problems.

In various cases everything works as expected.

So what exactly is the problem you are facing?
Run with `Debug.on(3)` as first line of the selection.
