### ISSUE TITLE
IDE: run script: IDE window does not come back --- problem: endless loop

### ISSUE THREAD

**Issue by nokaidora** [RaiMan/SikuliX1#377]
Hello,

I used Sikuli successfully a few years back and I really enjoyed it. Now I want to use it again but I can't seem to make the IDE work anymore. I can launch the sikulixide-2.0.4.jar just fine and I can type a script in the editor but when I click run, the window just disappears completely while my script apparently runs. I then have to kill it from command line or from task manager to make it stop. 

I tried this on Windows 10 with java version:

> C:\Users\CTDev>java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

I tried also on Windows 7 with java 1.8 (can't post the exact version atm) as well and got the same exact behavior.

My simple test script is:
```
while True:
  if not exists("protonlogo.PNG"):
    print("it's NOT there!")
  else:
    print("it's there!")
  sleep(5)
```

I don't see any errors in the command line output as well:

... not relevant

Any help appreciated

**Comment by RaiMan** [comment]
your script is an endless loop and hence can only be stopped by killing or using the stop-hotkey.

... non-endless

```
while True:
  if not exists("protonlogo.PNG"):
    print("it's NOT there!")
  else:
    print("it's there!")
    break # end loop if success
  sleep(5)```

**Comment by nokaidora** [comment]
Ah I see, sorry for the dumb question then.

I really did not think that the window disappearing was in fact the expected behavior but I guess it makes sense for the IDE to get out of the way on its own in the context of SikuliX.

However, I actually want my script to run indefinitely until I stop it. So in my case, it would be handy to have the window IDE stay visible so I can minimize and close it myself when needed; is there a setting to do that?
Alternatively, what way would you recommend to do that cleanly? invoke with command line and listen for input? 

I appreciate the quick response and thank you for your amazing work on Sikuli

**Comment by RaiMan** [comment]
SikuliX has 2 standard hotkeys (see Preferences):
capture: `CTRL+SHIFT 2`
stop run: `ALT+SHIFT c`

The latter is what you need.

BTW: If you are planning to use SikuliX scripting more often again: [get familiar with the docs](https://sikulix-2014.readthedocs.io/en/latest/index.html) ;-) 

One more thing: The best place to ask usage [questions like yours is still Launchpad](https://answers.launchpad.net/sikuli) (much bigger audience).

**Comment by nokaidora** [comment]
Thank you very much!

I see the capture hotkey input field in preferences but I can't find the stop run hotkey input field (not even in 'more options') but it does not matter to me. I promise I will read the docs before asking any more questions ;-)

Thanks again.
