### ISSUE TITLE
RobotDesktop Error

### ISSUE THREAD

**Issue by badboiaustria** [RaiMan/SikuliX1#379]
Hi!
I am using Sikulix 2.0.4 on Windows 10 64bit, JAVA 11, 2 large sized Monitors (3440x1440 + 2560x1440 as one display, NVIDIA).

I am getting this error:
[error] RobotDesktop: checkMousePosition: should be L[1465,1274]@S(0) - but is not!
Possible cause in case you did not touch the mouse while script was running:
 Mouse actions are blocked generally or by the frontmost application.
You might try to run the SikuliX stuff as admin.
[log] CLICK on L[1465,1274]@S(0) (34 msec)

on this script: this can be reproduced,
```
Settings.MoveMouseDelay = 0.0
if exists("1599396623669.png"):
    click(getLastMatch())    # besides the error it clicks somewhere.. on the very first click
exit()

```
this script works fine:
```
Settings.MoveMouseDelay = 0.1
if exists("1599396623669.png"):
    click(getLastMatch()) # it clicks correctly always
exit()
```

I believe its a bug.
Regards
Michael

**Comment by RaiMan** [comment]
Cannot reproduce: (neither from IDE nor from commandline):
```
*** monitor configuration [ 2 Screen(s)] ***
*** Primary is Screen 0
Screen 0: R[0,0 1920x1200]@S(0)
Screen 1: R[1920,0 1080x1920]@S(1)
*** end monitor configuration ***
[log] CLICK on L[1453,960]@S(0) (60 msec)
```
