### ISSUE TITLE
[1.1.2] [1.1.4] Screen.capture not allowing region + filename args

### ISSUE THREAD

**Issue by kaltinril** [RaiMan/SikuliX1#38]
Unless I am misunderstanding the usage of the 1.1.2 feature in documentation, this is not allowing me to send in the filename.  It appears that the text or region is required, along with the filename, but the path is optional.  That's 2 arguments.  The error says I must have 0, 1, or 4 arguments.

filename = screen.capture(screen.getBounds(), "file.png")

> [error] Error caused by: Traceback (most recent call last): File "C:\sikulix\EndUserLocation.sikuli\EndUserLocation.py", line 12, in <module> filename = s.capture(s.getBounds(), "file.png") TypeError: capture(): expected 0-1 or 4 args; got 2 

https://sikulix-2014.readthedocs.io/en/latest/screen.html?highlight=screenshot#Screen.capture
> capture(region | text, [path, ]name)
only available in Python scripting
> 
> Parameters:	
| text (region) – an existing region object or text to display in the interactive mode.
path – a path to a folder where the image is stored
text – name of the image file (.png can be omitted)
Returns:	
the absolute path of the stored image as path/name.png or None if no success

**Comment by RaiMan** [comment]
as mentioned in the docs:

> only available in Python scripting

... and has be used so:

> capture(region | text, [path, ]name)

hence undotted. Might not be clear enough - I will refine the docs.

If you want to use it dotted (only makes sense on the Java level), then it is the static Screen method

``cmdCapture()`` with the same signature. I will add this to the docs too.

**Comment by RaiMan** [comment]
> cmdCapture() with the same signature. I will add this to the docs too.

Found, that is already there.

I made some slight additions to the docs.

**Comment by kaltinril** [comment]
I found the issue.  Using screen.getBounds() returns a rectangle.  capture expects a "Region".  

**Documentation lists two separate capture methods:**
1. capture([region | rectangle | text])
2. capture(region | text, [path, ]name)

**This doesn't work:**
    `filename = capture(screen.getBounds(), "file")`

**This works:**
`    reg = Region(0, 0, screen.getBounds().width, screen.getBounds().height)`
`    filename = capture(reg, "file")`
