### ISSUE TITLE
guide.dialog results in error

### ISSUE THREAD

**Issue by badboiaustria** [RaiMan/SikuliX1#380]
Hi!
I am using Sikulix 2.0.4 on Windows 10 64bit, JAVA 11, 2 large sized Monitors (3440x1440 + 2560x1440 as one display, NVIDIA).

I am getting this error:
```
[error] script [ Play ] stopped with error in line 16
[error] NameError ( name 'dialog' is not defined )
[error] --- Traceback --- error source first
line: module ( function ) statement 
16: main (  <module> )     dialog("Part 1: Navigation Links")
[error] --- Traceback --- end --------------
```

when running this script:
```
from guide import *
text("1599588491358.png","Use these to jump to other parts")
dialog("Part 1: Navigation Links")
show()
```
 I would expect a popoup, etc. as described in: https://sikulix-2014.readthedocs.io/en/latest/extensions/sikuli-guide/

Thanks
Michael

**Comment by RaiMan** [comment]
**The important note from the link above**
>The Guide feature has been completely revised. The following original documentation might give an impression about the intention and the principally available features, but might not work as expected in 1.1.1+
>For information about the API you currently have to look into the sources (Lib/guide/guide.py for Python and org.sikuli.guide.xxx for Java). The revision focused on the static features (annotation types), so the interactive features might not work as expected.
>This feature has the state experimental, meaning it might change at any time without notice and without any guarantee to be fully backwards compatible.

[These features should be available](https://sikulix-2014.readthedocs.io/en/latest/extensions/sikuli-guide/#function-references)

So you have to live with the current state. Guide is not on the priority list.
