### ISSUE TITLE
Observer matches outside Screen - wrong results

### ISSUE THREAD

**Issue by badboiaustria** [RaiMan/SikuliX1#382]
******** fixed in 2.0.5 (commit https://github.com/RaiMan/SikuliX1/commit/731f285a104526f83d85606297318e097715ba4f)
a new `onChange` for the same Region object overrides an existing one while keeping the existing event name.

-------------------------

Hi!
I am using Sikulix 2.0.4 on Windows 10 64bit, JAVA 11 (1.8.0_261), 2 large sized Monitors (3440x1440 + 2560x1440 as one display, NVIDIA).

It seems Observe captures events outside the screen after a couple of correct matches. 
This behavior can be reproduced anytime, also on Windows 7 VM with 1 monitor. For instance let it run on a youtube video or animated gif.
As you can see, the match moves lower and lower. This has also a second sideeffect: the first matches are correct, and later after a couple of matches there are matches found where only changes appeared above the watched region.

Following script:

```
def testObserver():
    RegUnten=Region(37,1305,1791,35)
    RegUnten.highlight(3)
    for t in range(0,30) :
        print_l(t,RegUnten)
        RegUnten.onChange(35, ObserverEvent) 
        RegUnten.observe(3)


def ObserverEvent(event):
    RegUnten=Region(37,1305,1791,35)
    print_l("Number of Events:",len(event.getChanges()))
    for t in range(0,len(event.getChanges())):
        print_l(t,":Event !",event.getChanges()[t],event.getChanges()[t].getCenter().getY(),"vs.",RegUnten)
showMonitors()
testObserver()
exit()        
```
results in: (remember my screens are only 1440 pixels tall...)

*** monitor configuration [ 2 Screen(s)] ***
*** Primary is Screen 0
Screen 0: R[0,0 3440x1440]@S(0)
Screen 1: R[-2560,-357 2560x1440]@S(1)
*** end monitor configuration ***
[log] highlight R[37,1305 1791x35]@S(0) for 3.0 secs
0 R[37,1305 1791x35]@S(0) 
Number of Events: 2 
0 :Event ! M[1620,1310 9x8]@S(0) S:1,00 C:1624,1314 [-1 msec] 1314 vs. R[37,1305 1791x35]@S(0) 
1 :Event ! M[439,1305 1388x34]@S(0) S:1,00 C:1133,1322 [-1 msec] 1322 vs. R[37,1305 1791x35]@S(0) 
Number of Events: 5 
0 :Event ! M[1640,1327 6x6]@S(0) S:1,00 C:1643,1330 [-1 msec] 1330 vs. R[37,1305 1791x35]@S(0) 
1 :Event ! M[1645,1316 6x6]@S(0) S:1,00 C:1648,1319 [-1 msec] 1319 vs. R[37,1305 1791x35]@S(0) 
2 :Event ! M[1623,1312 6x7]@S(0) S:1,00 C:1626,1315 [-1 msec] 1315 vs. R[37,1305 1791x35]@S(0) 
.
. stripped a couple of lines here
.
Number of Events: 2 
0 :Event ! M[1813,1318 6x7]@S(0) S:1,00 C:1816,1321 [-1 msec] 1321 vs. R[37,1305 1791x35]@S(0) 
1 :Event ! M[439,1305 1388x34]@S(0) S:1,00 C:1133,1322 [-1 msec] 1322 vs. R[37,1305 1791x35]@S(0) 
Number of Events: 2 
0 :Event ! M[1850,2623 6x7]@S(?) S:1,00 C:1853,2626 [-1 msec] 2626 vs. R[37,1305 1791x35]@S(0) 
1 :Event ! M[476,2610 1388x34]
[error] Region(1850,2623,6,7) outside any screen - subsequent actions might not work as expected
[error] Region(476,2610,1388,34) outside any screen - subsequent actions might not work as expected
[error] Region(1887,3928,6,7) outside any screen - subsequent actions might not work as expected
...

**Comment by badboiaustria** [comment]
It seems the problem goes away with that script:
```
def testObserver():
    RegUnten=Region(37,1305,1791,35)
    RegUnten.highlight(3)
    for t in range(0,30) :
        RegUnten=Region(37,1305,1791,35)     **# added this line**
        print_l(t,RegUnten)
        RegUnten.onChange(35, ObserverEvent) 
        RegUnten.observe(3)


def ObserverEvent(event):
    RegUnten=Region(37,1305,1791,35)
    print_l("Number of Events:",len(event.getChanges()))
    for t in range(0,len(event.getChanges())):
        print_l(t,":Event !",event.getChanges()[t],event.getChanges()[t].getCenter().getY(),"vs.",RegUnten)
showMonitors()
testObserver()
exit()  
```

**Comment by RaiMan** [comment]
Ok, thanks. I will check.

In any case, this is the correct setup for your case:
```
def testObserver():
    RegUnten=Region(37,1305,1791,35)
    RegUnten.highlight(3)
    RegUnten.onChange(35, ObserverEvent) 
    for t in range(0,30) :
        RegUnten.observe(3)
```

In your first setup, you are trying to add a new `onChange` to an existing Region object. It makes sense, that one Region object should only have one `onChange`.
In your second approach, you are creating the Region object inside the loop, which in turn leads to the one-Region-one-onChange.

**Comment by RaiMan** [comment]
OK, I can reproduce.

It happens only if you add more than one `onChange` to the same Region object.

As mentioned above: One Region object should have only one `onChange`. 

I will revise it in 2.0.5, so that a new `onChange` will replace/overwrite an existing `onChange`.
