### ISSUE TITLE
HTTPS(TLS) for sikulix.com

### ISSUE THREAD

**Issue by C0rn3j** [RaiMan/SikuliX1#391]
The site currently does not have a certificate.
Well, it does, but a self signed one, and HTTP does not redirect to HTTPS.

https://letsencrypt.org/ provides free TLS certificates, it would be great if one could be used for the main site

http://sikulix.com
https://sikulix.com

**Comment by RaiMan** [comment]
Thanks for the hint, but its not worth for such a simple web page.
Will move it to GitHub anyways.
