### ISSUE TITLE
macOS 10.15+ Sikulix IDE 2.0.4 does not open

### ISSUE THREAD

**Issue by Sidu28** [RaiMan/SikuliX1#394]
Currently on macOS 10.15.  

I followed the instructions at this link: https://github.com/RaiMan/SikuliX1/wiki/GettingStarted-on-macOS

When I download the sikuli-2.0.4.jar as well as the jython-standalone-2.7.1.jar and place them in the downloads folder, I continue to get the error window "Niether Jython or JRuby is available.  When I go into the Extensions folder, there is also no extensions.txt file.

**Comment by RaiMan** [comment]
Use either Java 8 or Java 11, preferably from here: https://adoptopenjdk.net

As mentioned on the download page:
```
Download what you prefer or both to the same folder as you have your sikulix.jar. 
They will be recognized by SikuliX at the next start and moved to the SikuliX's extension folder. 
So preferably download before using the IDE the first time.
```

After download you should have these files in a folder:
```
sikulixide-2.0.4.jar
jython-standalone-2.7.1.jar
```

Double-click the `sikulix....jar` and you should get the startup-badge.

If you never used SikuliX before, then you have to allow some aspects in the macOS preferences to java, which should be noted by macOS with some popups.

If it does not work as expected, run this from a command line (Terminal window):
```
java -jar <path-to>/sikulixide-2.0.4.jar -v -c
```
to get the start-up log.

**Comment by Sidu28** [comment]
Ok, here's what happened - I installed java 8 and double clicking on the sikuli jar file still does nothing, it just hangs.  However running the "java -jar <path-to>/sikulixide-2.0.4.jar -v -c" command in the terminal does successfully launch the IDE.

**Comment by Sidu28** [comment]
A quick thing, how do we get the command List to show up in the IDE?  In its current state I do not see a command list on the left panel

**Comment by RaiMan** [comment]
>command list

... sorry, no longer available.

>clicking on the sikuli jar file still does nothing

check in `System Preferences` -> `Security & Privacy` -> tab `Privacy` that `java` is allowed with `Screen Recording`.
Allowance with `Accessibility` might also be a problem.
