### ISSUE TITLE
Exact does not find difference in image

### ISSUE THREAD

**Issue by hessels22** [RaiMan/SikuliX1#395]
Hello!

I am trying to verify that button presses gets recognized by my backend. For starters(before I venture into OCR) I just wanted to try to do image match, but the exact match is not working as expected. It does not fail when I feed it a wrong input.

I have opened the image from the IDE, to do a matching preview. This also incorrectly identifies the wrong image as an exact match. See images attached. The image FromTargetOffset is the current screen that is displayed, the ImageSavedForMatching is my target, and FromMatchingPreview is to show that the IDE find the incorrect image.

I use SikulixIDE-2.0.4

My code(indententation was screwed when pasting):

def findWithTryCatch(img):
    try:
        wait(img,3)
    except FindFailed:
        result = popAsk("Test failed!\nContinue?")
        if not result:
            printErrorToLog("Failed at image: " + img.getFilename())
            exit()
        else:
            printErrorToLog("Failed at image: " + img.getFilename())

findWithTryCatch(Pattern("1606914992857.png").exact())

FromMatchingPreview 
![FromMatchingPreview](https://user-images.githubusercontent.com/8081440/100988363-f0964300-354f-11eb-8b97-e74a55bed28c.png)
FromTargetOffset 
![FromTargetOffset](https://user-images.githubusercontent.com/8081440/100988367-f12ed980-354f-11eb-92f1-09c495b0a85e.png)
ImageSavedForMatching 
![ImageSavedForMatching](https://user-images.githubusercontent.com/8081440/100988369-f12ed980-354f-11eb-82c8-ac3793060cfc.png)

**Comment by hessels22** [comment]
After further evaluation and trying to reproduce the result the same way it is implemented in Sikulix, I can conclude that this is not an bug in the software, but merely a problem of too high resolution images in a visualization that has a lot of big black areas.

OCR has to be the way forward, I assume.

**Comment by hessels22** [comment]
As a side note:
The problem is that the template matching gives a similarity of 0.994 when given the "wrong" image. Downscaling the images makes it work as expected.

**Comment by RaiMan** [comment]
What do you mean by 

> Downscaling the images makes it work as expected.

**Comment by hessels22** [comment]
I made python script to run the same algorithm from OpenCV as you do, i.e the Template matching with Normalized Cross Correlation, to get the similarity value out. 
When running the original setup as posted, the template matching returned 0.998 when I would have liked it to fail. 

I then resized the images to 50% of the original size and ran the template matching again.
Finding the correct image was still above 0.99 but the incorrect had fallen to 0.92.

See terminal output:

![output](https://user-images.githubusercontent.com/8081440/101472848-6a13a400-3949-11eb-850c-c0cc3ec87e4b.png)
First runthrough is with the correct image, second runthrough is with the incorrect image.

**Comment by hessels22** [comment]
The downscaling test was just to prove my theory of the images being too big and too similar.

**Comment by RaiMan** [comment]
I principally understand, what you have done, but based on this thread, it is not clear, what the images `source2`, `target` and `target2` are.

... and `SikuliX's Pattern.exact() `internally only means, that the score is > 0.99. So in your case exact() does not help, since the difference is only shown comparing as >0.999. 
`Match.getScore()` gives you the value as not rounded to 2 decimals.

**Comment by hessels22** [comment]
source2 is the full image with target.png present
Target.png is the same as ImageSavedForMatching in the original post.
Target2.png is the same as FromTargetOffset in the original post.

I will look into the Match.getScore on the result of my wait commands to verify.

Thanks for the feedback

**Comment by RaiMan** [comment]
Sorry, but not really helpful.

> source2 is the full image with target.png present

cannot find such an image here

> Target2.png is the same as FromTargetOffset in the original post.

This is a screenshot from an IDE window, that might not have the same resolution and on top has a red frame

... but it does not matter in the end - I can make my own tests.
Thanks anyways.
