### ISSUE TITLE
Could not find artifact jxgrabkey:jxgrabkey:jar:1.0 in sonatype-ossrh

### ISSUE THREAD

**Issue by vertigo17** [RaiMan/SikuliX1#396]
I work on another projet that use sikuli for automation on fat application.
Unfortunately, I con't compile my project any longer linked with the following error:

[ERROR] Failed to execute goal on project cerberus-extension-sikuli: Could not resolve dependencies for project org:cerberus-extension-sikuli:jar:1.1.7-SNAPSHOT: Could not find artifact jxgrabkey:jxgrabkey:jar:1.0 in sonatype-ossrh (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

I added the repo section to my pom but it did not help.

```
    <repositories>
        <repository>
            <id>sonatype-ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

```

Can you help me to find the good repo to get jxgrabkey:jar file dep ?
Thanks

**Comment by vertigo17** [comment]
I solved it by adding:

```
<repository>
    <id>uni-due.de</id>
    <url>http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/</url>
</repository>
```
Don't know if solution is the good one but at least I can now build my project.

**Comment by RaiMan** [comment]
If everything works, it is just fine.

When I had the same problem some time ago, I simply put the source code into my project:
https://github.com/RaiMan/SikuliX1/tree/master/API/src/main/java/jxgrabkey
