### ISSUE TITLE
libVisionProxy.so not usable

### ISSUE THREAD

**Issue by vertigo17** [RaiMan/SikuliX1#397]
I am under linux kubuntu
Linux 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I ddid follow the instructions documented [here](https://raiman.github.io/SikuliX1/downloads.html) and manage to have the IDE working fine on my Linux box ;-)

Then I started to use the JAVA API part of sikuli from my [project](https://github.com/cerberustesting/cerberus-extension-sikuli)
I manage to compile using the maven context.

I build a jar file that is supposed to interact with Sikuli API but each time I trigger a a sikuli command I get this error: 

16:43:07.221 INFO - Received: [Request from 127.0.0.1]
16:43:07.235 INFO - Executing: [click: on picture picture/2020.12.04.16.43.07.229..png]
[info] runcmd: lsb_release -i -r -s 
[error] RunTimeAPI: loadLib: libVisionProxy.so not usable: 
java.lang.UnsatisfiedLinkError: /home/ben/.Sikulix/SikulixLibs_201510081336/libVisionProxy.so: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
[error] RunTimeAPI: loadLib: libVisionProxy.so not usable: 
java.lang.UnsatisfiedLinkError: /home/ben/.Sikulix/SikulixLibs_201510081336/libVisionProxy.so: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
[info] runcmd: ldconfig -p 
[info] runcmd: wmctrl -m 
[info] runcmd: xdotool version 
[info] runcmd: /home/ben/.Sikulix/sikulixlibs/linux/runBuild 

How can I solve that in order to get it work like the IDE ?

thanks

**Comment by RaiMan** [comment]
Seems not to be a latest version of SikuliX!?

**Comment by vertigo17** [comment]
Sorry, My fault, I moved to latest version in my POM and now it works fine.
Latest version is indeed a lot more simple to integrate.
Thanks.
