### ISSUE TITLE
VNC is broken since 1.1.3

### ISSUE THREAD

**Issue by sopak** [RaiMan/SikuliX1#4]
VncScreen.java:40
``` 
 public static VNCScreen start(String theIP, int thePort, String password, int cTimeout, int timeout) throws IOException {
    VNCScreen scr = null;
    if (RunTime.get().runningMac && !RunTime.get().isJava9("VNCScreen not yet working on Mac")) {
      scr = new VNCScreen(VNCClient.connect(theIP, thePort, password, true));
      screens.put(scr, scr.client);
    }
    return scr;
  }
```
method start always return null on non Mac machine

**Comment by RaiMan** [comment]
Uuuups, must have been drunken, when adding a check that VNC cannot be used on Mac with Java 9+

Should be fixed with nightly build #19

Thanks for finding

**Comment by amir3code** [comment]
Hello RaiMan I find that you were struggling with the testing part of VNC.
I have a solution to this:

1. Install docker
2. run the command: `docker run --rm -d -p 5901:5901 -p 6901:6901 consol/ubuntu-icewm-vnc`

It will bring up a container and will expose two ports: `5901` and `6901`.

`5901` is the read vnc port
`6901` is noVNC (or html5 vnc which can be browsed using a web browser)

You can then use any ip address your machine has (`ip a | grep inet`) and vnc to your container.
You can test with this and it is easy and fast (although it uses 1GB of harddisk and downloads about 400MBs)

You have done great work, but please work on the vnc part more cause as I can see it is the best way to automate GUIs. We can have a vnc server everywhere and we can run a client everywhere, this is powerful! So please take time. I myself highly appreciate your work. Thanks.

**Comment by teras** [comment]
@RaiMan Is it possible to connect to the OSX VNC server ?
I am trying to connect but I always get a "No matching security types" exception :(
