### ISSUE TITLE
vidstige jadb dependency version no more available in jitpack rep

### ISSUE THREAD

**Issue by aino-gautam** [RaiMan/SikuliX1#40]
While trying to use sikulix api the following dependency cannot be found anymore

```
<dependency>
      <groupId>com.github.vidstige</groupId>
      <artifactId>jadb</artifactId>
      <version>-v1.0-g94ebf38-23</version>
      <!--License Apache 2-->
</dependency>
```

After some investigation it seems the corresponding release / tag is no more there in the github repo and the build is not available anymore in jitpack.io repository. 

Thus preventing use of sikulix API 1.1.3+ in code.

**Comment by RaiMan** [comment]
1.1.3 is not supported anymore.

If you really need the sources, you have to repair things yourself.

Android/ADB support will be revised and brought back in version 1.1.4.
