### ISSUE TITLE
Linux(2.0.4): App("Terminal").window() return region R[0,0 1x1]@S(0) 

### ISSUE THREAD

**Issue by petrukhnov** [RaiMan/SikuliX1#403]
Currently it is not possible to get region from App in Linux (e.g. Ubuntu desktop)

App("Terminal").window() always return region R[0,0 1x1]@S(0) 

sikulix 2.0.4
org.sikuli.natives.LinuxUtil
line 200

public Rectangle getWindow(App app, int num) {
    return new Rectangle();
}

While other OSUtil classes have proper implementation.

**Comment by petrukhnov** [comment]
Possible workaround:

App app = new App("Terminal")
app.focus()
Region reg2 = App.focusedWindow()

**Comment by RaiMan** [comment]
thanks.
