### ISSUE TITLE
IDE module not compiling with JDK 1.8 due to lack of desktop package in awt

### ISSUE THREAD

**Issue by aino-gautam** [RaiMan/SikuliX1#41]
After checking out and building the SikuliX1 1.1.3 all modules I am getting a compilation error on this line

https://github.com/RaiMan/SikuliX1/blob/dc855c6e9ff3968d1f228971bfbfb1636b2632ad/IDE/src/main/java/org/sikuli/idesupport/IDEMacSupport.java#L10

As I understood the source and compiled code is compatible with JDK 1.8 but seems this package was introduced in JDK 9 . May be its simply a documentation issue that we need to build the project with JDK 9 or higher ? not sure.

**Comment by RaiMan** [comment]
Sorry, I do not support 1.1.3 anymore.

But yes: you have to build with at least Java 9 (recommended Java 11).
... but the artefacts run on Java 8+

**Comment by RaiMan** [comment]
BTW: In the java source you can find:

```
/**
 * This class only compiles with Java 9+
 * If you want to compile with Java 8, you have to hide this classfile<br>
 * (is possible, because it is accessed in Java 9 only using reflection)
 */
```

**Comment by paul-hammant** [comment]
There's a couple of ways that the POM can explicitly note JDK 9+. Here's one:

```
<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <source>1.9</source>
                        <target>1.9</target>
                    </configuration>
                </plugin>
```

**Comment by RaiMan** [comment]
@paul-hammant 
Thanks for the hint, but that is not what is needed.
Both source and target have to be Java 8

What is needed is an option to exclude the mentioned classfile from compilation, when the build runs on Java 8. I did not find such an option until now.

so only hiding the classfile in this case IMHO helps.

**Comment by paul-hammant** [comment]
Towards tactical exclusion: One or both of Joe Walnes' QDox or XStream does stages of JDK compilation into the same jar, in order to take advantage of JDK-specific classes in JDK 5, 6, 7+. Well I say Joe, but there were multiple contributors towards that. Specifically, multiple runs through with Javac, then a single zipping into a Jar that's adaptive between those JDKs. That was 10 years ago, and the need for that homogenization may be gone now.
