### ISSUE TITLE
[Windows 10/java 8] ImportError when using the -r command line argument but not when using the IDE

### ISSUE THREAD

**Issue by kokounet** [RaiMan/SikuliX1#410]
Hello!
I recently had a bug in SikuliX 2.0.4 in Windows 10 64bits using java 8 where executing from command line generate an error but not when executing using the IDE.

Minimal example to reproduce the issue:

project directory:
```
root
  ├ lib.py
  ├ script.py
  └ sikulix-2.0.4.jar
```

Content of `lib.py`:
```python
def a():
    print("Hello world!")
```

Content of `script.py`:
```python
from lib import a

if __name__ == "__main__":
    a()
```

Running this script using `java -jar sikulix-2.0.4.jar -r script.py` gives the following error:
```
[error] script [ main ] stopped with error in line 1
[error] ImportError ( No module named lib ) 
[error] --- Traceback --- error source first
line: module ( function ) statement
1: main (  <module> )     from lib import a 
[error] --- Traceback --- end --------------
```

But it works fine using the ide as this gif demonstrate:
![2021-01-22_17-02-31](https://user-images.githubusercontent.com/25613312/105514420-bfc2c680-5cd3-11eb-914a-54994d337e1c.gif)

Also using `--run` instead of `-r` opens the ide which I think is not supposed to do.

Great work on this tool !
Cheers,
Chris

**Comment by RaiMan** [comment]
Have to check.

**Comment by RaiMan** [comment]
works in 2.0.5
