### ISSUE TITLE
Conflicting dependencies, log4j-over-slf4j vs log4j and jcl-over-slf4j vs commons-logging

### ISSUE THREAD

**Issue by TeofilisMartisius** [RaiMan/SikuliX1#412]
Hello,

I'm trying to get sikulixapi 2.0.4 with JavaFX and that needs Java9 modules to be enabled. Modules system is quite strict and complains if several jars provide the same module.

In your dependency tree, log4j and commons-logging are provided both by original jars, and by slf4j bridges. It should be only slf4j. Please exclude log4j and commons-logging from dependencies.

Sincerely,
Teofilis Martisius

[INFO] \- com.sikulix:sikulixapi:jar:2.0.4:compile
[INFO]    +- com.sikulix:sikulix2tigervnc:jar:1.1.4:compile
[INFO]    +- commons-cli:commons-cli:jar:1.4:compile
[INFO]    +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO]    +- net.java.dev.jna:jna-platform:jar:5.4.0:compile
[INFO]    |  \- net.java.dev.jna:jna:jar:5.4.0:compile
[INFO]    +- net.oneandone.reflections8:reflections8:jar:0.11.6:compile
[INFO]    |  \- org.javassist:javassist:jar:3.22.0-GA:compile
[INFO]    +- net.sourceforge.tess4j:tess4j:jar:4.4.1:compile
[INFO]    |  +- com.github.jai-imageio:jai-imageio-core:jar:1.4.0:compile
[INFO]    |  +- org.ghost4j:ghost4j:jar:1.0.1:compile
[INFO]    |  |  +- **log4j:log4j:jar**:1.2.17:compile
[INFO]    |  |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO]    |  |  |  \- commons-collections:commons-collections:jar:3.2.1:compile
[INFO]    |  |  +- org.apache.xmlgraphics:xmlgraphics-commons:jar:1.4:compile
[INFO]    |  |  \- com.lowagie:itext:jar:2.1.7:compile
[INFO]    |  +- org.apache.pdfbox:pdfbox:jar:2.0.17:compile
[INFO]    |  |  +- org.apache.pdfbox:fontbox:jar:2.0.17:compile
[INFO]    |  |  \- **commons-logging:commons-logging:jar**:1.2:compile
[INFO]    |  +- org.apache.pdfbox:pdfbox-tools:jar:2.0.17:compile
[INFO]    |  |  \- org.apache.pdfbox:pdfbox-debugger:jar:2.0.17:compile
[INFO]    |  +- org.apache.pdfbox:jbig2-imageio:jar:3.0.2:compile
[INFO]    |  +- commons-io:commons-io:jar:2.6:compile
[INFO]    |  +- net.sourceforge.lept4j:lept4j:jar:1.12.3:compile
[INFO]    |  +- org.jboss:jboss-vfs:jar:3.2.14.Final:compile
[INFO]    |  |  \- org.jboss.logging:jboss-logging:jar:3.1.4.GA:compile
[INFO]    |  +- org.slf4j:jul-to-slf4j:jar:1.7.28:compile
[INFO]    |  +- **org.slf4j:jcl-over-slf4j:jar**:1.7.28:compile
[INFO]    |  \- **org.slf4j:log4j-over-slf4j:jar**:1.7.28:compile
[INFO]    \- org.slf4j:slf4j-nop:jar:1.7.28:compile
[INFO]       \- org.slf4j:slf4j-api:jar:1.7.28:compile

**Comment by RaiMan** [comment]
could you give me some hints, how to incorporate this into my pom?

**Comment by TeofilisMartisius** [comment]
Sent a PR with a fix.

**Comment by RaiMan** [comment]
See #415
