### ISSUE TITLE
4k + 2k monitors are recongized as 2k + 2k.

### ISSUE THREAD

**Issue by kaijianwang** [RaiMan/SikuliX1#414]
I have 2 monitors. The primary monitor is 4k and the secondary monitor is 2k.

However, SikuliX seems not recognizing my primary monitor correctly. The following logs show up when I start it with `-c -v`.
```
[1167 debug] Screen: Monitor 0: (3072, 0) 2048 x 1152
[1167 debug] Screen: ScreenDevice 1 has (0,0) --- will be primary Screen(0)
[1168 debug] Screen: Monitor 1: (0, 0) 2560 x 1440
```

**Comment by RaiMan** [comment]
What system? What Java? what SikuliX?

SikuliX uses/reports the information of the `GraphicsDevice`s returned by 
`java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()`

So in doubt this is a system-setup/Java problem.
Something like the pixel-doubling in a Retina display is simply ignored by Java.

**Comment by RaiMan** [comment]
no feedback

**Comment by kaijianwang** [comment]
System: Windows 10 pro 2004
Java: 14.0.2 OpenJDK
SikuliX: 2.0.4

**Comment by kaijianwang** [comment]
Sorry for the late reply.

**Comment by RaiMan** [comment]
As long as everything works well, simply ignore it.

On my iMac I have a 4K/Retina display where the macOS reports 4096x2304, but Java/SikuliX shows 2048x1152. 
On the way to the monitor, each image pixel simply gets 4 monitor pixels.
