### ISSUE TITLE
Tess4J setup for Linux computers - SikuliX v1.1.4 Build #272

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#417]
Hi Raimund, Happy 2021 to you and family! I'm Ken from the [TagUI automation project](https://github.com/kelaberetiv/TagUI).

Right now I'm using SikuliX v1.1.4 (Build # 272) in TagUI to provide computer vision, OCR, low-level keyboard and mouse capabilities. I have a user who's using it on Linux, and I've asked him to follow the setup instructions you gave at -
https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

![Screenshot 2021-02-01 at 9 28 19 PM](https://user-images.githubusercontent.com/10379601/106477089-bc54e980-64e2-11eb-9e3c-4b5c9772e2c4.png)

He has a question on how to setup Tess4J. May I check with you if installation and setup of Tess4J required for v1.1.4?

Thank you! Below is his question at TagUI repo - https://github.com/kelaberetiv/TagUI/issues/916#issuecomment-770348239 (copying @marcelocecin)

---

hello Ken, do you know in which Linux folder do I need to put the tess4j-4.5.4.jar file?
https://sikulix-2014.readthedocs.io/en/latest/textandocr.html?highlight=tess4j
thank you

tesseract 4.1.1
leptonica-1.79.0
libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
Found AVX
Found SSE
Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import cv2
cv2.version
'4.2.0'

**Comment by marcelocecin** [comment]
@kensoh wouldn't it be possible to use the most current version of SikuliX?

**Comment by kensoh** [comment]
From what I recall, in later versions of SikuliX, there is a need to do some manual installation of components. For v1.1.4 I can package the SikuliX files including the Jython library, and let users unzip and run TagUI directly. Also, v1.1.4 is similar to v2 from what I recall, the architecture has changed and moved away from the original v1.

**Comment by RaiMan** [comment]
@kensoh 
Where can I read/see, how you integrate SikuliX into your package?

I do not support version 1.x any longer.
Current version is 2.0.4, which runs on Java 8+.
My current focus is getting 2.0.5 to final during this month.
... and I have to admit, that getting SikuliX working on Linux distros is always some effort and not really my focus/experience.

So if I understand your Sikuli-integration concept, I surely can make suggestions or even fix something of interest.

**Comment by RaiMan** [comment]
@marcelocecin
I already saw your question somewhere else.

Tess4J is bundled in the SikuliX jars as the access layer to Tesseract. No need to have an extra Tess4J jar.
On Linux, you have to provide Tesseract 4.1.x in a libs folder, where the Java native code loader can find it.

**Comment by marcelocecin** [comment]
@RaiMan I have two files at `/lib/x86_64-linux-gnu/` 
<img width="215" alt="" src="https://user-images.githubusercontent.com/2955762/106499107-eb496c00-649e-11eb-8c90-31a61c953653.png">


[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /lib/x86_64-linux-gnu/libtesseract.so.4: undefined symbol: TessPDFRendererCreateTextonly )
[error] --- Traceback --- error source first
line: module ( function ) statement
354: main ( text_read ) temp_text = region_layer.text()
331: main ( save_intent ) return text_read(raw_intent)
526: main ( parse_intent ) return save_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1

**Comment by RaiMan** [comment]
@marcelocecin 
You need a Tesseract 4.1.x lib

**Comment by marcelocecin** [comment]
I did the installation from scratch
I downloaded the file https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz
tar -zxvf 4.0.0-beta.1.tar.gz
cd tesseract-4.0.0-beta.1 /
./autogen.sh
PKG_CONFIG_PATH = / usr / local / lib / pkgconfig LIBLEPT_HEADERSDIR = / usr / local / include ./configure --with-extra-includes = / usr / local / include --with-extra-libraries = / usr / local / lib
LDFLAGS = "- L / usr / local / lib" CFLAGS = "- I / usr / local / include" make -j
make install
ldconfig

the error continues:
[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /usr/local/lib/libtesseract.so.4: undefined symbol: TessPDFRendererCreateTextonly )
[error] --- Traceback --- error source first
line: module ( function ) statement 
354: main (  text_read )     temp_text = region_layer.text()
331: main (  save_intent )     return text_read(raw_intent)
526: main (  parse_intent )     return save_intent(script_line)
[error] --- Traceback --- end --------------
IDE terminated: returned: 1

**Comment by RaiMan** [comment]
@marcelocecin 
> I downloaded the file https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz

... but what I see in your log is `4.0.0-beta.1.tar.gz`

So please make sure, it is the version 4.1.1 you have installed.

**Comment by marcelocecin** [comment]
sorry, I copied the instructions from another website, but I installed version 4.1.1
I will edit the comment above

**Comment by marcelocecin** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3274
https://github.com/nguyenq/tess4j/issues/209

**Comment by marcelocecin** [comment]
It looks like your SikuliX is still loading tess4j-3.x version for Tesseract 3.x, which has TessPDFRendererCreateTextonly function. That function is removed in Tesseract 4.x. You need to upgrade SikuliX to use tess4j-4.5.4 to go with your Tesseract 4.1.1. (nguyenq reply on issue # 209)

**Comment by RaiMan** [comment]
To be clear:
- SikuliX versions before 2.0.4 might not work any longer especially on Linux, because they need specific dependencies (OpenCV and Tesseract) 
- Tess4J (the Java interface to the Tesseract library) is bundled with SikuliX. You cannot use another Tess4J with SikuliX.
- SikuliX version 2.0.4 contains Tess4J 4.5.x, which needs Tesseract 4.1.x

SikuliX 1.1.4 uses older versions (V 3) of Tess4J/Tesseract, which must fit together (since Tess4J is bundled)

I do not support Sikulix with older versions before 2.0.4 any longer regarding any system specific aspects (especially Linux).
... and the OCR features in 1.1.4 do not really work well.

**Comment by marcelocecin** [comment]
I downgraded tesseract to version 3.05.02
the error has now changed:
Failed loading language 'eng'
Tesseract couldn't load any languages!

**Comment by marcelocecin** [comment]
ok thanks !

**Comment by kensoh** [comment]
Thanks @RaiMan for your reply!

On your question on how TagUI integrates with SikuliX, I created a video with demos to run through the topics below - https://www.youtube.com/watch?v=_b9YYH-zYCY

>I've also created an [issue](https://github.com/kelaberetiv/TagUI/issues/928) over at TagUI repo for future reference -
>
>There is an existing issue https://github.com/kelaberetiv/TagUI/issues/916 on specific setup question on Linux for SikuliX. So I raised an issue over at Raimund's project https://github.com/RaiMan/SikuliX1/issues/417. Raimund has been the maintainer of SikuliX quite early on, where it was originally created at MIT.
>
>TagUI comes packaged with SikuliX for the computer vision (OpenCV), OCR (Tesseract), low level keyboard and mouse capabilities. Without SikuliX project, TagUI project would not be so powerful. Raimund asked about how the integration works so I thought to create this issue to put all these info here.

**Flow chart of TagUI architecture**

![flowchart](https://user-images.githubusercontent.com/10379601/106833700-f5ea4800-66ce-11eb-85f3-3ac9b1e51208.png)

**TagUI's SikuliX Jython script**
https://github.com/kelaberetiv/TagUI/blob/master/src/tagui.sikuli/tagui.py

**Entry point to invoke SikuliX process** - MacOS/Linux and Windows
https://github.com/kelaberetiv/TagUI/blob/5ab3f7c9e0f8ab2c917f09e6a711f636785c6c25/src/tagui#L292
https://github.com/kelaberetiv/TagUI/blob/5ab3f7c9e0f8ab2c917f09e6a711f636785c6c25/src/tagui.cmd#L954

**Packaging for distribution with TagUI**
Following files come with TagUI packaged zips here - https://tagui.readthedocs.io/en/latest/setup.html
```
tagui/src/sikulix/LICENSE.txt
tagui/src/sikulix/sikulix.jar (v1.1.4)
tagui/src/sikulix/jython-standalone-2.7.1.jar
```

**Credits to SikuliX on TagUI project page**
https://github.com/kelaberetiv/TagUI#credits

![c](https://user-images.githubusercontent.com/10379601/106835150-c721a100-66d1-11eb-9bb3-642e059fc047.png)

---

**Comment by RaiMan** [comment]
@kensoh 
Ok, great thanks. I will dive into it and come back asap.
May take some days dew to my works on getting 2.0.5 out.

**Comment by kensoh** [comment]
Thank you Raimund, absolutely no hurry at all!

On my end I respond fast to users but the TagUI project takes a very longterm view, no hurry to iron the details out.

In the video, I also shared that in the last 2 years, there were 40k downloads of TagUI, and each copy comes with SikuliX. Your wonderful work has made it possible for TagUI users to enjoy many of its best features.

PS - the actual user count I can't really track because people can download 1 copy and share internally on intranet or with colleagues. Folks may also download and stop using after that. So I can only share the count from GitHub statistics.

**Comment by RaiMan** [comment]
Thanks for kind feedback.

I know, that SikuliX is well accepted. For version 2.0.4 I have more than 80k downloads of the IDE package since March 2020.

While working on the final 2.0.5 during February, I will have a look into your provided information and hopefully can make some suggestions.

**Comment by RaiMan** [comment]
@kensoh 
OK, had a look into TagUI and now understand principally, how it works.

About interfacing to SikuliX, I understand, that for each line/block using vision features, a SikuliX script is generated and then run using the -r command line parameter of SikuliX. This means, that each evaluation might at least take 5 to 10 seconds due to the SikuliX startup delay.

When I have the 2.0.5 ready, I will make a suggestion, how to evaluate vision lines/blocks without this delay based on a SikuliX running in the background and waiting for the next script trigger.

**Comment by kensoh** [comment]
Thanks @RaiMan! There is some correction. TagUI only invokes SikuliX process once during its whole execution. It does this by running SikuliX at the start with https://github.com/kelaberetiv/TagUI/blob/master/src/tagui.sikuli/tagui.py

After that, every time a line of instruction requires SikuliX features, TagUI will pass that instruction to above process to parse and do the SikuliX method accordingly. After the whole execution is completed, then a message will be passed to SikuliX to exit the infinite loop.

The passing of messages is done using 2 files, 1 file for TagUI to send message to SikuliX's process, and 1 file for that process to send result back to TagUI. The communication is done synchronously and blocking as you would expect in order to ensure that everything is ran in the correct order as it is written.

**Comment by RaiMan** [comment]
OK, thanks for clarification. My bad - did not look carefully enough :-(

During February, I will make some tests with the pre-final 2.0.5 and hopefully come back with suggestions.
