### ISSUE TITLE
Maybe here a mistake.

### ISSUE THREAD

**Issue by gzll** [RaiMan/SikuliX1#42]
https://github.com/RaiMan/SikuliX1/blob/911be91358592fa5b37c482fd5daefa41781edf9/API/src/main/java/org/sikuli/script/TextRecognizer.java#L144

should be: set psm instead of seting oem there.

**Comment by RaiMan** [comment]
Yep, thanks (copy&paste devil ;-)

**Comment by RaiMan** [comment]
fixed 2018-10-23
