### ISSUE TITLE
sikulixapi not clicking the identified  Pattern Object on MAC Book Pro.

### ISSUE THREAD

**Issue by abcdblr147** [RaiMan/SikuliX1#439]
Hi, i am facing issue with sikulixapi. it is not clicking on desired Pattern Object. 

System Details :

MAC Book Pro with  11.2.2 OS. 
JDK Version : java 11.0.10 2021-01-19 LTS
Display Resolution :  1792x1120 PPI

all the sikuli image files were resized to 72 PPI from 144 PPI.

pom.xml file:
------------

<dependencies>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.141.59</version>
		</dependency>
		
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.4.0</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>4.3.1</version>
		</dependency>
		
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>4.3.3</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			
			<version>2.0.5</version>
		</dependency>
</dependencies>

Code:
=====

public static void  attachImage() throws SikuliException {

		Screen s = new Screen();
		String dir = System.getProperty("user.dir");
		Pattern DirSearchImage = new Pattern(dir+"/Resources/DirSearchImage.png");

		if(s.exists(DirSearchImage) != null) {
			s.wait(DirSearchImage, 2);
			s.highlight();  ==> code is getting executed till here. 
			try { 
				s.click(DirSearchImage);  ==> Mouse is moved to the targetted  Image Location to click, 
                                                                                     but not clicking.
				s.click();  ==> click is failing. 
			} catch ( SikuliException e) {
				System.out.println("sikuli Exception");
			}
		} else {
			System.out.println("Sikuli Object for Directory Search not Found");
		}

		Pattern FileImage = new Pattern(dir+"/Resources/AttachmentFileImage.png");
		if(s.exists(FileImage)!= null) {
			s.wait(FileImage, 2);
			s.highlight();
			s.click(FileImage,0);
		}
		Pattern OpenButtonImage = new Pattern(dir+"/Resources/OpenButtonImage.png");
		if(s.exists(OpenButtonImage)!=null) {
			s.wait(OpenButtonImage, 2);
			s.highlight();
			s.click(OpenButtonImage,0);
		}
		
	}

**Comment by RaiMan** [comment]
On Mac the first click into a not-active (not-foreground) window only activates the window, but does not click the target.
So it only moves the mouse to the target.
The second click should then do its work, but since it happens only some milliseconds after activating the window, it might not be accepted by the application, because the GUI is not yet ready.

So you either have to take care, that the app is in foreground before the first click, or you have to wait a bit after the activation click.

My version for above workflow:
```
        Screen s = new Screen();
	String dir = System.getProperty("user.dir");
	ImagePath.add(dir+"/Resources");
	if(s.exists("DirSearchImage") != null) {
            s.click(); // activates the Window
            s.wait(1.0);
            s.click(); // should click now
        } else {
           // did not work
           // should terminate here
       }
	if(s.exists("AttachmentFileImage")!= null) {
		s.getLastmatch().highlight(2); // should be made optional
		s.click();
	}
```

Another technique might be:
```
try {
    s.click(s.wait("firstImage", 5))
    s.click()
    s.click(s.wait("secondImage", 5))
    s.click(s.wait("thirdImage", 5))
} catch (Exception ex) {
    //handle problems here
}
```
