### ISSUE TITLE
[error] FileManager: writeStringToFile: did not work: /home/developer-sikulix/.Sikulix/SikulixStore/lastUsedJar.txt

### ISSUE THREAD

**Issue by Marietto2008** [RaiMan/SikuliX1#448]
'm tryng to display the GUI of sikulix using a docker container. Below you can see my Dockerfile :

FROM ubuntu:20.04
MAINTAINER Mario Zio "marietto2008@gmail.com"

RUN sed 's/main$/main universe/' -i /etc/apt/sources.list && \
    apt-get update && apt-get install -y software-properties-common default-jdk wget firefox && \
    apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

RUN wget https://launchpad.net/sikuli/sikulix/2.0.5/+download/sikulixide-2.0.5.jar -O /tmp/sikulix.jar -q && \
    chmod +x /tmp/sikulix.jar && \
    echo 'Installing sikulix' && \
    cp /tmp/sikulix.jar /usr/local/bin

RUN chmod +x /usr/local/bin/sikulix.jar && \
    mkdir -p /home/developer-sikulix && \
    echo "developer-sikulix:x:1000:1000:Developer-Sikulix,,,:/home/developer-sikulix:/bin/bash" >> /etc/passwd && \
    echo "developer-sikulix:x:1000:" >> /etc/group && \
    echo "developer-sikulix ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d && \
    chmod 0440 /etc/sudoers.d && \
    chown developer-sikulix:developer-sikulix -R /home/developer-sikulix

USER developer-sikulix
ENV HOME /home/developer-sikulix
WORKDIR /home/developer-sikulix
CMD java -jar /usr/local/bin/sikulix.jar

This is the script that should display the sikulix IDE :

docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
             sikuli/cont

The GUI of sikulix appears ,but I see this error : 

[error] FileManager: writeStringToFile: did not work: /home/developer-sikulix/.Sikulix/SikulixStore/lastUsedJar.txt
/home/developer-sikulix/.Sikulix/SikulixStore/lastUsedJar.txt (No such file or directory)

**Comment by RaiMan** [comment]
fixed in 2.0.6
