### ISSUE TITLE
Unable to open App with parameters

### ISSUE THREAD

**Issue by rajeshtaneja** [RaiMan/SikuliX1#45]
While opening app using App.open(), on 1.1.4 it fails with an error, "Windows cannot find C:\myapp.exe --config C:\myapp.conf --skip-splash". Make sure you typed the name correctly and try again.

It works fine on 1.1.2. If I don't pass config (No space in command) then it opens my app.

**Comment by RaiMan** [comment]
the relevant part from the docs:
https://sikulix-2014.readthedocs.io/en/latest/appclass.html#App.App

Optionally you might add parameters, that will be given to the application at time of open.

> 
```
There are 3 options:

- put the application string in apostrophes and the rest following 
   the second apostroph will be taken as parameter string
- put  –  (space 2 hyphens space) between the applications name or path (no apostrophes!) 
   and the parameter string.
- use setUsing() with an already existing application object (created before)
```

Had to be slightly changed with 1.1.4 due to other oddities.

**Comment by rajeshtaneja** [comment]
Thanks @RaiMan . That worked 👍
