### ISSUE TITLE
Can not display Tamil characters correctly on the UI.

### ISSUE THREAD

**Issue by fz0000** [RaiMan/SikuliX1#451]
I set the language to Tamil and set the region to India.
The app is launched in Tamil automatically, but the characters are displayed as "□".
See screenshot for details:
![image](https://user-images.githubusercontent.com/5061311/118249684-3c262300-b4d8-11eb-8317-91471cf0ef25.png)

Environment:
Win 10 x64
jdk 11

**Comment by RaiMan** [comment]
Sorry, but internationalization is far down on the prio list, it is not looked at since years and will only be revised towards end of this year earliest.

If it is urgent, then you have to step down into the sources.
