### ISSUE TITLE
FindFailed when using a desktop application

### ISSUE THREAD

**Issue by rafael-avantech** [RaiMan/SikuliX1#452]
Hello, I'm using Sikulix to automate a MFP scanner and to do some testing.
When I try to find the buttons pattern  to be clicked, the find always fail, below some of the settings that I have and the code I'm using:

JDK: 14.0.1
Sikuli API: 2.0.5 using Maven
SO: Windows 10 Pro 64bit

            `Screen screen = new Screen(0);
		
		Robot robot = null;
	    try {
	    	robot = new Robot();
	    	robot.delay(500);
	        robot.setAutoDelay(2);
	        robot.setAutoWaitForIdle(true);
		} catch (AWTException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
		
	    
	  	String path = "C:\\Program Files (x86)\\Canon Remote Operation Viewer 2.3\\viewer.exe";
	  	App.open(path);
	  	App.focus("Connect To", 0);
	  	
	  	try {		
	  		
	  		robot.keyPress(KeyEvent.VK_ENTER);
	        robot.keyRelease(KeyEvent.VK_ENTER);    
	        
	        Thread.sleep(4000);
	  		screen.type("12365"); 
	  		
	  		robot.keyPress(KeyEvent.VK_ENTER);
	        robot.keyRelease(KeyEvent.VK_ENTER);
	        
	        Thread.sleep(4000);
	        
	        App.focus("Canon Remote Operation Viewer 2.3 ", 0);
	        
	        
	        Pattern process = new Pattern("C:\\Users\\rafael\\eclipse-workspace\\MFP\\src\\resources\\process.jpg");
			
			
			screen.wait(process.similar((float) 0.80), 8).click();
	        
			
	        }catch(Exception ex)
	        {
	        	// TODO Auto-generated catch block
	        	ex.printStackTrace();	
	        	ex.getMessage();
		        
		        Toolkit toolkit = Toolkit.getDefaultToolkit();
			    Dimension screenSize = toolkit.getScreenSize();
			    
			    Rectangle screenRect = new Rectangle(screenSize);
				
			    
			    BufferedImage image = robot.createScreenCapture(screenRect);
			    ImageIO.write(image, "png", new File("C:\\Users\\rafael\\eclipse-workspace\\MFP\\Errors\\test.jpg"));
	        }`

![image](https://user-images.githubusercontent.com/68068466/120655511-0941d000-c483-11eb-88ea-67ad1db8b3d2.png)
I'm taking a screenshot if some error happens and I always can see the button that I want clearly visible on the screen.
![image](https://user-images.githubusercontent.com/68068466/120655831-59209700-c483-11eb-9fbe-403f5b79b8f6.png)
And that's the image I'm using for the click.

And the console gives me the following error:

[log]  TYPE "12365"
FindFailed: C:\Users\rafael\eclipse-workspace\MFP\src\resources\process.jpg: (285x236) in R[0,0 1536x864]@S(0)
  Line 2226, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:2226)
	at Login.<init>(Login.java:77)
	at Main.main(Main.java:13)
	
There's any way to make this work or If I'm missing something ? 
Thanks for the help.

**Comment by RaiMan** [comment]
The image (285x236) and its suggested target in the screenshot have different sizes (about 210x180), so it cannot be found.

**Comment by rafael-avantech** [comment]
Hello thanks for the reply, so my images should have a minimal of 210x180 size ? 
Tried with this size and still same problem.

**Comment by RaiMan** [comment]
This was only to tell you, that the images are different in size and hence cannot match.

The image to search for on the screen must have the same size as it is shown on the current screen. This usually is done by making the shots with the capture button in the IDE.

**Comment by rafael-avantech** [comment]
Thanks for the tip! Using the IDE capture tool is working fine instead of using the snipping tool.

**Comment by RaiMan** [comment]
all the best.
