### ISSUE TITLE
SikuliX IDE on macOS M1 - 2.0.6 snapshots available

### ISSUE THREAD

**Issue by leonstafford** [RaiMan/SikuliX1#459]
```
$ java -jar sikulixmac-2.1.0-20210523.145838-7.jar 
Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: /Users/leon/Library/Caches/JNA/temp/jna18013432991504759997.tmp: dlopen(/Users/leon/Library/Caches/JNA/temp/jna18013432991504759997.tmp, 1): no suitable image found.  Did find:
	/Users/leon/Library/Caches/JNA/temp/jna18013432991504759997.tmp: no matching architecture in universal wrapper
	/Users/leon/Library/Caches/JNA/temp/jna18013432991504759997.tmp: no matching architecture in universal wrapper
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1877)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:40)
	at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:36)
	at com.tulskiy.keymaster.osx.CarbonProvider$1.run(CarbonProvider.java:55)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

System info:

```
$ java --version
openjdk 17 2021-09-14
OpenJDK Runtime Environment Homebrew (build 17+0)
OpenJDK 64-Bit Server VM Homebrew (build 17+0, mixed mode)

$ brew list --versions opencv
opencv 4.5.2_4

$ brew list --versions tesseract
tesseract 4.1.1
```

Been years since I ran SikuliX and not experienced with Java.

What more info should I provide/things to try?

**Comment by RaiMan** [comment]
the 2.1.0 snapshot (branch master) is currently not useable generally.
The branch I am actually working on is release_2.0.x

On macOS with M1 none of the actual versions/packages are working in native M1 mode (due to the fact that opencv lib is x86-64 only).

Since yesterday I have an iMac M1 and will now prepare a 2.0.6-SNAPSHOT that works in this environment.

The actual stable version 2.0.5 works with support of Rosetta 2.

So stay tuned.

**Comment by leonstafford** [comment]
Awesome, thanks @RaiMan for everything you do / have been doing for so long!

**Comment by RaiMan** [comment]
Now I have a running IDE version for macOS M1:
- branch: release_2.0.6_macM1

It uses OpenCV 4.5.3 (java classes and amd64-dylib are bundled in the jar).

My M1 library setup is completely based on latest homebrew (/opt/homebrew setup for M1 machines).

If you install tesseract via this brew config, then SikuliX will auto-detect the amd64 libraries. This is currently the only option to use OCR.

I am working  with Java 11 and Java 17ea [from Azul](https://www.azul.com/downloads/?package=jdk#download-openjdk)

[Ready-to-use snapshot versions of the IDE directly from OSSRH](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.sikulix&a=sikulixidemacm1&v=2.0.6-SNAPSHOT&e=jar)

**Comment by leonstafford** [comment]
Many thanks, will try soon!

**Comment by rodfersou** [comment]
the IDE open, mouse move, but never click:

![image](https://user-images.githubusercontent.com/131209/126907697-fcae606d-e41d-4a2c-a47c-414fe85308e4.png)

```
[log] CLICK on L[99,252]@S(0) (636 msec)
[error] script [ test ] stopped with error in line 2
[error] java.lang.IllegalArgumentException ( java.lang.IllegalArgumentException: SikuliX: find, wait, exists: invalid parameter: R[75,335 63x34]@S(0) )
[error] --- Traceback --- error source first
line: module ( function ) statement 
68: Sikuli (  wait ) 	at org.sikuli.script.Element.getImageFromTarget(Element.java:385)
2: main (  <module> )     wait(Region(75,335,63,34))
[error] --- Traceback --- end --------------
```

**Comment by RaiMan** [comment]
Will check

**Comment by RaiMan** [comment]
@rodfersou 

supposing, you have your Mac ready according to 
https://github.com/RaiMan/SikuliX1/wiki/Allow-SikuliX-actions-on-macOS

then you have to know, that the first click outside the IDE only brings the window to front, that is hit by the click.
On macOS clicks only do what you want in active windows (frontmost, foreground, top-left buttons not greyed).

Since App.focus() does not work yet on M1, you have to follow the "search"-click (which only makes the window active) by a click(), that clicks the match from before.
now every "search"-click in same window will work instantly.
This works as long you are clicking in the same window.

**Comment by panadol007** [comment]
Hi All,

I've been stuck on getting the sikuli working on my M1 Mac since Jun21, can anyone create YouTube video guide on how to install it on M1 Mac?

**Comment by RaiMan** [comment]
@panadol007 
the available versions up to 2.0.5 do not work on macOS M1.

You might try with the snapshots of 2.0.6 ([see in the section](https://github.com/RaiMan/SikuliX1) `2.0.6 (branch release_2.0.x) preparing for release - snapshots available`) - but it is still work in progress.

**Comment by panadol007** [comment]
Hi @RaiMan , thank you so much for your revert. I've downloaded and tried run, and this is what I've gotten: 

java -jar sikulixidemacm1-2.0.6-20211110.180130-6.jar -v -c
[SXINFO] ***** show environment for 2.0.6-SNAPSHOT (202111101801)
[SXINFO] running as: /Users/markkhor/Development/Sikuli/M1/sikulixidemacm1-2.0.6-20211110.180130-6.jar (org.sikuli.ide.Sikulix)
[SXINFO] running on: macOS 12.0.1 (aarch64)
[SXINFO] running Java: Azul Systems, Inc. 16.0.2+7
[SXINFO] java.io.tmpdir: /var/folders/4w/5_83h6lx0y34pw5cx1r277wh0000gn/T
[SXINFO] app data folder: /Users/markkhor/Library/Application Support/Sikulix
[SXINFO] work dir: /Users/markkhor/Development/Sikuli/M1
[SXINFO] user.home: /Users/markkhor
[SXINFO] active locale: en_US
[SXINFO] ***** show environment end
[SXINFO] ARG_CONSOLE
[SXINFO] ARG_VERBOSE
[DEBUG STARTUP] IDE starting ( 0.1)
[debug] IDESupport: enter
[debug] Runner: added: PackedSikulix [skl] text/skl
[debug] Runner: added: Robot [robot] text/robot
[debug] Runner: added: SikulixExecutableJar [executablejar] text/jar
[debug] Runner: added: Text [txt] text/text
[debug] Runner: init: class org.sikuli.script.runners.AbstractLocalFileScriptRunner: warning: not possible
[debug] Runner: added: Sikulix [] directory/sikulix
[debug] Runner: added: NetworkRunner [] NET
[debug] Runner: added: AppleScript [scpt, scptd, applescript] text/applescript
[debug] Runner: added: Jython [py] text/jython
[debug] Runner: added: PackedSikulix [zip] application/zip
[debug] Runner: added: SikulixJar [jar] text/jar
[debug] IDESupport: added: Jython
[debug] IDESupport: added: Text
[debug] IDESupport: exit: defaultrunner: Jython (py)
[debug] IDE: IDE: starting GUI
[debug] HotkeyManager: add Capture Hotkey: ⌘+⇧ 2 (50, 5)
[debug] HotkeyManager: add Abort Hotkey: ⌘+⇧ C (67, 5)
[debug] IDE: Restore scripts from last session
[debug] IDE: Restore Sikuli script: /Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli
[debug] EditorPane: created 1637651599123
[debug] EditorPane: loadfile: /Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli
[debug] EditorPane: InitTab: (text/text)
[debug] SikuliEditorKit.read
[debug] ImagePath: new BundlePath: /Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli
[debug] EditorPane: setFiles: for: /Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli
[debug] Image: loaded: 1625840843355.png (file:/Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli/1625840843355.png)
[debug] Image: cached: 1625840843355.png (73 KB) (# 1 KB 73 -- 0 % of 64 MB)
[DEBUG STARTUP] IDE ready: on Java 16 ( 2.7 sec)
^C[SXDEBUG] ***** final cleanup at System.exit() *****


However, the IDE is not show after that, any advice?

**Comment by RaiMan** [comment]
Try this:
- delete `~/Library/Preferences/org.sikuli.script.plist`
- delete  `~/Library/Application Support/Sikulix`

To see the the hidden files/folders in the Finder press SHIFT-CMD. (SHIFT-CMD-Dot).

Then start again from command line.

Recommendation: upgrade to Java 17 (LTS version) and purge Java versions up to 16.

**Comment by panadol007** [comment]
Thanks @RaiMan !! 
Finally it's working, I followed all steps recommended but still same result. Until after I delete this project: 
/Users/markkhor/Development/Sikuli/M1/testing/M1.sikuli

Appreciated for your help!

**Comment by syly123** [comment]
There is an error in the message field: java.lang.NoSuchMethodError：accessibilityHitTest
every time I click IDE , the error line will increase.
And when I change the window size of the ide the error disappears strangely, but when I restart, I get the error again.
I looked https://github.com/openjdk/jdk/pull/5702
but still don't know how to fix it.
![image](https://user-images.githubusercontent.com/65237304/143481352-b96d343e-6857-41cd-b885-419d9185e30a.png)


and my terminal log: 

2021-11-26 01:55:58.927 java[5568:181733] Bad JNI lookup accessibilityHitTest
2021-11-26 01:55:58.929 java[5568:181733] (
	0   libawt_lwawt.dylib                  0x0000000102ebda98 -[JavaComponentAccessibility accessibilityHitTest:withEnv:] + 160
	1   libawt_lwawt.dylib                  0x0000000102e6e858 -[AWTView accessibilityHitTest:] + 180
	2   AppKit                              0x000000018dcaa3f0 -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 420
	3   AppKit                              0x000000018d8445f4 -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 288
	4   AppKit                              0x000000018d813da4 CopyElementAtPosition + 172
	5   HIServices                          0x000000018fe4456c _AXXMIGCopyElementAtPosition + 432
	6   HIServices                          0x000000018fe6681c _XCopyElementAtPosition + 336
	7   HIServices                          0x000000018fe23354 mshMIGPerform + 200
	8   CoreFoundation                      0x000000018abfdf28 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
	9   CoreFoundation                      0x000000018abfdde4 __CFRunLoopDoSource1 + 596
	10  CoreFoundation                      0x000000018abfc264 __CFRunLoopRun + 2372
	11  CoreFoundation                      0x000000018abfb1a8 CFRunLoopRunSpecific + 600
	12  HIToolbox                           0x0000000192b20b40 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x0000000192b207cc ReceiveNextEventCommon + 320
	14  HIToolbox                           0x0000000192b20674 _BlockUntilNextEventMatchingListInModeWithFilter + 72
	15  AppKit                              0x000000018d3ed660 _DPSNextEvent + 836
	16  AppKit                              0x000000018d3ec000 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
	17  libosxapp.dylib                     0x0000000102f7025c -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 144
	18  AppKit                              0x000000018d3dde4c -[NSApplication run] + 596
	19  libosxapp.dylib                     0x0000000102f70018 +[NSApplicationAWT runAWTLoopWithApp:] + 208
	20  libawt_lwawt.dylib                  0x0000000102ec5d60 +[AWTStarter starter:headless:] + 488
	21  libosxapp.dylib                     0x0000000102f71c88 +[ThreadUtilities invokeBlockCopy:] + 28
	22  Foundation                          0x000000018b9c64e8 __NSThreadPerformPerform + 188
	23  CoreFoundation                      0x000000018abfd694 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	24  CoreFoundation                      0x000000018abfd5e0 __CFRunLoopDoSource0 + 208
	25  CoreFoundation                      0x000000018abfd2cc __CFRunLoopDoSources0 + 268
	26  CoreFoundation                      0x000000018abfbc54 __CFRunLoopRun + 820
	27  CoreFoundation                      0x000000018abfb1a8 CFRunLoopRunSpecific + 600
	28  libjli.dylib                        0x000000010263b374 CreateExecutionEnvironment + 400
	29  libjli.dylib                        0x00000001026378b0 JLI_Launch + 1148
	30  java                                0x000000010260bbb0 main + 396
	31  libdyld.dylib                       0x000000018ab1d430 start + 4
)
Exception in thread "AppKit Thread" ^C%                                         User@MacBook-Air ~ % java -jar /Applications/sikulixidemacm1-2.0.6-20211110.180130-6.jar
User@MacBook-Air ~ % java -jar /Applications/sikulixidemacm1-2.0.6-20211110.180130-6.jar
2021-11-26 01:57:01.804 java[5571:182400] Bad JNI lookup accessibilityHitTest
2021-11-26 01:57:01.807 java[5571:182400] (
	0   libawt_lwawt.dylib                  0x000000012a1b9a98 -[JavaComponentAccessibility accessibilityHitTest:withEnv:] + 160
	1   libawt_lwawt.dylib                  0x000000012a16a858 -[AWTView accessibilityHitTest:] + 180
	2   AppKit                              0x000000018dcaa3f0 -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 420
	3   AppKit                              0x000000018d8445f4 -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 288
	4   AppKit                              0x000000018d813da4 CopyElementAtPosition + 172
	5   HIServices                          0x000000018fe4456c _AXXMIGCopyElementAtPosition + 432
	6   HIServices                          0x000000018fe6681c _XCopyElementAtPosition + 336
	7   HIServices                          0x000000018fe23354 mshMIGPerform + 200
	8   CoreFoundation                      0x000000018abfdf28 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
	9   CoreFoundation                      0x000000018abfdde4 __CFRunLoopDoSource1 + 596
	10  CoreFoundation                      0x000000018abfc264 __CFRunLoopRun + 2372
	11  CoreFoundation                      0x000000018abfb1a8 CFRunLoopRunSpecific + 600
	12  HIToolbox                           0x0000000192b20b40 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x0000000192b207cc ReceiveNextEventCommon + 320
	14  HIToolbox                           0x0000000192b20674 _BlockUntilNextEventMatchingListInModeWithFilter + 72
	15  AppKit                              0x000000018d3ed660 _DPSNextEvent + 836
	16  AppKit                              0x000000018d3ec000 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
	17  libosxapp.dylib                     0x000000012a26c25c -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 144
	18  AppKit                              0x000000018d3dde4c -[NSApplication run] + 596
	19  libosxapp.dylib                     0x000000012a26c018 +[NSApplicationAWT runAWTLoopWithApp:] + 208
	20  libawt_lwawt.dylib                  0x000000012a1c1d60 +[AWTStarter starter:headless:] + 488
	21  libosxapp.dylib                     0x000000012a26dc88 +[ThreadUtilities invokeBlockCopy:] + 28
	22  Foundation                          0x000000018b9c64e8 __NSThreadPerformPerform + 188
	23  CoreFoundation                      0x000000018abfd694 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	24  CoreFoundation                      0x000000018abfd5e0 __CFRunLoopDoSource0 + 208
	25  CoreFoundation                      0x000000018abfd2cc __CFRunLoopDoSources0 + 268
	26  CoreFoundation                      0x000000018abfbc54 __CFRunLoopRun + 820
	27  CoreFoundation                      0x000000018abfb1a8 CFRunLoopRunSpecific + 600
	28  libjli.dylib                        0x0000000102a07374 CreateExecutionEnvironment + 400
	29  libjli.dylib                        0x0000000102a038b0 JLI_Launch + 1148
	30  java                                0x00000001029dfbb0 main + 396
	31  libdyld.dylib                       0x000000018ab1d430 start + 4
)
Exception in thread "AppKit Thread"

**Comment by RaiMan** [comment]
@syly123 
tested on my iMac M1 macOs 12 Java 17 in Terminal with actual snapshot:
`java -jar /Users/raimundhocke/Downloads/sikulixidemacm1-2.0.6-20211110.180130-6.jar -v -c`

script:
```
popup("test")
click()
```

... and had no problems.

I have the Terminal app activated in the relevant security options in SystemPrefs.

**Comment by syly123** [comment]
maybe my pc problem,thank you @RaiMan 
and there are  problem with popup&input.
Popup window is not automatically focused after input () is executed. So you have to click it manually. However, after clicking manually, you will not be able to enter in the input field.

1.Run sikulix (focus:sikulix)
2.click chrome by sikulix(focus chrome)
3.popup window appear(forcus chrome) 
4.click the popup manually to focus on it(focus popup window)
<<<CANNOT  input!!>>>>

1.Run sikulix (focus:sikulix)
2.click chrome manually(focus chrome) <--!! this is different from above
3.popup window appear(forcus chrome)
4.click the popup manually to focus on it(focus popup window)
<<<in this case, I CAN input!!>>>>

so why this happen?

(string "number" is default ,after focus manually ,I click it many times but won't able to input any number)
![image](https://user-images.githubusercontent.com/65237304/143666210-c6217d61-67c2-47d0-9a2f-2fe25162eace.png)

**Comment by RaiMan** [comment]
It is not really clear, what you are doing and about what popups (SikuliX or Chrome) you are talking.

Please paste the script code here (no screenshots of the IDE please! just the text).

On macOS generally any dialogs created from within a SikuliX script steal the focus and switch it to SikuliX. After having closed the dialog, the focus does not go back automatically to where it was before (Chrome in your case).

Currently the App features have still problems on macOS M1. So you have to click once into the target app window (Chrome in your case) afterwards to give the focus back to Chrome.

It is on the list, to give back focus to where it was before when using the SikuliX created dialogs (popup, input, ...).

**Comment by RaiMan** [comment]
@syly123 
Just made some tests again.

If you use once at the beginning of the script:
`app = App("'Google Chrome'")` (watch the inner apostrophes!)

then you can later use `app.focus()`to give focus back to Chrome in case.

**Comment by syly123** [comment]
```sikuli
# after run (Cmd + R) sikuliX, focus is on sikulix.

#click chrome to focus on it
click (Location(610, 51))

sleep(0.5)

# this will not steal the focus from chrome, still focus on chrome.
result = input("please input your number") 

# try to click inputWindow to focus on sikulix,
# but this will not be done because this code will done after I input something and
# give vlue to "result"
click(Location(742, 482))

# so I click the areas of sikulix input window other than it's title bar manually ... 
# then focus is on siklix input window , but I cannot input anything.
# and if I click chrome manually, and after that click inputWindow manually,
# or, If I click titlebar of inputWindow,
# then I am able to input number!

# summary
# 1:input() will not steal the focus from chrome
# 2:so I have to manually click on the title bar of the input window 
#   or manually click on chrome and then click on the input window.

```
and app = App("'Google Chrome'") is working correctly ~

**Comment by RaiMan** [comment]
@syly123 
Thanks for this optimal input.

I can confirm, that you are right:
If by whatever reason the focus is on another app than SikuliX at the moment the input dialog comes up, the dialog does not get the focus. One has to manually activate the focus to be able to act on the dialog.

IMHO: this is a change of behaviour compared with previous versions of macOS (I am rather sure it worked at least on macOS 10). On Windows it still works as expected. 

I accept this as a bug now (will create issue) with no commitment when it might be solved.

But still in no case the focus goes back to the app that had it before.

**Comment by syly123** [comment]
@RaiMan 
There is one more thing I don't understand
```
# /Users/User/sikuliX/sub.sikuli

from sikuli import *
def focusChrome():
    doubleClick(Location(714, 503))
    print("focused")
    sleep(0.3)

```
```
# /Users/User/sikuliX/import_test.sikuli

import sub
sub.focusChrome()

```
and when Run import_test.sikuli , I got error on sikuliX IDE's [message]:
```
[error] script [ import_test ] stopped with error in line 2
[error] NameError ( global name 'doubleClick' is not defined )
[error] --- Traceback --- error source first
line: module ( function ) statement 
4: sub (  focusChrome )     doubleClick(Location(714, 503))
2: main (  <module> )     sub.focusChrome()
[error] --- Traceback --- end --------------
```
I don't know what's wrong with my code....

**Comment by RaiMan** [comment]
@syly123 
Nothing is wrong - it is a bug. Not special for macOS M1.
I am sorry, no easy workaround for now.

A possibility:
```
s = Screen() # once at the beginning
s.doubleClick(...) # later
```

A request for the future: please post a separate new issue for new things. It is easier for me to track.
This time I will do it.

**Comment by syly123** [comment]
@RaiMan 
Thank you for your quick response!
I will be careful from the next time ~

**Comment by RaiMan** [comment]
OK: https://github.com/RaiMan/SikuliX1/issues/497

**Comment by fmm124** [comment]
First of all, I would like to thak RaiMan for having depeloped Sikulix. I have been using it (and still I do) for years.

But the nightmare began with my new 2021 M1 chip MacBookPro.

I have read almost all the posts related to the issue. So in a terminal, I write:

java -jar /Users/mfm/Downloads/sikulixidemacm1-2.0.6-20220409.135403-15.jar -v -c

Though Sikulix get started I think that my mouse is still blocked. In fact, in the terminal I read:

[SXLOG 0,688] [error] Start MouseDevice: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.set(boolean)" because "org.sikuli.script.support.devices.MouseDevice.useable" is null

so my code to be run in Sikulix still does not work.

Is there any comprehensible way to unlock the mouse?

Thank you very very much.

**Comment by shruti-s12** [comment]
> First of all, I would like to thank RaiMan for having depeloped Sikulix. I have been using it (and still I do) for years.
> 
> But the nightmare began with my new 2021 M1 chip MacBookPro.
> 
> I have read almost all the posts related to the issue. So in a terminal, I write:
> 
> java -jar /Users/mfm/Downloads/sikulixidemacm1-2.0.6-20220409.135403-15.jar -v -c
> 
> Though Sikulix get started I think that my mouse is still blocked. In fact, in the terminal I read:
> 
> [SXLOG 0,688] [error] Start MouseDevice: Cannot invoke "java.util.concurrent.atomic.AtomicBoolean.set(boolean)" because "org.sikuli.script.support.devices.MouseDevice.useable" is null
> 
> so my code to be run in Sikulix still does not work.
> 
> Is there any comprehensible way to unlock the mouse?
> 
> Thank you very very much.

Hi,
I am stuck at same issue
is your issue resolved?

**Comment by RaiMan** [comment]
@fmm124 
Make sure, that you have allowed screen capture and mouse usage on the target system:
https://github.com/RaiMan/SikuliX1/wiki/Allow-SikuliX-actions-on-macOS

**Comment by clemcoop** [comment]
I've been trying to run sikuli for weeks on my Mac M1 without any success. I'm pretty young to this kind of things and I can't figure out what the problem is... Here's what I get when trying to launch sikuli from the terminal. Thanks in advance for any help :) .
<img width="553" alt="Capture d’écran 2023-02-22 à 14 35 59" src="https://user-images.githubusercontent.com/126083137/220637828-a136eb3f-ddac-45f7-a4f4-72fbe2a26900.png">

**Comment by RaiMan** [comment]
@clemcoop 
what does it mean: `<>/...` ???

**Comment by RaiMan** [comment]
@fmm124 
You are not using the latest snapshot.
should read: `sikulixidemacm1-2.0.6-202208 ... -16.jar`

**Comment by RaiMan** [comment]
@clemcoop 
Thanks for feedback.
You should not put the sikulix....jar into the `Applications` folder (it is not an application in the macOS's sense).
Instead in your home folder create a folder SikuliX and then use
`~/SikuliX/sikulixidemacm......jar`

To reference something on `Desktop` in Terminal: `~/Desktop/myfile.txt`

**Comment by ItayMokarya** [comment]
hi I have a question the 2.0.5 version is work on java 11?
