### ISSUE TITLE
Finder with Image in Image throws NPE on next()

### ISSUE THREAD

**Issue by eitzenbe** [RaiMan/SikuliX1#46]
Below is the example code. Problem is in Finder.java 484 where _region gets added alas is NULL
I suspect the next() method would need some overhaul regarding the optional private fields.
In my scenario there would be also no parentScreen so line 491 would be also problematic I assume...

```
BufferedImage img = .......
 BufferedImage screenshot = .......

    org.sikuli.script.Image i = new org.sikuli.script.Image(screenshot);
    Finder finder = new Finder(img);
    finder.find(i);
    while (finder.hasNext()) {
      try {
        Match m = finder.next(); // PENG here comes the NPE
        System.out.println("Score:"+ m.getScore());
        if (m.getScore() >= wantedScore) {
          return;
        }
      } catch (Exception e) {
        System.out.println("ERROR while retrieving matcher!");
        e.printStackTrace();
      }
    }
```
Happy for any suggestion son how to overcome ;) FWIW I am using it in combination with AssertJ's Swing module to do Java Swing GUI testing and am retrieving screenshots of the gui via AssertJ's ScreenshotTaker to be able to restrict it to specific components...
br
Thomas

**Comment by eitzenbe** [comment]
I cloned and modified it locally adding an "&& _region != null" to the if in Finder.java:483
works fine better approach however would be to allow setting the region to restrict looking up images in images with the finder but that doesnt seem to have been implemented or?

**Comment by RaiMan** [comment]
Thanks for finding and suggestion.
I will check and fix asap

**Comment by RaiMan** [comment]
--- NPE in Finder line 484
I revised using your suggestion.

--- parentscreen 
Right ;-) Moved the line 491 into the if-block before (makes only sense there)

your code:
```
    org.sikuli.script.Image i = new org.sikuli.script.Image(screenshot);
    Finder finder = new Finder(img);
    finder.find(i);
```
should be possible as:
```
    Finder finder = new Finder(img);
    finder.find(i);
```
I will add a` find()`, that accepts `BufferedImage`

Again thanks for the contribution.

A test is highly appreciated.
