### ISSUE TITLE
Query on Linux dependencies - in particular, the libopencv_java version supported

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#465]
Hi Raimund, a TagUI user is trying to use SikuliX on Linux. I'm still using SikuliX v1.1.4 that doesn't require [additional setup on macOS](https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-libraries-for-Tess4J-Tesseract-4-OCR). A user has some questions while following the [SikuliX OpenCV setup guide](https://sikulix-2014.readthedocs.io/en/latest/newslinux.html#getting-the-opencv-support-ready). Is it correct to say that SikuliX v1.1.4 does not work with the libopencv_java v4.2 already on his system, and user should build libopencv_java v3.2 from source?

Below are his inputs -

---

I tried to install libopencv3.2-java but got this:

Package libopencv3.2-java is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source. However the following packages replace it: libopencv4.2-java

So then I changed the version in the install to 4.2 but that package is already installed.

**Comment by RaiMan** [comment]
Will check.

**Comment by RaiMan** [comment]
With SikuliX 1.1.4 on Linux we look for a libopencv_java.so using Java::System.loadLibrary().

This expects the library or a link to the real stuff in the standard places, where native libs are loaded from  on this Linux.

1.1.4 is actually based on OpenCV 3.4.2, but might work with latest OpenCV libs as well (not tested).

In any case you need a symbolic link in the right place, that points to the real lib.

As an example on Ubuntu 20:
- a possible folder for the link: `/usr/lib/jni/`
- being in this folder create the symlink like this:
`sudo ln -s libopencv_javaxxx.so libopencv_java.so`
where  `libopencv_javaxxx.so` is the path to the real library location

If OpenCV 4.x is not useable with SikuliX 1.1.4, you have to build 3.4.x from the sources.
The symlink is needed in any case.

**Comment by kensoh** [comment]
Thanks Raimund, this is very helpful! I'll share your detailed guide with user.

I'll close the issue now because above contains all the info needed for user to advance in the setup.

**Comment by RaiMan** [comment]
@kensoh 

Thanks for feedback:

> Yes solution verified, reply from user -

> Hi Ken, creating the symlink for libopencv_java.so has resolved the problem, click is now working.
