### ISSUE TITLE
Query on getting confidence for OCR text, for example match.getText()

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#466]
Hi Raimund,

A very good day to you. From below link it looks like `match.getScore()` will return the confidence level of a search.

https://sikulix-2014.readthedocs.io/en/latest/textandocr.html#accuracy-of-text-recognition-confidence

Following that line, there is `match.getText()` performed using SikuliX's implementation of Tesseract OCR.

May I check with you if my understanding is correct that there isn't a confidence output that can be returned as part of `match.getText()`? For example, given an image and this function returns 'Hello World', is there existing functionality to know the confidence level of this OCR parsing result 'Hello World'?

```py
# for example, let's say I want to get the OCR text from a region
ocr_text = Region(region_origin_x,region_origin_y,region_width,region_height).text()

# is there a way to know the 'confidence level' of ocr_text returned?
```

Thanks in advance for your time! No urgency on this and the other recent issue I raised.

**Comment by RaiMan** [comment]
Sorry, but currently this is not a feature. 

I will check this with version 2.0.6.
Thanks for the pointer.

**Comment by kensoh** [comment]
Thanks Raimund!

This is not urgent and the usage scenario is this. For example a user opens a scanned PDF document.

If OCR is used to extract image input into text output, and a confidence level is available, user can decide in the automation logic whether to accept this operation and proceed if the level is sufficiently high. If the confidence level is too low, user can flag it out as an exception to be handled manually later.

**Comment by kensoh** [comment]
**_Yes solution verified, reply from user -_**

Hi Ken, creating the symlink for libopencv_java.so has resolved the problem, click is now working.

**Comment by RaiMan** [comment]
@kensoh: Thanks for feedback.
