### ISSUE TITLE
Mat <-> BufferedImage converters do not work for subimages of BufferedImages

### ISSUE THREAD

**Issue by eitzenbe** [RaiMan/SikuliX1#47]
Using BufferedImage.getSubimage(...) to limit the area for Finder does not work,
Using the converters (forth and backwards) on such images show that the original image gets distorted.

Workaround is to create a new BufferedImage of Type TYPE_INT_RGB with limiting width/height and drawing the large image onto that....

**Comment by RaiMan** [comment]
Thanks.
Will check and fix asap.

**Comment by RaiMan** [comment]
Ok, looked into the code and could not find any (obvious ;-) problem.

> Using the converters (forth and backwards)

What converters?

Could you please give me a code sample?

**Comment by eitzenbe** [comment]
See attached method. simply using getSubImage wont return success  even if image "img" clearly is contained in Component's screenie

Workaround is creating a new BufferedImage with smaller size and drawing the screenie onto it...

```
 protected boolean isImageInComponent(Component c, Rectangle region, BufferedImage img, double wantedScore) {
    BufferedImage screenshot = shooter.takeScreenshotOf(c);

    BufferedImage regionImg = new BufferedImage(region.width, region.height, BufferedImage.TYPE_INT_RGB);
    Graphics2D imageGraphics = regionImg.createGraphics();
    imageGraphics.drawImage(screenshot, -region.x, -region.y, null);

    //getSubimage(region.x, region.y, region.width, region.height); causes Mats conversion and comparison to fail

    int match_method = Imgproc.TM_SQDIFF;

    Mat scrMat = bufferedImageToMat(regionImg);
    Mat tokMat = bufferedImageToMat(img);


    BufferedImage bscreen = Finder2.getBufferedImage(scrMat);
    BufferedImage btoken = Finder2.getBufferedImage(tokMat);

    // / Create the result matrix
    int result_cols = scrMat.cols() - tokMat.cols() + 1;
    int result_rows = scrMat.rows() - tokMat.rows() + 1;
    Mat result = new Mat(result_rows, result_cols, CvType.CV_32FC1);

    // / Do the Matching and Normalize
    Imgproc.matchTemplate(scrMat, tokMat, result, match_method);
    //Core.normalize(result, result, 0, 1, Core.NORM_MINMAX, -1, new Mat());

    // / Localizing the best match with minMaxLoc
    Core.MinMaxLocResult mmr = Core.minMaxLoc(result);

    Point matchLoc = mmr.minLoc;
    return (mmr.minVal < 10);
  }
```

**Comment by RaiMan** [comment]
> Mat scrMat = bufferedImageToMat(regionImg);

Cannot find this method in the 1.1.4 SikuliX.

> //getSubimage(region.x, region.y, region.width, region.height);

If this is a method from SikuliX, then the containing class must be a subclass of SikuliX Image.
If not, then where is it?

IMHO: Generally in the SikuliX code, BufferedImages are only read (even subimages). If a writable version is needed, then a new Buffered image is returned, which is created the way you said above.

So what has this to do with SikuliX?

**Comment by RaiMan** [comment]
ok, made some quick tests:
BufferedImage.getSubimage() objects apparently are not converted correctly to OpenCV Mat by the conversion method in Finder2. Might be a problem with the fact, that such a subimage is only a "pointer" to the same imagebuffer as the original.

I will check and fix it somehow.

Additionally it makes sense to generally allow the usage of BufferedImage objects all over the place for usages in Java.

**Comment by eitzenbe** [comment]
Excellent! Thanx a ton. I have a list of a few other issues, that might be worth discussing. Would you mind / have time for a chat or phone call? Topics are more complicated so doing it via voice would be more efficient me thinks ;)
br
Thomas

**Comment by RaiMan** [comment]
> Would you mind / have time for a chat or phone call?
Principally yes.
So let us first talk on that offline via mail: sikulix---at---outlook---dot--com

**Comment by RaiMan** [comment]
I decided to make a new branch as version 1.1.5.

From the ReadMe:

> Main intention is, to make the the base for image/text searching and OCR more general:

> Image should be an extension of a Region with the same features (except that it is not bound to a screen, but to some image content and you cannot click or type on it)

This in the end will make class Finder obsolete and allow to fully integrate BufferedImage as source (or other image sources).

So if you have any ideas for SikuliX:
- the master branch 1.1.4 is the place for minor revisions/fixes
- 1.1.5 is for really new features and major revisions (like the new Image implementation)

**Comment by RaiMan** [comment]
If still interested, get familiar with the new release situation and feel free to come back with issues.
