### ISSUE TITLE
mouse and keyboard

### ISSUE THREAD

**Issue by marcelocecin** [RaiMan/SikuliX1#471]
Hello
is it possible to send a mouse and keyboard command at the same time?
example: right click + alt ?
thanks

**Comment by marcelocecin** [comment]
I need to press Option key and click on the link at the same time to make Chrome downloads the target of the link
I tried this way, but it didn't work
```
mouseMove("target.png")
keyDown(Key.ALT)
mouseDown(Button.LEFT)
keyUp(Key.ALT)
mouseUp(Button.LEFT)
```

**Comment by RaiMan** [comment]
If you look, what you are doing manually, I guess it must be:

```
mouseMove("target.png")
keyDown(Key.ALT)
mouseDown(Button.RIGHT)
mouseUp()
keyUp()
```
or even:
```
find("target.png")
keyDown(Key.ALT)
rightClick() 
keyUp()
```

... I used `right` because initially you said `right click`

**Comment by marcelocecin** [comment]
ok it works !
thank you !
