### ISSUE TITLE
Unusual NullPointerException which can't be replicated elsewhere

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#475]
Hi Raimund, good day to you :)

Recently I have a user with a SikuliX error. I've asked him to try with the current version of SikuliX and the error happens as well. This error just started happening recently, and can't be replicated elsewhere. Thought to raise this here to see if you or other users have come across this problem, and whether there are actionable next steps for him to explore.

He followed the instructions to run SikuliX IDE (http://sikulix.com/quickstart) and got below error when starting IDE -

![error](https://user-images.githubusercontent.com/10379601/131238395-cbe495e7-d0d4-41b8-beb4-893586b22458.jpg)

**Comment by RaiMan** [comment]
should not happen in 2.0.6
