### ISSUE TITLE
Issue with some transparent image raising IllegalArgumentException

### ISSUE THREAD

**Issue by jNullj** [RaiMan/SikuliX1#481]
some transparent files (took screenshot using the ide then edited with gimp) raise [IllegalArgumentException ](https://docs.oracle.com/javase/10/docs/api/java/awt/Color.html#%3Cinit%3E(int,int,int,int))caliming alpha is out of range.

it claims the issue is here https://github.com/RaiMan/SikuliX1/blob/09cb0452f3c07137c5106a46c171270cef6722e9/IDE/src/main/java/org/sikuli/ide/PatternSimilaritySlider.java#L59

this is odd considering alpha seems to be bound to a value inside the 0-255 range.

sometimes editing a bit the same image solves this, sometimes it does not.
it appears to happend more with png that have alpha with semi-transparent areas. altho i confirmed the issue can also appear if alpha does not have semi-transparent areas.

running on:
os: archlinux
java: openjdk16 (also tested and had same issue with openjdk11)
sikulix: ide 2.0.5 (post march)

**Comment by RaiMan** [comment]
cannot be reproduced.

The mentioned code line is completely independent of the given image, only depends on the selected score.
