### ISSUE TITLE
Mac m1: AbortKey only runs on first invocation

### ISSUE THREAD

**Issue by ewalti** [RaiMan/SikuliX1#483]
I'm running silkuliX 2.0.6 via sikulixidemacm1-2.0.6-20210708.153544-1.jar with azul JDK 17. 

When I do a fresh boot of a sikuli script via:

```
 java -jar sikulixidemacm1-2.0.6-20210708.153544-1.jar -v -c
```

then load my script and click run, the abort key cmd+shift+c only works on the first invocation:

```
[debug] IDE: AbortKey was pressed: aborting all running scripts
[debug] HotkeyManager: reset: removed all SikuliX hotkeys.
[debug] HotkeyController: stopping hotkey provider
```

if I then run my script again and try to `AbortKey`, nothing happens. I have to kill the java process and rerun it to be able to abort script execution again.

This happens regardless of loading and running a new script

**Comment by unsightedmetal6** [comment]
I am having this issue on Windows 10 as well. It is not exclusive to Mac.

**Comment by RaiMan** [comment]
Checked today with my local version of 2.0.6: works on Win and Mac.

I will publish new 2.0.6 snapshots the next days.
