### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by atinary-dpacheco** [RaiMan/SikuliX1#485]
Dear SikuliX community,

I am really interested in your project which looks great. This is a really open source good alternative to Windows power automate and others. The missing point I have is I do not find any roadmap for next features. For example, there is  a new LTS java version has been release about a month ago, is it included in the roadmap ?

Thanks a lot! 
Daniel

**Comment by RaiMan** [comment]
Development is done on Java 17.
Testing additionally on Java 11.
Java 8 no longer supported with 2.0.6+
