### ISSUE TITLE
Make message more informative: [error] ImagePath: find: not there: src/login.png

### ISSUE THREAD

**Issue by anhphan-cwvn** [RaiMan/SikuliX1#488]
MacOS: 11.5.2
Java: 11

This is my code:
```
package automation.tests.RemoteControl;

import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.sikuli.script.*;

public class Demo {
    @Test
    public void test() throws FindFailed, InterruptedException {
        System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/mac/chromedriver95");
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.google.com/");

        Screen s = new Screen();
        try{
            s.click("src/login.png");
        }
        catch(FindFailed e){
            e.printStackTrace();
        }

        Thread.sleep(50000);
    }
}

```

But output is:

> 
> Starting ChromeDriver 95.0.4638.54 (d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}) on port 37205
> Only local connections are allowed.
> Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
> ChromeDriver was started successfully.
> Nov 16, 2021 8:41:29 AM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C
> [error] ImagePath: find: not there: src/login.png
> FindFailed: src/login.png: (0x0) in R[0,0 1792x1120]@S(0)
>   Line 2226, in file Region.java
> 
> 	at org.sikuli.script.Region.wait(Region.java:2226)
> 	at org.sikuli.script.Region.wait(Region.java:2244)
> 	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3298)
> 	at org.sikuli.script.Region.click(Region.java:3916)
> 	at org.sikuli.script.Region.click(Region.java:3892)
> 	at automation.tests.RemoteControl.Demo.test(Demo.java:17)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
> 
> Process finished with exit code 130 (interrupted by signal 2: SIGINT)
> 

**Please tell me how to solve this problem?**
Note that: If I create a script via Sikuli IDE, it's work.

**Comment by RaiMan** [comment]
The image cannot be loaded from `<working-directory>/src/login.png`.

Correct the path spec or use `ImagePath.setBundlePath()`.

**Comment by anhphan-cwvn** [comment]
@RaiMan 
After using:
`System.getProperty("user.dir");`

To get the full path, this issue was solved. However, another issue happened:

> FindFailed: /Users/ap/Documents/Projects/src/test/java/bellFace/automation/ui/imageElement/extensionPageElements/login.png: (224x46) in R[0,0 1792x1120]@S(0)

I used CMD+SHIFT+4 to created the login.png, but SikuliX always failed to find that one.

**Comment by RaiMan** [comment]
Retina display? 
If yes: Images captured with macOS capture have double pixels in width and height.

Recommended: use the SikuliX IDE to capture the images or write your own capture tool using `Screen.userCapture()`. Java 11/17 knows, that it is a Retina display and internally adjusts the images automatically.

**Comment by anhphan-cwvn** [comment]
@RaiMan 

> Retina display?
> If yes: Images captured with macOS capture have double pixels in width and height.
Yes, it is!

So, If I capture an element by SikuliX IDE on Retina, then run that script on MacOS 10.X.X
Will it work?

(I guess it will not work due to different resolution)
