### ISSUE TITLE
Email note to you - feel free to close this issue

### ISSUE THREAD

**Issue by kensoh** [RaiMan/SikuliX1#489]
Hi @RaiMan, good day to you. I've emailed you from my @tebel.org email and wanted to send a notification to you so that you know that the email is from me. I'm Ken who created the [TagUI open-source RPA tool](https://github.com/kelaberetiv/TagUI) and [RPA for Python](https://github.com/tebelorg/RPA-Python) automation tool. Both relies on SikuliX to handle the computer vision, OCR, OS-level keyboard and mouse automation.

**Comment by RaiMan** [comment]
See my answer to the mentioned mail. I take this issue as spam.
