### ISSUE TITLE
How to disable "This Safari window is remotely controlled by an automated test"

### ISSUE THREAD

**Issue by anhphan-cwvn** [RaiMan/SikuliX1#490]
MacOS: 11.5.2
Selenium: 3.14.xx
SikuliX1: 2.0.5
Java: 11
Safari: 14.1.2

When using selenium to open a website on **SAFARI**, then I call the SikuliX script to click an element by Image.
But Safari always shows a popup:
`This Safari window is remotely controlled by an automated test`

**So, please show me how to solve this issue?**

Note that: I turned-on "Allow Remote Automation" on Develop tab in Safari

**Comment by RaiMan** [comment]
I guess you have to ask Apple ;-)

**Comment by anhphan-cwvn** [comment]
@RaiMan Thank you for your response. I just want to make sure this issue does not relate about Sikuli

**Comment by RaiMan** [comment]
@anhphan-cwvn It is surely related to SikuliX, since it uses programmatically created mouse/keyboard actions, which in turn reveal the macOS security-related popup. 
But how to avoid this popup, is related to macOS.
... you might try to watch out for the popup (observe) and click OK to get it closed ;-)

**Comment by anhphan-cwvn** [comment]
@RaiMan The automation is breaking down, so there is no any meaning when trying to do that.
Thanks for your advice! :)

**Comment by RaiMan** [comment]
@anhphan-cwvn I have written/sent this comment using a script and do not get the popup.
So exactly after what action does the popup come up?

**Comment by anhphan-cwvn** [comment]
@RaiMan 

> When using **Selenium** to open a website on Safari, then I call the SikuliX script to click an element by Image.
> But Safari always shows a popup:
> This Safari window is remotely controlled by an automated test

The popup always comes up like that way.

**Comment by RaiMan** [comment]
As far as I know, then it is possible to click web elements with Selenium also.
What happens then?

You might try to load the webpage in Safari with the features of SikuliX. What happens then, when you click the image?

Why do you need Selenium?

**Comment by anhphan-cwvn** [comment]
Selenium is easy to find web element, I need Sikuli for some special moment, such as: find image, click an element in image.

Sikuli works fine with Chrome, Firefox... but not in Safari. The warning popup always shows when Sikuli has trying to click somewhere in Safari.

**Comment by RaiMan** [comment]
ok, it is cause by using Selenium with Safari:
https://qavalidation.com/2021/05/configure-safari-browser-to-run-selenium-tests.html/

**Comment by anhphan-cwvn** [comment]
@RaiMan 

> ok, it is cause by using Selenium with Safari:
> https://qavalidation.com/2021/05/configure-safari-browser-to-run-selenium-tests.html/

Sorry but I did it before reporting this issue:

> Note that: I turned-on "Allow Remote Automation" on Develop tab in Safari

**Comment by RaiMan** [comment]
Please read down the post, there is a soplution !

**Comment by anhphan-cwvn** [comment]
@RaiMan As I told you, It did not work!

**Comment by RaiMan** [comment]
@anhphan-cwvn 
Ok, but your second last reply did not really say, that you have also tried the 
`sudo /usr/bin/safaridriver --enable`.

... but then I have to leave you alone with that problem.
I wish you all the best to finally find a solution.

**Comment by anhphan-cwvn** [comment]
@RaiMan

> Ok, but your second last reply did not really say, that you have also tried the
> sudo /usr/bin/safaridriver --enable.

I tried that solution before logging this ticket.

Anyway, thanks for your supporting!
