### ISSUE TITLE
How to use this with Ruby

### ISSUE THREAD

**Issue by tkblackbelt** [RaiMan/SikuliX1#491]
Hello,

Just wondering if there's any documentation on using this with JRuby? Been looking around and I'm not really sure how to even start using this. I got the IDE running fine, but want to use JRuby.

Thanks!

**Comment by PfrLisBerndt** [comment]
I´m sure there several approaches, but my way using Sikulix in Jruby is that:

1. Add the sikulixapi.jar to your project
2. Your rubyfile should call "require 'java'" and "require_relative 'sikulixapi.jar'"
3. Import classes: e.g. 	IMAGE_PATH    = JavaUtilities.get_proxy_class('org.sikuli.script.ImagePath')

**Comment by tkblackbelt** [comment]
Thank you! This worked perfectly :). First time using JRuby, so was a bit confused on what I needed to do.
