### ISSUE TITLE
sikulixapi 2.0.5 package size question

### ISSUE THREAD

**Issue by rainmanwy** [RaiMan/SikuliX1#495]
Hi, RaiMan

Nice to see you again:-)

Recently i upgraded sikulixapi from 2.0.4 to 2.0.5 in my project.
And i found the size of jar with dependency changed from 70M to 150M.

As you know, i want to upload the python wheel package(with jar file) to pypi,
and pypi has upload limit [guidelines-for-upload-limit-requests](https://github.com/pypa/pypi-support#guidelines-for-upload-limit-requests)

do you have any suggestion about this?

**Comment by RaiMan** [comment]
The jar with dependencies (fat jar) contains the OpenCV libraries for Windows, macOS and Linux.

The only way to get the size down is to make special fat jars for only Windows, macOS or Linux (available for the IDE jars).

So you only have the choice to either make special packages for Windows, macOS and Linux or split the install procedure somehow based on the system type it is running on.

The mentioned IDE jars could be used as is in system specific packages as well.
