### ISSUE TITLE
Mouse not useable (blocked) on Ubuntu 20.40

### ISSUE THREAD

**Issue by titusfx** [RaiMan/SikuliX1#498]
When I use `mouseDown(Button.LEFT)` this error appears on the terminal `Mouse not useable (blocked)`

**Comment by jNullj** [comment]
Having the same issue with hover (but not click).

using this simple script
`hover(SCREEN.getBottomRight())` im getting the following in log
```
[debug] Jython: SikulixForJython: init: success
[debug] Jython: sikuli: Sikuli: starting init
[debug] Jython: use as default region: R[0,0 1280x1024]@S(0)
[debug] Image: BufferedImage: (1280, 1024)
[debug] Jython: sikuli: Sikuli: ending init
[debug] Jython: use as default region: R[0,0 1280x1024]@S(0)
[debug] Image: BufferedImage: (1280, 1024)
[debug] Region: hover: L[1279,1023]@S(0)
[error] Mouse.move(): Mouse not useable (blocked)
[debug] RunTime:***** running cleanUp *****
```

im using arch, installed using the aur.
i can't find why it happends, sometimes it works. after changing from java17 to 11 it temporarily fixed it.

**Comment by RaiMan** [comment]
If the mouse moves, just ignore the message. It might be an internal timing problem (the reported final mouse position is some pixels away from the target, which leads to the message).
Will be handled differently in 2.0.6.
