### ISSUE TITLE
[error] script [ script name ] stopped with error at line --unknown-- [error] --UnKnown-- ( --UnKnown-- )

### ISSUE THREAD

**Issue by e1ghtSpace** [RaiMan/SikuliX1#499]
This bug is really giving me a hard time. It seems to be if I add too many variables or if statements or lines... some kind of limit I am hitting.
For some reason if I type things like:
```
if int(stiffnessPercentage) != 100:
    type(Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + "FFFRFS")
else:
    type(Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + "FFFFFF")
```

I get the crash. However it no longer occurs if I rearrange the text like so:
```
type(Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE + Key.BACKSPACE)
if int(stiffnessPercentage) != 100:
    type("FFFRFS")
else:
    type("FFFFFF")
```

Another (even dumber example):
```
if (problemAmt == 1 or intnum == 15) and extnum != 15:
        extnum += 1
        endFrames[0] = kNm2Sec[kNm[extnum]]
        endFrames[1] = kNm2Sec[kNm[extnum]]
        logFile += "Upgrading End Frame Section Size\n"
```
This is fine but when I type this:
```
if (problemAmt == 1 or intnum == 15) and extnum != 15:
        if intnum == 15:
            logFile += "Mid Frame Section size already at max\n"
        extnum += 1
        endFrames[0] = kNm2Sec[kNm[extnum]]
        endFrames[1] = kNm2Sec[kNm[extnum]]
        logFile += "Upgrading End Frame Section Size\n"
```
I get the error.

Theres over 2000 lines of code in this program so I feel there may be some limit I am hitting that needs to be increased.

Error:
```
[error] script [ <script_name> ] stopped with error at line --unknown--
[error] --UnKnown-- ( --UnKnown-- )
```

**Comment by RaiMan** [comment]
There is a 64KB limit to script content (compiled script) in Jython, which is fix and cannot be changed.
With 2000 lines of code you are surely in this range. 

Just put some parts of your script as functions (def xxx(): ...) into other script files and use the import feature.

**Comment by e1ghtSpace** [comment]
Thanks. I have found that the script parts can be put into functions in the same file, with no need to import from another file.

**Comment by RaiMan** [comment]
Interesting ;-) Thanks.
