### ISSUE TITLE
[NotAnIssue] SikuliX @ chocolatey

### ISSUE THREAD

**Issue by sinbrkatetete** [RaiMan/SikuliX1#5]
Hi!

If it's not too much trouble for you, could you please update the chocolatey package? If possible, maybe somehow make it autoupdate?

Thanks for this great tool!

**Comment by RaiMan** [comment]
Can you guide me? I have no idea how to do that.
I know, I have taken over the responsibility some years ago, but did not do anything since then.

If it might be better, to make a new package - just tell me.

**Comment by RaiMan** [comment]
Just checked: I can still log in ;-)
I will have a look at it.

... but I hate to be forced to do the stuff on Windows - brrrrr

**Comment by sinbrkatetete** [comment]
Sorry for not getting back earlier... and sorry for being a total layperson and unfortunately not being able to help you with choco. If it's too much trouble for you, please don't do it. Since I didn't contribute anything to your work (lack of any knowledge in programing being the sole reason) nor did anything to help you in any other way and, on the other hand, your work has saved me countless hours of entering data into stupidly designed web forms to help my girlfriend and friends, I really don't feel comfortable asking/expecting anything more from you. 

However you choose to proceed on choco front, please receive my sincere thanks for sharing your work with the world and saving all those valuable percentages of lifetimes.

Thanks and live long and prosper.

**Comment by RaiMan** [comment]
@sinbrkatetete 
Great thanks for kind feedback.

I actually had a look into it and decided to do nothing.

reason: this choco package does nothing else than just execute sikulixsetup....jar. So I do not see the advantage over just downloading the jar and double click it.

**Comment by sinbrkatetete** [comment]
The only advantage I get from chocolatey in contrast todownload/doubleclick is - I just hit cmd and type "choco upgrade all -y" on all the computers I own and/or take care of for friends and family and all's done 😀 

Thanks! See you around.

**Comment by sinbrkatetete** [comment]
totally understandable. the low priority of it, that is. on a side note, if i ever find the time to learn about chocolatey packaging system, would you be open to sharin the maintainer position there?

**Comment by RaiMan** [comment]
anyone's help is always welcome - especially for things that I want to handle with low priority for whatever reason ;-)
