### ISSUE TITLE
Does it support arm？--- Principally yes --- not tested

### ISSUE THREAD

**Issue by LbBob** [RaiMan/SikuliX1#504]
Does it support arm？

**Comment by RaiMan** [comment]
**..... Warning! ..... Joke :-))**

No, you need your hands with your fingers until a script is running (on mouse and keyboard).

When a script is running successfully, you can sit back, fold your arms and watch the automation.

**..... end of joke .....**

What system are you talking about?

**Comment by bitcoinmeetups** [comment]
I second this, I want SikuliX on ARM in general and Raspberry Pi 4 in particular.

**Comment by RaiMan** [comment]
Since the Java environment is available for arm-arch, SikuliX should principally work on such systems running some Linux.
See: https://adoptium.net/de/temurin/releases/

The challenge: the native libraries for OpenCV and Tesseract must be available.

I do not plan to have a suitable environment.
Hence feedback on tests are welcome (preferably with version 2.0.6+) and requests are accepted.

**Comment by misterjame** [comment]
# Running Sikuli 1.0.5 on Ubuntu 22 desktop inside VMware Fusion 13 on an M1 Mac

These instructions will help you run Sikuli 1.0.5 stable on Ubuntu 22 desktop inside VMware Fusion 13 on an M1 Mac.

## Prerequisites

- Ubuntu 22 desktop installed inside VMware Fusion 13 on an M1 Mac.

## Installation

1. Open the terminal and update the package list by running the command `sudo apt update`.

2. Install OpenJDK 11 JDK by running the command `sudo apt install openjdk-11-jdk`.

3. Install the required Java bindings for OpenCV by running the command `sudo apt install libopencv4.5-java`.

4. Disable Wayland to prevent a black screen issue while running Sikuli. Open the custom.conf file in the GDM3 configuration directory by running the command `sudo gedit /etc/gdm3/custom.conf`. Uncomment the line `WaylandEnable=false` and save the file.

5. Restart the GDM3 service by running the command `sudo systemctl restart gdm3.service`.

6. Run Sikuli at least once and note any errors that occur.

7. Find the required .so libraries for OpenCV and other dependencies used by Sikuli. These libraries are typically located in the `/usr/lib/` directory.

8. Copy the required .so libraries to the `SikulixLibs` directory located at `/home/me/.Sikulix/SikulixLibs`.

9. Rename the copied libraries to match the names of the original x64 .so files in the `SikulixLibs` directory. Sikuli expects the libraries to have the same names as the original x64 .so files.
