### ISSUE TITLE
Windows image element is not detected in 2.0.6 (branch release_2.0.x) 

### ISSUE THREAD

**Issue by YogeshPatelTR** [RaiMan/SikuliX1#506]
In v2.0.6 (release_2_0_x branch), When we try to find any element in windows, it does not find that element with OpenJDK11.

Same code works fine with v2.0.5 and JDK1.8

**Sample Code**
 screen = new Screen();
        try {
            screen.find(image);
            status = true;
        } catch (FindFailed e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

**Error logs:**

  Line 2315, in file Region.java
	at org.sikuli.script.Region.find(Region.java:2315)

**Comment by YogeshPatelTR** [comment]
Thank you @RaiMan  for your quick response. But it still not working for me. Below are some extra information which might help you to detect the problem

**Branch:** release_2_0_x
**Java:** OpenJDK11
**Other Project:** sikulix2opencv GitHub Project (I am not using openCV lib but using sikulix2opencv GitHub Project)
**Operating System:** Windows 10

**Below is source code**

```
	public static void main(String[] args) {
        Screen screen = new Screen();
        try {
    		Pattern wordIcon = new Pattern(new File("D:\\Mailing.PNG").getCanonicalPath().trim());
        	 File images = new File("D:\\images");
             ImagePath.setBundleFolder(images);
             String winimg = "Mailing_Page.PNG";
             screen.userCapture().saveInBundle(winimg);
             Match match = screen.find(wordIcon);
             screen.hover(screen.getLastMatch());
             System.out.println(String.format("%s", match));
        } catch (Exception e) {
            e.printStackTrace();
        }

```
**It shows below error message**:```

FindFailed: D:\Mailing.PNG: (90x32) in R[0,0 1536x864]@S(0)
  Line 2315, in file Region.java
	at org.sikuli.script.Region.find(Region.java:2315)
	at Main.main(Main.java:18)

```

Attaching the images as well. 

[](url
![Mailing_Page PNG](https://user-images.githubusercontent.com/90629020/149448159-854ec18f-9c4d-48c0-b6ed-5a394507e27f.png)
![Mailing](https://user-images.githubusercontent.com/90629020/149448164-4414f472-316d-4c47-94a8-3ed6f59cf930.PNG)
)

**Comment by RaiMan** [comment]
Attaching the images as well. 

[](url
![Mailing_Page PNG](https://user-images.githubusercontent.com/90629020/149448159-854ec18f-9c4d-48c0-b6ed-5a394507e27f.png)
![Mailing](https://user-images.githubusercontent.com/90629020/149448164-4414f472-316d-4c47-94a8-3ed6f59cf930.PNG)
)

**Comment by RaiMan** [comment]
Attaching the images as well. 

![Mailing_Page PNG](https://user-images.githubusercontent.com/90629020/149448159-854ec18f-9c4d-48c0-b6ed-5a394507e27f.png)
![Mailing](https://user-images.githubusercontent.com/90629020/149448164-4414f472-316d-4c47-94a8-3ed6f59cf930.PNG)

**Comment by RaiMan** [comment]
Not exactly, what I proposed.

So again:

```
         File images = new File("D:\\images");
         ImagePath.setBundleFolder(images);
         Screen scr = new Screen();
         String winimg = "_mailing.png"; // the underscore is a must!
         //now you have to capture the menu word `Mailings`
         //so it is finally used in the find
         scr.userCapture().saveInBundle(winimg);
         try {
           Match match = scr.find(winimg);
           scr.hover(scr.getLastMatch());
           System.out.println(String.format("%s", match));
         } catch (FindFailed e) {
           System.out.println("not found");
         }
         new File(images, winimg).delete();
```

**Comment by YogeshPatelTR** [comment]
Thanks @RaiMan 

Actually, I was capturing separately through tool instead cropping from captured image.

Now, its done

Thank you for your help and prompt replies
