### ISSUE TITLE
FindFailed on pattern in Windows Remote Desktop session - Shows up with "Matching Preview" tool

### ISSUE THREAD

**Issue by robot-army** [RaiMan/SikuliX1#508]
Hi, 

I'm running sikulix 2.0.5 on my local machine, and trying to automate a process in some label making software on a remote machine. 

I've successfully taken a screengrab of the region I want to click on the remote machine, and the region is highlighted in the "Matching Preview" tool when I click on the pattern in the IDE. 

When I run the script, it fails to find the match, and therefore crashes out. 

See screenshots attached. 

Any tips? 

![image](https://user-images.githubusercontent.com/4554056/151459352-473710fd-1fae-4814-bf50-175f4d70854f.png)

![image](https://user-images.githubusercontent.com/4554056/151459535-1ad0b77e-a49f-4f26-8097-a82bcfdf1ab5.png)

**Comment by RaiMan** [comment]
A similarity of 0.23 is a very bad value.
Patterns should be found with scores of at least 0.8 to 0.9, to make the find op robust.

The best recommendation is to restrict the shot to what you really want to click and what is found with a high score in all possible situations. Leave out as much background as possible, that might change from run to run.

**Comment by robot-army** [comment]
Thanks, I understand all that, it matched to a very high value. I changed
that score in an attempt to see if that was the problem, it wasn't.

I'll take some more screenshots demonstrating the same later today.
