### ISSUE TITLE
Java 17 compatibility

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [RaiMan/SikuliX1#509]
If this version of Java (Java >= 15) is detected, then NashornEngine shouldn't be tried to use.
Java 17 LTS is nowadays the stable release.

**Comment by RaiMan** [comment]
In what version did you see that?

IMHO Nashorn is no longer used in 2.0.5+

**Comment by DavidPerezIngeniero** [comment]
When trying SikuliX 2.0.5 with Java 17.
I will repeat my test....
