### ISSUE TITLE
[1.1.4] exit status of script not passed to the shell executing java --- fixed 2019-01-30

### ISSUE THREAD

**Issue by romangrothausmann** [RaiMan/SikuliX1#51]
Using SikuliX (1.1.4) inside a docker image (https://gitlab.com/romangrothausmann/dind-sikuli) for automated fog testing in GitLab CI (many thanks for Sikuli and its maintenance, it's just amazing what can be done with it!), I noticed that when executing a script with `java -jar /opt/sikulix.jar -r test.script/` the exit code that the shell receives (e.g. `echo $?` is not correlating to the exit code of the script. For example if the script has an `exit(10)` the log says: `[info] Exit code: 10` but a following `echo $?` reports `0`. I found a few related issues on this from old:
https://answers.launchpad.net/sikuli/+question/193835
https://answers.launchpad.net/sikuli/+question/203783
https://github.com/sikuli/sikuli/issues/38
but none seems to give an answer how to pass on the exit status of a script to the shell executing java. I had a look at the source (https://github.com/RaiMan/SikuliX1/blob/98ac9872e6d186c699cebcef1dc44e72dc17f87a/IDE/src/main/java/org/sikuli/scriptrunner/ScriptingSupport.java#L448) but can't see where it gets lost.
The exit code to the shell is finally used by GL CI to determine if the job/test succeeded, so my current workaround is to grep the output from java for `[info] Exit code: 0` but in case of multiple return values that's not ideal.

Should a script be called differently for such cases or is there another way to pass on the exit code of the script to the shell?

**Comment by RaiMan** [comment]
1. thanks for feedback
2. understood - will try to fix it

**Comment by romangrothausmann** [comment]
Many thanks @RaiMan for your looking into this. Even though `java -jar /opt/sikulix.jar -r ` seems to be the general recommendation to run SikuliX scripts without GUI, I got what I needed by running jython and importing sikuli-jython conditionally (to preserve GUI portability for editing), i.e. in the sikuliy python script `sikuli-script.py` I added:

```
try:
    import org.sikuli.script.SikulixForJython
    from sikuli.Sikuli import *
except ImportError:
    print("No run by sikuli jython")
....
exit(X)
```

and call it for the headless tests with Xvfb as:
```
java -cp "/opt/sikulixapi.jar:/opt/jython-standalone-2.7.1.jar" org.python.util.jython sikuli-script.py
```

Then, the return code from java corresponds to that of `exit(X)` in the script

**Comment by RaiMan** [comment]
thanks for the workaround.

Be aware: With this variant, there is no default image path set. With the recommended way, the default image path is set to the bundle path (folder .sikuli containing the .py)

So I have to fix it anyways ;-)

**Comment by romangrothausmann** [comment]
Many thanks @RaiMan for that hint. I had been stuck on that, and found the following workaround:

```
try:
    import org.sikuli.script.SikulixForJython
    from sikuli.Sikuli import *
    import inspect
    import os.path
    addImagePath(os.path.dirname(os.path.abspath(inspect.getsourcefile(lambda:0))))
except ImportError:
    print("No run by sikuli jython")
```

**Comment by RaiMan** [comment]
ok, exam passed ;-)

BTW: this is sufficient:
```
    import org.sikuli.script.SikulixForJython
#    from sikuli.Sikuli import *
    from sikuli import *
# already imported
#    import inspect
#    import os.path
    addImagePath(os.path.dirname(os.path.abspath(inspect.getsourcefile(lambda:0))))
```

**Comment by balmma** [comment]
PR #74 might fix this one.

**Comment by RaiMan** [comment]
Please reopen, if the mentioned PR #74 did not solve your problem
