### ISSUE TITLE
[error] Mouse: not useable (blocked)

### ISSUE THREAD

**Issue by JustForLife** [RaiMan/SikuliX1#510]
OS:  macOS 12.1 (21C52)
JAVA version: 1.8.0_231

When I running in sikulixide-2.0.5-mac.jar, is all right
<img width="825" alt="image" src="https://user-images.githubusercontent.com/62697455/152903490-b64a75fd-bbe7-4e59-ba06-036f17dbb1d5.png">

But, When I running in IDEA, get error : Mouse: not useable (blocked)
<img width="757" alt="image" src="https://user-images.githubusercontent.com/62697455/152903617-d48f0a84-1f48-4798-96e0-0b5b0f94b058.png">

Then, I Use mvn package command to make jar and running in iterm,get error again
<img width="756" alt="image" src="https://user-images.githubusercontent.com/62697455/152903770-1c75008d-390a-471c-9015-6f85f533ef28.png">

This is my Config:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/62697455/152903859-ddd6a780-7106-4e56-91c5-181f81af57e9.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/62697455/152903884-964291c2-f4f6-427d-a8e7-7ed13bbd0835.png">

Can you help me?

**Comment by RaiMan** [comment]
tested on macOS 12.1 (should make no difference) using AdoptOpenJDK (1.8.0_322).

When running a test from within IDEA (2012.2.4 CE), then only the IDEA app has to be activated in the 2 settings.

When running stuff from a Terminal window (I do not have iTerm), then the Terminal app has to be activated in the 2 settings.

This works for me. I did not need the Java entries (this might only be needed, if you want to run a jar by double clicking).

In doubt yo have to remove all entries in the 2 settings and start again in the sequence IDEA, Terminal and then iTerm.

**Comment by JustForLife** [comment]
> tested on macOS 12.1 (should make no difference) using AdoptOpenJDK (1.8.0_322).
> 
> When running a test from within IDEA (2012.2.4 CE), then only the IDEA app has to be activated in the 2 settings.
> 
> When running stuff from a Terminal window (I do not have iTerm), then the Terminal app has to be activated in the 2 settings.
> 
> This works for me. I did not need the Java entries (this might only be needed, if you want to run a jar by double clicking).
> 
> In doubt yo have to remove all entries in the 2 settings and start again in the sequence IDEA, Terminal and then iTerm.

I remove all entries in the 2 settings, but when I start again in the IDEA, only IDEA app has to be activated in the 1 settings，It doesn't appear in the screen recording setting
<img width="609" alt="image" src="https://user-images.githubusercontent.com/62697455/153116493-b307941f-dc78-4b33-b83e-bbe74f37d832.png">

**Comment by JustForLife** [comment]
> > tested on macOS 12.1 (should make no difference) using AdoptOpenJDK (1.8.0_322).
> > When running a test from within IDEA (2012.2.4 CE), then only the IDEA app has to be activated in the 2 settings.
> > When running stuff from a Terminal window (I do not have iTerm), then the Terminal app has to be activated in the 2 settings.
> > This works for me. I did not need the Java entries (this might only be needed, if you want to run a jar by double clicking).
> > In doubt yo have to remove all entries in the 2 settings and start again in the sequence IDEA, Terminal and then iTerm.
> 
> I remove all entries in the 2 settings, but when I start again in the IDEA, only IDEA app has to be activated in the 1 settings，It doesn't appear in the screen recording setting <img alt="image" width="609" src="https://user-images.githubusercontent.com/62697455/153116493-b307941f-dc78-4b33-b83e-bbe74f37d832.png">

My POM file Config
`<dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.0.5</version>
        </dependency>`

**Comment by RaiMan** [comment]
> It doesn't appear in the screen recording setting 

You have to run a capture operation, to get macOS to add the entry.
... or do it manually.

**Comment by JustForLife** [comment]
> > It doesn't appear in the screen recording setting
> 
> You have to run a capture operation, to get macOS to add the entry. ... or do it manually.

I manually added IDEA APP to the screen recording
<img width="587" alt="image" src="https://user-images.githubusercontent.com/62697455/153327216-dc658f37-7b6b-41cc-9685-c7ca28975098.png">

and use code like this
`
Screen screen = new Screen();

        String path = System.getProperty("user.dir");
        String test = path + "/test.jpg";

        Pattern pattern = new Pattern(test);

        try {
            if (screen.find(pattern) != null) {
                screen.click(pattern);
            }
        }catch (Exception ex){
            System.out.println(ex.toString());
        }
`

Run the following error message：

Exception in thread "main" org.sikuli.script.SikuliXception: Mouse.init: Mouse not useable (blocked) - Screenshots might not work either!
	at org.sikuli.script.Screen.initScreens(Screen.java:184)
	at org.sikuli.script.Screen.<init>(Screen.java:198)
	at com.gykj.test.DesktopAppAutoTest.main(DesktopAppAutoTest.java:8)

**Comment by JustForLife** [comment]
> Sorry, no idea, what is wrong with your situation.
> 
> As mentioned above: It works on my side.

After I used sikulixapi version 2.0.4, everything was fine，Thanks。
