### ISSUE TITLE
Question: How can we convert SikuliX jar to an exe?

### ISSUE THREAD

**Issue by orrburgel** [RaiMan/SikuliX1#512]
Hello everyone!

Please read the question in the title, I will be glad to get any response, thanks!

I'm well aware of all the tools that lets you compile jar to exe but my questions are:

1) Will it work to compile the LTS of SikuliX to exe in theory?

2) Are you familier with any procedure to convert the sikulix jar to exe? I choose to not purchase jar2exe since it only supports up to java 14 and its really hard to find one that supports java 17

3) Can we convert the Jython package of Sikuli to exe using like pyinstaller or something with a lot more ease? Is it gonna be less feature rich or less good as SikuliX?

4) Are we legally allowed to redistribute commercially in some way Sikuli/X? (with all your licensees in our about us section) I mean the app itself is free to download and sikulix is free to use within it but completely other aspects of the software is selling something on the same app like in-app purchases

I think this can help not just me but everyone else :)

Included is some extra questions that I did not wanted to open a new issue about, so feel free to skip those: (or answer at a later time, thank you!)

1) Do you happen to know what is the performance difference between SikuliX running with Java 14/8/17? I read that Java17 is faster and therefor worth the upgrade and so im currently biased to find ways to make it all work on 17.

2) I use SikuliX all my life and I noticed over the years that some options within the GUI went missing on newer versions of sikulix, which I found weird at the time, and this kind of forced me to use an older version of sikulix to preserve that old school feeling and all the features I use to love about it, you know, all these buttons that lets you capture screen wait and etc, I'm would like to know if you know what I'm talking about and is it still the case on the LTS of SikuliX? (missing old school features)

3) I also noticed that by having a different version of java back in the days, a completely different GUI interface will open when you double click SikuliX (tested both v1xx and v2.0 I think it was at the time)
And my question is, is this something you are aware of? is it still the case with the LTS?

My ultimate goal and question is what is the best combo for using sikulix (; in terms of versions and etc..

**Comment by orrburgel** [comment]
Why you may ask? to make it so PCs will be able to run it without having the correct java version installed or java installed at all, it will be converted to byte code and therefor in theory will be using java 17 latest security updates and benefits

**Comment by RaiMan** [comment]
Ok, thanks for the questions. I'll try my very best ;-)

> Will it work to compile the LTS of SikuliX to exe in theory?
Are you familier with any procedure to convert the sikulix jar to exe?

Not only in theory, but in practice too :-)
The tool to use is jpackage which comes with the Java JDK (I think 11+).
It allows to create an installable package, that can be used like an exe and runs without the need to have Java installed.
In fact it contains everything needed including Java and hence is rather big (installed about 200 MB)
I have already tested the tool with success and will make installable packages available with the next 2.0.6 snapshot.
With 2.0.6+ they will be a standard offer besides the jar packages.

Another option would be to switch the dev base to Kotlin, which allows to create native code and hence to create exe files. I will have a look into it later this year.

> Can we convert the Jython package of Sikuli to exe ....

I do not really understand the question. 
If you mean to convert a Jython script to an exe: Yes this is principally possible, but you always need the complete package of SikuliX available - either standalone (see above) or bundled (which would mean for some 10-100 lines of script a package of 200MB - does not really makes sense). 

> Are we legally allowed to redistribute commercially ...

You can do with SikuliX whatever you want. I am happy, if you keep a reference to my work with your product.
For commercial use cases you have to be careful with some dependencies of SikuliX, that have licenses with special needs in this case. Use a license scan tool. [The licenses are listed here (API).](https://github.com/RaiMan/SikuliX1/tree/release_2.0.x/API/src/main/resources/Settings/LicenseAPI) and [here (IDE).](https://github.com/RaiMan/SikuliX1/tree/release_2.0.x/IDE/src/main/resources/Settings/LicenseIDE)

>Do you happen to know what is the performance difference ...

I have no idea. The speed and resource consumption of SikuliX depends only little on Java but on the performance of the image search based on OpenCV and the OCR feature based on Tesseract.
I generally recommend to use the latest Java LTS (currently either 11 or 17).
2.0.6 needs at least Java 11.

> ... some options within the GUI went missing on newer versions ...

I guess you are talking about the CommandBar left sided in the IDE window: yes it is removed and might come back later as an autocomplete feature. The rest is not fundamentally changed.

> ... a completely different GUI interface ...

not really. But the current GUI (2.0.5+) will be stable and get minor enhancements.

> My ultimate goal and question is what is the best combo for using sikulix ...

2.0.5 (or 2.0.6 snapshot and coming final) and Java 11 or Java 17

**Comment by orrburgel** [comment]
Epic! Wow! Thank you so much!
You helped a lot! <3 @RaiMan You the man
