### ISSUE TITLE
how to build it as ide?

### ISSUE THREAD

**Issue by kelisima001** [RaiMan/SikuliX1#513]
how to build it as ide?

**Comment by kelisima001** [comment]
build artifacts -> build -> java.lang.ClassNotFoundException: org.sikuli.ide.Sikulix
mvn clean && mvn package sikulixide-2.1.0-SNAPSHOT.jar no main

**Comment by RaiMan** [comment]
- the only useable version (`2.0.6-SNAPSHOT`) is in branch `release_2.0.x`.
- so you need `git` to switch to this branch before doing anything
- you need Java 11 or 17 and Maven 3
- use `mvn -P complete-xxx-jar clean install` (`xxx`: `win`, `mac`, `macm1`, `lux` is target system to build for)  
- you get a `...-complete-xxx.jar` in the `.../IDE/target` folder 
- rename it to whatever and move it to wherever you want

**macOS and Linux - OCR features:** you need a valid Tesseract 5.0.1 installation 
(test: `tesseract --version` command can be run from the command line)
On macOS use Homebrew to get things done
