### ISSUE TITLE
Cannot find any matches with different size screenshot

### ISSUE THREAD

**Issue by jnhyperion** [RaiMan/SikuliX1#519]
I captured a small image "bug_template.png" from 2560x1600 screenshot.
![bug_template](https://user-images.githubusercontent.com/20297196/160575900-87b8378a-9533-4fa6-9cd4-65c6d5409240.png)
I want to find this small image on a device with size 1920x1200("bug.png"), because we want to run our tests on different types of devices.
![bug](https://user-images.githubusercontent.com/20297196/160576438-2d3827f8-48ca-46b3-b28e-d62183e4f1e4.png)

But sikuli cannot find any matches, here's my code, it always returns null:

``` java
        Finder finder = new Finder("bug.png");
        finder.find("bug_template.png");
        Match match = finder.next();
        if (match != null) {
            System.out.println("Matched" + match.toString());
        } else {
            System.out.println("Not match");
        }

```

any ideas?

**Comment by RaiMan** [comment]
A basic requirement for image search in SikuliX (based on matchTemplate of OpenCV) is that the image to be searched for (bug_template) must have the same size in pixels as its possible match in the image to search in (bug).
In your case the Chrome icon is about 90x90 pixels, but in the screen image it is only about 70x70 pixels - hence it cannot be found.
This often happens, when images are shot on large monitors run with some scaling (e.g. 120%).

There are principally two solutions for such cases:
1. have an appropriate image set for every different screen setup
2. use SikuliX's resize option when the scaling factor is known and proportional in both directions.

One might use a series of test images, to evaluate the current screen situation.

... and it is recommended to use Java 11 or 17, where the handling of scaled monitors is much better supported.

**Comment by jnhyperion** [comment]
I tried [Feature Matching](https://docs.opencv.org/4.x/dc/dc3/tutorial_py_matcher.html) SIFT(Scale Invariant Feature Transform) could work in such kind of cases, but it's not so accurate sometimes.

Will you consider to add feature matching in sikuli?

**Comment by RaiMan** [comment]
Currently it is not on the plan to implement it. Completely different concept.

Do you have your test implementation on the Java level? Then I am interested to have a look at it.

**Comment by jnhyperion** [comment]
Unfortunately not, only some python code snippets from: https://docs.opencv.org/3.4/dc/dc3/tutorial_py_matcher.html

**Comment by RaiMan** [comment]
no problem. Thanks anyways for the reminder. I already looked at it some years ago ;-)
