### ISSUE TITLE
Java API: findLine failing to convert to Match type --- fixed 2018-11-24 build #131

### ISSUE THREAD

**Issue by FlamingGear** [RaiMan/SikuliX1#52]
Whilst trying to make use of the Region.findLine() method I'm noticing that some of my calls to findLine() are giving me the following error:

```
java.lang.ClassCastException: org.sikuli.script.Finder cannot be cast to org.sikuli.script.Match
	at org.sikuli.script.Region.findLine(Region.java:2746)
```

Looks like findLine is struggling to cast the result of doFindText() to `Match` in some cases, I have a hunch that it's only when the searched for text is not found but that is unconfirmed.

**Comment by RaiMan** [comment]
Will check - thanks
