### ISSUE TITLE
VSCode can't open libopencv_java430.dylib in MacOS

### ISSUE THREAD

**Issue by richwyantoddball** [RaiMan/SikuliX1#533]
Environment:
MacOS 12.3.1 (21E258) M1
VS Code
Java
Maven
TestNG

I'm trying to write methods in a class for an automated testing framework that has to interact with a 3270 terminal emulator that I have to access over Cirtix. To get Sikuli installed, I followed this: https://gist.github.com/henrik/1967035. 

The Maven coordinates for Tess4j look like this:

```
<!-- https://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j -->
    <dependency>
      <groupId>net.sourceforge.tess4j</groupId>
      <artifactId>tess4j</artifactId>
      <version>5.2.1</version>
    </dependency>
```

I have a Hello World class that looks like this:

```
public class SikuliUtils {

    private static Screen screen = new Screen();
    private Settings settings = new Settings();
    private OCR ocr = new OCR();

    public static void printAllText() {
       System.out.println(OCR.readText(screen));
    }
}
```

When running a test that just invokes this method, I get this:
```
[error] RunTime:loadLib: libopencv_java430.dylib (failed) probably dependent libs missing:
Can't load library: /Users/<myusername>/Library/Application Support/Sikulix/SikulixLibs/libopencv_java430.dylib
[error] Save your work, correct the problem and restart the IDE!
[error] see: https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-Libraries-for-OpenCV-4
TERMINATING: problem with native library: libopencv_java430.dylib
```

So far, other than the gist, I've done the following.
1. Installed the Sikuli IDE from here: https://raiman.github.io/SikuliX1/downloads.html.
2. Made sure my version of Java and VSCode have access in Accessibility and Screen Recording. I think that was part of the install instructions for Sikuli IDE, but I didn't bookmark the page.
3. `brew install opencv` per the page that opens up every time this fails
4. Added /Users/<myusername>/Library/Application Support/Sikulix/SikulixLibs to my $PATH in .zshenv
5. chmod that file from rw-r--r-- to rwxr-xr-x
6. Ran the test with Sikuli IDE running in another window
7. Opened VSCode as `sudo` from Terminal. That at least got me this:
`[error] Mouse: not useable (blocked)
See: https://github.com/RaiMan/SikuliX1/wiki/Allow-SikuliX-actions-on-macOS`

The app and that file both have `staff` level ownership. Why did I get this at all? What would the next step be so I can actually use Sikuli in Java classes I write?

Thank you in advance for any constructive help.

Edit: code text had wrong formatting

**Comment by RaiMan** [comment]
SikuliX 2.0.5 does not work on macOS M1.

Try with the 2.0.6 snapshot.

**Comment by richwyantoddball** [comment]
It worked. For those as dumb as me on Maven:
* put the jar into project directory
* install it using the first option here: https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
* in ~/.m2/repository/<groupId>/<artifactId>/<version>, open up maven-metada-local.xml
* use that to make Maven coordinates in your main pom.xml
