### ISSUE TITLE
Add extensions or Syntax highlighting? 

### ISSUE THREAD

**Issue by FitzM** [RaiMan/SikuliX1#534]
Just want to say, I love Sikuli but I find the IDE difficult. Is there any way to enable extensions to add syntax highlighting or even use Sikuli from within another IDE such as Visual Studio? 

If you have several scripts and there is a space missing in one, it can be quite tedious to track down which line has 4 spaces instead of 5 for example.

**Comment by RaiMan** [comment]
Sorry, but there is nothing possible in the IDE - you have to live with the actual features.

But you can edit scripts in any editor that supports Python language.
What you might miss are the inline capturing, the thumbnails, auto-image-naming and running scripts.

You might use the IDE and the external editor in parallel, but to see your external changes in the IDE, currently you have to close and reload the script tab. So it is possible but needs some focused handling and routine.
