### ISSUE TITLE
Can't stop script on macbook m1 (sikulix 2.0.6)

### ISSUE THREAD

**Issue by stinkstar** [RaiMan/SikuliX1#538]
Hello, I am not able to stop the script tried the following combinations:
cmd + shift + 3
cmd + shift + c
cmd + shift  + - + 3

this is what I am instructed to press:

<img width="177" alt="Skærmbillede 2022-06-02 kl  14 55 08" src="https://user-images.githubusercontent.com/106751320/171635794-74262918-9881-4838-83ca-42be2f66a9c9.png">

Not sure what that means

**Comment by RaiMan** [comment]
Guess you already found out: SHIFT+CMD+c
