### ISSUE TITLE
TERMINATING: problem with native library: libJXGrabKey.so

### ISSUE THREAD

**Issue by Marietto2008** [RaiMan/SikuliX1#539]
Hello.

I'm running FreeBSD 13R,I tried to start Sikulix on this OS,but I've got the following error :

[marietto@marietto /usr/home/marietto/Desktop]$ java -jar sikulixide-2.0.5.jar
```

[error] FileManager: writeStringToFile: did not work: /home/marietto/.Sikulix/SikulixStore/lastUsedJar.txt
/home/marietto/.Sikulix/SikulixStore/lastUsedJar.txt (No such file or directory)
[error] SikuliIDEI18N: no locale for en
[error] RunTime:loadLib: libJXGrabKey.so (failed) probably dependent libs missing:
Can't load library: /home/marietto/.Sikulix/SikulixLibs/libJXGrabKey.so
[error] Save your work, correct the problem and restart the IDE!
[error] see: https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-Libraries-for-OpenCV-4
TERMINATING: problem with native library: libJXGrabKey.so
```

this is the java version that I'm using : 
```

[marietto@marietto /usr/home/marietto/Desktop]$ java -version

openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)
```

is there a way to fix this bug ? thanks.

**Comment by Marietto2008** [comment]
I have fixed this problem,doing :

```
[marietto@marietto /usr/home/marietto/Desktop]$ sudo pkg install jxgrabkey
mount -t fdescfs fdesc /dev/fd
mount -t procfs proc /proc
```

To make it permanent, you need the following lines in /etc/fstab:
```

        fdesc   /dev/fd         fdescfs         rw      0       0
        proc    /proc           procfs          rw      0       0
```

cp /usr/local/lib/libJXGrabKey.so /home/marietto/.Sikulix/SikulixLibs/

**Comment by melek956** [comment]
I had the same problem and I tried to do your procedure the cmd shows me this message pkg command not found what can i do please help me

**Comment by Marietto2008** [comment]
Go to /usr/ports/ports-mgmt/pkg, run # make build after which you should be left with a working pkg version somewhere in the working directory. Try running that, and when it works you can then use # ./pkg install pkg which would fix your problems.

**Comment by melek956** [comment]
/usr/ports/ports-mgmt/pkg not exist in ubuntu

**Comment by Marietto2008** [comment]
I'm not running ubuntu,but freebsd.

**Comment by melek956** [comment]
Have you an idea on ubuntu ?
