### ISSUE TITLE
Not able to install the Sikulix setup 1.1.3 jar in Linux 

### ISSUE THREAD

**Issue by rajateshr** [RaiMan/SikuliX1#543]
Url to download the Sikulix setup 1.1.3 jar : https://launchpad.net/sikuli/+download
Command  used to install Sikulix setup 1.1.3  jar -->java -jar Sikulix setup 1.1.3 jar
While installing sikulix setup 1.1.3 jar, i am getting the error as 'Something serious happened! Sikuli Not Usable'... Check the error log

OS used: Linux Ubuntu 20.04.4 LTS
![Uploading Screenshot from 2022-07-13 21-41-34.png…]()

**Comment by rajateshr** [comment]
Error Logs
[debug (13/07/22, 10:47:36 PM)] Debug: setLogFile: /home/mglocadmin/SikuliX-1.1.3-SetupLog.txt
[debug (13/07/22, 10:47:36 PM)] RunSetup: ... starting with no args given
[debug (13/07/22, 10:47:36 PM)] RunSetup: LinuxDistro: ???LINUX??? (64-Bit)
[debug (13/07/22, 10:47:36 PM)] RunSetup: Setup: 1.1.3 2018-07-11_08:19 in folder:
/home/mglocadmin
[debug (13/07/22, 10:47:36 PM)] RunSetup: RunningSystem: Linux 5.13.0-52-generic (???LINUX???)
[debug (13/07/22, 10:47:36 PM)] RunSetup: parent of jar/classes: /home/mglocadmin
[debug (13/07/22, 10:47:36 PM)] RunSetup: RunningJava: Java 11 (amd64) 11.0.15+10-Ubuntu-0ubuntu0.20.04.1
[debug (13/07/22, 10:47:36 PM)] init user preferences
[debug (13/07/22, 10:47:40 PM)] RunSetup: 
popAsk: --------------------
The following file(s) will be downloaded to
/home/mglocadmin
--- Native support libraries for Linux (sikulixlibs...)
--- Package 1 ---
sikulixsetupIDE-1.1.3-20180711.082119-40-forsetup.jar (IDE/Scripting)
sikulixsetupAPI-1.1.3-20180711.082046-40-forsetup.jar (Java API)
 - with Jython
Only click NO, if you want to terminate setup now!
Click YES even if you want to use local copies in Downloads!
--------------------
[debug (13/07/22, 10:47:42 PM)] RunSetup: 
popAsk: --------------------
You have for Linux native libs
/home/mglocadmin/.Sikulix/SikulixDownloads/sikulixlibslux-1.1.1.jar
Click YES, if you want to use this for setup processing
... or click NO, to ignore it and download a fresh copy
--------------------
[debug (13/07/22, 10:47:43 PM)] RunSetup: Copied from Downloads: sikulixlibslux
[debug (13/07/22, 10:47:43 PM)] RunSetup: checking usability of bundled, provided or built libs
[debug (13/07/22, 10:47:43 PM)] RunTimeSETUP: exists libs folder at: /home/mglocadmin/.Sikulix/SikulixLibs_201807110819
[error (13/07/22, 10:47:43 PM)] RunTimeSETUP: loadLib: libVisionProxy.so not usable: 
java.lang.UnsatisfiedLinkError: /home/mglocadmin/.Sikulix/SikulixLibs_201807110819/libVisionProxy.so: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
[error (13/07/22, 10:47:43 PM)] RunTimeSETUP: loadLib: libVisionProxy.so not usable: 
java.lang.UnsatisfiedLinkError: /home/mglocadmin/.Sikulix/SikulixLibs_201807110819/libVisionProxy.so: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: we have to build libVisionProxy.so
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: checking: availability of OpenCV and Tesseract
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: checking: scanning loader cache (ldconfig -p)
[debug (13/07/22, 10:47:43 PM)] RunTimeSETUP: ldconfig -p 
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: checking: found OpenCV libs:
/lib/x86_64-linux-gnu/libopencv_core.so.4.2
/lib/x86_64-linux-gnu/libopencv_highgui.so.4.2
/lib/x86_64-linux-gnu/libopencv_imgproc.so.4.2
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: checking: found Tesseract lib:
/lib/x86_64-linux-gnu/libtesseract.so.4
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: buildVision: starting inline build: libVisionProxy.so
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: buildVision: java.home from java props: /usr/lib/jvm/java-11-openjdk-amd64
[debug (13/07/22, 10:47:43 PM)] LinuxSupport: buildVision: JAVA_HOME from environment: null
[error (13/07/22, 10:47:43 PM)] LinuxSupport: buildVision: no valid Java JDK available nor found
[error (13/07/22, 10:47:43 PM)] RunTimeSETUP: Problematic lib: /home/mglocadmin/.Sikulix/SikulixLibs_201807110819/libVisionProxy.so (...TEMP...)
[error (13/07/22, 10:47:43 PM)] RunTimeSETUP: libVisionProxy.so loaded, but it might be a problem with needed dependent libraries
ERROR: ...TEMP...: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
[error (13/07/22, 10:47:43 PM)] RunSetup: libVisionproxy.so finally not useable
[error (13/07/22, 10:47:43 PM)] RunSetup: Giving up!
[error (13/07/22, 10:47:43 PM)] RunSetup: ... terminated abnormally :-(
[debug (13/07/22, 10:47:43 PM)] RunSetup: 
popError: --------------------
Something serious happened! Sikuli not useable!
Check the error log at /home/mglocadmin/SikuliX-1.1.3-SetupLog.txt
--------------------
[debug (13/07/22, 10:47:45 PM)] RunTimeSETUP: final cleanup
[debug (13/07/22, 10:47:45 PM)] FileManager: deleteFileOrFolder:
/tmp/Sikulix_1765921267

**Comment by RaiMan** [comment]
Sorry, have to leave you alone with that.
Try with latest version.
