### ISSUE TITLE
RunTime.libsExport() Not Working - M1 Mac, 2.0.6-SNAPSHOT, sikulix2opencv 4.5.4

### ISSUE THREAD

**Issue by harmonjeff** [RaiMan/SikuliX1#544]
Been a bit since I have tried to use SikluiX API on an M1 Mac, but I am back at it.  

I am sure I have done something wrong with regard to how to build/install/use the API and IDE.  Would appreciate your assistance even though I know you are not at a "stable" state with 2.0.6.

Here are the steps I have taken :

Install the opencv library required for SikluiX
- `brew install opencv` (got version 4.5.5_3 - maybe need to downgrade to 4.5.4?)
`brew info opencv` shows that cmake is needed, so install it
- `brew install cmake` (got version 2.23.2)

Install the tesseract library required for OCR in SikluiX
- `brew install tesseract` (got version 5.2.0)
`brew info tesseract` shows autoconf is needed
- brew install autoconf (got version 2.7.1)
`brew info tesseract` shows automake is needed
- `brew install automake` (got version 1.16.1)

Clone the new sikulix2opencv branch that has the natives for platforms
- `git clone https://github.com/RaiMan/sikulix2opencv.git`
- `cd sikluix2opencv`
- `mvn clean install`

Clone the Sikulix branch that uses sikluix2opencv and has code for M1
- `cd ..`
- `git clone https://github.com/RaiMan/SikuliX1.git`
- `cd SikluiX1`
- `git checkout release_2.0.6_macM1`
- `mvn clean install -P complete-macM1-jar`

Enable MacOS Security & Privacty to allow terminal and other applications to make calls to the "System Events.app"
- `osascript -e 'tell application "System Events" to keystroke "a"'`

Manually add Terminal.app, iTerm.app, java, Visual Studio Code to Screen Recording and Accessibility permissions
- Note: Not sure ALL of those have to be done, but it for sure works if all of them are

Launch the SikuliX IDE to help me with some testing and getting screen shots
- `java -jar SikuliX1/IDE/target/sikulixide-2.0.6-SNAPSHOT-complete-macM1.jar`

Create a script to bring Lightroom to foreground
```
LrApp = App("'Adobe Lightroom Classic'")
LrApp.focus()
```

No errors, brought the Lightroom application to the foreground!

Add to the script 
```
region = LrApp.focusedWindow()
region.click("Remove from Lightroom")
```

Get an exception
```
[error] ImagePath: find: not there: Remove from Lightroom.png
[debug] ImagePath: BundlePath: /Users/jharmon/lrtest.sikuli
[error] script [ lrtest ] stopped with error in line 4
[error] org.sikuli.script.SikuliXception ( org.sikuli.script.SikuliXception: OCR: start: Tesseract library problems: Error looking up function 'TessBaseAPIRecognizeForChopTest': dlsym(0x204dc3280, TessBaseAPIRecognizeForChopTest): symbol not found )
[error] --- Traceback --- error source first
line: module ( function ) statement 
4: main (  <module> )     region.click("Remove from Lightroom")
[error] --- Traceback --- end --------------
```

By the way, my Java application that uses Sikulix API works just like the IDE (focus works but click fails with tesseract error) after building, installing the libraries to my local maven repo and adding this to my pom.xml
```
<dependency>
  <groupId>com.sikulix</groupId>
  <artifactId>sikulixapi</artifactId>
    <version>2.0.6-SNAPSHOT</version>
</dependency>
```

**Comment by harmonjeff** [comment]
Adding some more information to the issue, I managed to downgrade to tesseract 4.5.4 (not so easy with brew, this site was helpful though it didn't fully work: https://itnext.io/how-to-install-an-older-brew-package-add141e58d32)

After doing that, the behavior is a little strange.  First time running the entire script (including the click on the button) I get this error:
```
[error] ImagePath: find: not there: Remove from Lightroom.png
[debug] ImagePath: BundlePath: /Users/jharmon/lrtest.sikuli
TERMINATING: FATAL: loadlib: libopencv_java454.dylib not in any libs folder
[error] script [ lrtest ] stopped with error in line 4
[error] java.lang.ExceptionInInitializerError ( java.lang.ExceptionInInitializerError )
[error] --- Traceback --- error source first
line: module ( function ) statement 
4: main (  <module> )     region.click("Remove from Lightroom")
[error] --- Traceback --- end --------------
```

But if I run the script again without closing and restarting the IDE I get this error:
```
[error] ImagePath: find: not there: Remove from Lightroom.png
[debug] ImagePath: BundlePath: /Users/jharmon/lrtest.sikuli
[error] script [ lrtest ] stopped with error in line 4
[error] java.lang.NoClassDefFoundError ( java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindInput2 )
[error] --- Traceback --- error source first
line: module ( function ) statement 
4: main (  <module> )     region.click("Remove from Lightroom")
[error] --- Traceback --- end --------------
```

If I change the script to not try and use Tesseract libraries to find a button by OCR things work with any errors.

**Comment by harmonjeff** [comment]
And a little more information :)

I decided to try using an image to find and click the button.  Took a screenshot using the IDE to make sure it was the right resolution (though I am working on a non-retina screen attached to M1 MacBook Pro).  That failed too, looks like the same error as I am getting in the IDE when using OCR (on the second try):

```
[error] script [ lrtest ] stopped with error in line 4
[error] java.lang.NoClassDefFoundError ( java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindInput2 )
[error] --- Traceback --- error source first
line: module ( function ) statement 
4: main (  <module> )     region.click("RemoveFromLightroomButton.png")
[error] --- Traceback --- end --------------
```

Here is more information in the stack trace from my Java application where the same things happens:
```
java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindInput2
	at org.sikuli.script.Finder.<init>(Finder.java:25) ~[sikulixapi-2.0.6-SNAPSHOT.jar:na] Finder.java:25
	at org.sikuli.script.Region.doFind(Region.java:2849) ~[sikulixapi-2.0.6-SNAPSHOT.jar:na] Region.java:2849
	at org.sikuli.script.Region$RepeatableFind.run(Region.java:3103) ~[sikulixapi-2.0.6-SNAPSHOT.jar:na] Region.java:3103
```

**Comment by harmonjeff** [comment]
I think I have made sense of the two error messages.  Looks to me like the `libsExport` method isn't working for me on M1 Mac.  

https://github.com/RaiMan/SikuliX1/blob/release_2.0.6_macM1/API/src/main/java/org/sikuli/script/support/RunTime.java#L188

As I run the IDE (or the API from my Java application), the following happens
- `~Library/Application Support/Sikulix/SikulixLibs` folder gets created 
- `2.0.6_202207161553_MadeForSikuliXMaarch64` text file gets created in that folder
- `libopencv_java454.dylib` library built and included in the `sikulix2opencv-4.5.4.jar` never gets put in that folder
 
Therefore the library can't be found and none of the functionality that requires opencv or tesseract works.  The App.focus works because that is now done via AppleScript.

I tried to do some debugging on why the `libsExport` is failing and couldn't make sense of it right off so I took a shortcut just to get me going so that I can continue building my automation client.  I commented out the if exists check in the `libExport` method so that it won't delete the libs folder in my User home.  Then I manually copied the library to where it needs to be.

Doing a Region.click using an image now works, so opencv is functional. Doing a Region.click with text did not.  I don't get an exception about the tesseract library not working nor a FindFailed, so not sure what is going on there.  For now I guess I'll just use images with my automation.

**Comment by RaiMan** [comment]
1. On macOS M1 the current SikuliX 2.0.6 does not need an opencv installed. The dependency `sikulix2opencv::4.5.4-SNAPSHOT` contains a fat dylib with all needed dependencies (static lib). This is the same as for Windows.
2. For OCR by Tesseract it should work with the latest version installed with homebrew (currently 5.2.0, tested ok).

Generally it is currently not recommended to work with a fork of the repo (very unstable, not tested).
Use the downloadable IDE jar from the README.

Before trying from Java, you should test the features you want to use with the IDE.

If everything is ok, then use a Maven project with the dep `com.sikulix::sikulixapi::2.0.6-SNAPSHOT.`
This should work as expected.

Alternatively you can use the IDE jar as a static local Java library.

**Comment by harmonjeff** [comment]
Thank you so much for the time RaiMan.

Is there a maven repo that has the `com.sikulix::sikulixapi::2.0.6-SNAPSHOT` for me to pull from.  Doesn't look to me like the IDE jar has the needed `org/siklui/script` classes I need for my Java project.  I am sure I am missing something.

**Comment by RaiMan** [comment]
*   snapshots are on OSSRH
  *   IDE jar contains the API - be sure 👍

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: harmonjeff ***@***.***>
Gesendet: Sunday, July 17, 2022 5:20:53 PM
An: RaiMan/SikuliX1 ***@***.***>
Cc: Raimund Hocke ***@***.***>; State change ***@***.***>
Betreff: Re: [RaiMan/SikuliX1] RunTime.libsExport() Not Working - M1 Mac, 2.0.6-SNAPSHOT, sikulix2opencv 4.5.4 (Issue #544)


Thank you so much for the time RaiMan.

Is there a maven repo that has the com.sikulix::sikulixapi::2.0.6-SNAPSHOT for me to pull from. Doesn't look to me like the IDE jar has the needed org/siklui/script classes I need for my Java project. I am sure I am missing something.
