### ISSUE TITLE
Don't start on windows - Dell E6420

### ISSUE THREAD

**Issue by charliedaps1** [RaiMan/SikuliX1#546]
Hello,

I try to install Sikuli on a Dell E6420 with windows 7 (I have test with windows 10 too)

New fresh install, last version of java check with java -version

And when I double click on the sikuli ide file, nothing append.

The same configuration work on a lenovo. I'm sure that I have almost use sikuli on this dell before.

Thanks for your help.

**Comment by woodrow73** [comment]
What's the output if you run the jar file from CMD?

**Comment by charliedaps1** [comment]
Thanks for your anwser and your help.

I only have error messages concerning the path.

java -jar c:\sikuli\sikulixide-2.0.5-win.jar 

There file is in this folder.

And Java is installed by default.

Thanks.
