### ISSUE TITLE
Error when using sikulix from Maven repository

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [RaiMan/SikuliX1#55]
Version 1.1.1 was working fine.
But version 1.1.2 fails in this way:

```
java.lang.ExceptionInInitializerError
  org.sikuli.script.Sikulix.cleanUp(Sikulix.java:459)
  org.sikuli.script.Sikulix.endError(Sikulix.java:415)
  org.sikuli.script.RunTime.initSikulixOptions(RunTime.java:1688)
  org.sikuli.script.RunTime.get(RunTime.java:310)
  org.sikuli.script.RunTime.get(RunTime.java:122)
  org.sikuli.script.RunTime.get(RunTime.java:337)
  org.sikuli.util.JythonHelper.<clinit>(JythonHelper.java:23)
java.lang.NullPointerException
  org.sikuli.script.RunTime.makeFolders(RunTime.java:804)
  org.sikuli.script.RunTime.libsExport(RunTime.java:913)
  org.sikuli.script.RunTime.libsLoad(RunTime.java:844)
  org.sikuli.script.RunTime.loadLibrary(RunTime.java:1019)
  org.sikuli.android.ADBScreen.<clinit>(ADBScreen.java:21)
  org.sikuli.script.Sikulix.cleanUp(Sikulix.java:459)
  org.sikuli.script.Sikulix.endError(Sikulix.java:415)
  org.sikuli.script.RunTime.initSikulixOptions(RunTime.java:1688)
  org.sikuli.script.RunTime.get(RunTime.java:310)
  org.sikuli.script.RunTime.get(RunTime.java:122)
  org.sikuli.script.RunTime.get(RunTime.java:337)
  org.sikuli.util.JythonHelper.<clinit>(JythonHelper.java:23)
```

I'd be happy to use a newer version, but they aren't in any Maven repo.

BTW, it has been hard to use sikulix2tigervnc-2.0.0-SNAPSHOT, because it isn't published.

**Comment by RaiMan** [comment]
> I'd be happy to use a newer version, but they aren't in any Maven repo.

IMHO this was clear now:
https://github.com/RaiMan/SikuliX1/issues/50

> sikulix2tigervnc-2.0.0-SNAPSHOT
yep, not in MavenCentral - but in OSSRH (snapshot)

You have to live with the situation - I have to concentrate on the features and other things currently.

**Comment by DavidPerezIngeniero** [comment]
Version 1.1.4 can be downloaded ok from maven repositories with all its dependencies :-)

**Comment by RaiMan** [comment]
@DavidPerezIngeniero 

> Version 1.1.4 can now be downloaded ok from maven repositories with all its dependencies

not sure what you want to tell us?

1.1.4 is still snapshot and not on MavenCentral but on OSSRH

**Comment by DavidPerezIngeniero** [comment]
It was before impossible to download from Maven sikulix 1.1,2, 1.1.3 and 1.1.4 with all its dependencies, even configuring the right repositories.  So I had to stick to version 1.1.1.
