### ISSUE TITLE
NameError after making a change to the script

### ISSUE THREAD

**Issue by sengsational** [RaiMan/SikuliX1#550]
I can run a script for the first time, and it starts running, but if the script fails for some reason and I make a change to the script, I get the NameError.

For instance, say my script hits a `wait()` statement, where the image is not found, and the script ends because the web page has made a slight change.   I will typically go to the image that wasn't found, click `matching preview` and lower the fraction until the image is found.

Then I will put `"""` starting after the imports, and a matching `"""` right before the line that failed.

I expect to be able to click the `Run` button and have the script run.

What I encounter, unexpectedly, is something like this:

    [error] IDE: Run Script: internal error:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'DalesScript' is not defined

Stopping and restarting the IDE is a work-around, but it's time-consuming.

**Comment by RaiMan** [comment]
since version 2.0.5:

right click on the respective line number in the IDE and select an option to run some lines only.
this works in the same context as the previous complete run.
