### ISSUE TITLE
Mouse not useable  in win10

### ISSUE THREAD

**Issue by chenjiao322** [RaiMan/SikuliX1#552]
I tried use idea or just run sikulix ide (already run as administrator)。
Error messages are notified as follows([error] Mouse: not useable (blocked):
![image](https://user-images.githubusercontent.com/17329051/196314244-c3592f36-3cf4-40ca-8a38-5700e40e315d.png)

**Comment by chenjiao322** [comment]
The message is not notified in version 2.0.4 but it doesn't work either.

**Comment by artem-zinin** [comment]
This is still an issue in win10, version 2.0.5.

**Comment by santeriv** [comment]
I had this problem on on 2.0.5 win11, but setting scale to 100% in Display settings made this error-message disappear.

<img width="1072" height="140" alt="Image" src="https://github.com/user-attachments/assets/b6e37f5d-63ef-4ea4-b2e1-5885cb4c4c90" />
