### ISSUE TITLE
Unable to use SikuliSharp to click on Pattern

### ISSUE THREAD

**Issue by anilnambiar003** [RaiMan/SikuliX1#554]
Hi,

I am trying to use Sikulisharp to automate a desktop application. now that sikulisharp is NOT MAINTAINED. I have installed sikulixIDE and tried performing click action on the application using IDE. I could perform the action using IDE.

But when I try to create sikuli session using C# code and tried the above action using sikulisharp, I am facing "no result in allotted time" although the Pattern is available on the desktop application. (I have installed java 8, used sikulixapi and jython-standalone-2.7.1 and setup environment variable for sikuli_home)

1. Could you help me if I am missing any other jar files needed to be placed under sikuli_home path.
2. It would be really helpful if we have any pointer/ page which I can refer to integrate sikulix with C#

Thanks in advance

**Comment by RaiMan** [comment]
Sorry. Cannot support you - lack of knowledge and testing environment.
