### ISSUE TITLE
New screenshot with same variable name overwrites previous screenshot

### ISSUE THREAD

**Issue by jto234** [RaiMan/SikuliX1#555]
Consider the following code:

```
def which_image(input):
    if input == "red":
        output = #screenshot of red object
    if input == "blue":
        output = #screenshot of blue object
    return output
```

Upon creation of the last (blue) screenshot, the first screenshot (red) is replaced by the new screenshot, though this is not reflected visually in the IDE until the script is closed and reopened.

This may seem like a trivial edge case bug (and I guess it is) but I was working with very similar-looking images with the same variable names, and it threw me for a loop for a while. If the new screenshot is named output2.png this is avoided.

**Comment by RaiMan** [comment]
This is by design: the image name  is taken from the name left of the equal sign.

workaround:

``` python
def which_image(input):
    if input == "red":
        red = #screenshot of red object
        output = red
    if input == "blue":
        blue = #screenshot of blue object
        output = blue
    return output
```
