### ISSUE TITLE
getting dialog box mouse and screenshot is blocked while trying to launch sikuili 2.0.6 as remote user(Mac13 M1)

### ISSUE THREAD

**Issue by shruti-s12** [RaiMan/SikuliX1#557]
while automating some scripts on Mac 13 m1 thrugh sikuli 2.0.6 we are getting a pop up mouse/screenshot is blocked while launching sikuli ide as a remote user due to which we are stuck, is there is any way to resolve this?
<img width="714" alt="Screenshot 2022-12-01 at 11 22 42 AM" src="https://user-images.githubusercontent.com/118868286/204976646-00f248fb-5470-4133-9622-374d3c7d9f67.png">

<img width="393" alt="Screenshot 2022-11-30 at 6 21 40 PM" src="https://user-images.githubusercontent.com/118868286/204802320-7d904e07-5fb3-4e1f-8aab-124dc1bc74bb.png">

**Comment by asinghQA** [comment]
@RaiMan kindly help with this problem

**Comment by RaiMan** [comment]
Make sure, that you have allowed screen capture and mouse usage on the target system:
https://github.com/RaiMan/SikuliX1/wiki/Allow-SikuliX-actions-on-macOS

**Comment by shruti-s12** [comment]
@RaiMan i have already allowed screen capture and mouse usage and sikuli is working fine if we are launching it on that particular machine terminal,we getting this dialog box while running sikuli as remote user.

steps:
1.ssh the target machine by another machine.
2.run sikuli -jar file

**Comment by asinghQA** [comment]
@RaiMan , I have allowed, but the problem is still there

**Comment by RaiMan** [comment]
Mind the differences between Java 8 and later versions in the above mentioned wiki post.

On the target machine: can you start the SX stuff locally (not over ssh) and look what happens?
Might be that The Terminal app must be authorized too.

Generally I cannot help you with your ssh situation - no experience.

**Comment by asinghQA** [comment]
@RaiMan , can we expect a newer build for mac m1 any soon?

**Comment by RaiMan** [comment]
@asinghQA 

SikuliX itself cannot do anything to make the script work on the target machine.
It can only detect, that the Java Robot features (screenshot, mouse and keyboard) do not work.
It is up to the user to tweak the system accordingly.

Hence a newer build would not change anything.

But anyways: the dev is currently slowed down due to private priorities.

**Comment by asinghQA** [comment]
Oh okay, thank you
