### ISSUE TITLE
Add simple code examples to README.md to help new users

### ISSUE THREAD

**Issue by PyaePhyoKhant** [RaiMan/SikuliX1#559]
Can I add simple code examples on README.md? For example I want to add documentation/examples of hello world tutorial, conditionals, loops, etc. Also mentioning short list of built-in functions like `click`, `doubleClick`, `exists`, etc.

When I started using this software, I didn't see any links or documentation on README.md about how to actually write code. Most of the documentation are about settings, configuration and such without any code examples. I had to refer to Youtube to see actual code examples.

So, I think it will be beneficial for new users to see code examples on README.md. I want to contribute writing simple code examples and tutorials on README.md.

**Comment by RaiMan** [comment]
This GitHub repo is not the place for new users to learn how to code SikuliX scripts.

The basic scripting uses Python language run by the Jython engine.
New users should start with the [homepage sikulix.com](http://sikulix.com).
There you find the [link to the docs](http://sikulix-2014.readthedocs.org/en/latest/index.html) which contains the feature descriptions and some examples.

Feel free to post examples with description/comments here in this thread, which I can add to the docs.
