### ISSUE TITLE
IDE: [error] EditorPane: Problem while trying to clean bundle (not used images): null

### ISSUE THREAD

**Issue by plaidshirtakos** [RaiMan/SikuliX1#56]
I get following error message after I saved project.

`[error] EditorPane: Problem while trying to clean bundle (not used images): null`

SikulixIDE 1.1.4-SNAPSHOT(2018-12-05)

**Comment by RaiMan** [comment]
Thanks, already seen that, but forgot to register a bug ;-)

**Comment by RaiMan** [comment]
Should be fixed with next build #140
