### ISSUE TITLE
Can it comatible with Wayland on Ubuntu 22.04? It is using Xorg.

### ISSUE THREAD

**Issue by takurx** [RaiMan/SikuliX1#560]
I'm often helpful to Sikulix . Thank you.

Sikulix work "take screenshot" on Xorg (legacy display server) and Ubuntu 22.04.
![ubuntu_on_xorg_IMG_8543](https://user-images.githubusercontent.com/6850122/209456063-1a894284-b038-4186-99b0-81e6b9b88a55.jpg)

Case of Wayland (default display server),
I try to push "take screenshot", it became black screen and I can not get image.
![ubuntu_on_wayland_IMG_8542](https://user-images.githubusercontent.com/6850122/209456055-e669d048-76d3-4942-b29c-5753c3411b0a.jpg)

I had changed to Xorg from Wayland.
In login screen and setting(like gear) button at bottom right, checked "Ubuntu on Xorg"
![select_wayland_or_xorg_IMG_8541](https://user-images.githubusercontent.com/6850122/209455989-ba1760dc-f4da-4c40-a35d-0e57f779c545.jpg)

My environment is default on Ubuntu 22.04.
- gdm3

> $ gnome-shell --version
> GNOME Shell 42.2

Happy holidays!!

**Comment by RaiMan** [comment]
You have to find a solution in the net that is compatible with the usage of the Java feature `AWT.Robot.createScreenCapture()`, which is used by SikuliX internally to grab screen content.
