### ISSUE TITLE
Sikuli script is throwing FindFailed exception while running desktop application in different resolution

### ISSUE THREAD

**Issue by rajateshr** [RaiMan/SikuliX1#561]
I have ran the Sikuli script for automating desktop application in my current resolution of desktop..But when i ran the sikuli script in different screen resolution then the script is not able to recognize the exact matching image screenshot of GUI element and also it is throwing FindFailed exception

**Comment by RaiMan** [comment]
Images must be visible on the target system in the same size in pixels.

If you know a scaling factor, you might use the `Pattern.resize()` feature.

In all other cases you need an extra image set for each different target system.

You could automate the image set selection by checking an image at startup in appropriate sizes/resolutions.
