### ISSUE TITLE
Use system libJXGrabKey.so in Ubuntu

### ISSUE THREAD

**Issue by jhonny-oliveira** [RaiMan/SikuliX1#563]
Hi!

I'm trying to package SikuliX for Ubuntu 22.04+ and include it in the [XtraDeb](https://xtradeb.net) package portfolio. Is there a way to use the system "libJXGrabKey.so" instead of the one embedded in the code?

Additionally, I'm using the official release (2.0.5-final). Ideally, any suggestion, should be for that version of the code.

Thank you!
Jhonny Oliveira

**Comment by RaiMan** [comment]
2.0.5 only works with the bundled (in-jar) `libJXGrabKey.so`. If you need another lib, you have to exchange the one in the jar before adding it to the package (`/sikulixlibs/linux/...`).
2.0.6 will have a feature to use the needed libs from outside the jar (folder env variable or simply from the system lib path).
... but I have no idea when the final will be ready
