### ISSUE TITLE
Sikuli Test Execution stops unexpectedly after running multiple test cases using runScript() command

### ISSUE THREAD

**Issue by rajateshr** [RaiMan/SikuliX1#571]
When i try to run tests for 8 modules using runScript() command, then only 1st 4 modules automation test executes successfully..But Sikuli suddenly stops execution for last 4 modules..Getting below error log

IOError: java.nio.channels.ClosedByInterruptException

java.lang.ThreadDeath

**Comment by RaiMan** [comment]
no feedback
