### ISSUE TITLE
text():  not all characters are read correctly 

### ISSUE THREAD

**Issue by rajateshr** [RaiMan/SikuliX1#572]
When i try to capture the visible texts from Desktop screen using text() command, then it is not capturing the properly

Example:When i try to capture text 79.1223 using text(), then it is displaying 791223 in the console

**Comment by RaiMan** [comment]
Version? System?

**Comment by RaiMan** [comment]
A short test with 2.0.5 on Win11 reads the text from your post above correctly.

**Comment by RaiMan** [comment]
ok, then you have to try with 2.0.5.
