### ISSUE TITLE
Unable to run Sikuli via Jenkins

### ISSUE THREAD

**Issue by Guter1988** [RaiMan/SikuliX1#574]
Hello,

First, thank you for this repository @RaiMan.

We use Sikuli for testing different suites on Windows.
All suites with Sikuli are developed and used in local machines and are working as expected.

### **The problem**
When using this suite in Jenkins, we open a remote desktop via `mstsc` to the relevant Windows machine at the Jenkins node.
Unfortunately, This is not working, and an option to work we found that open remote control to this Node is played a mouse in the widows, and then it starts to run.

### **Error**
INFO: couldn't find the image to click
 
### **Dependencies:**
sikuli-core - 1.2.2
sikulixapi - 2.0.5
Java version - 17

@RaiMan, you can significantly help us with the guide if there is any existing option or workaround.

Thanks ahead,
Regards,
Guy

**Comment by RaiMan** [comment]
Make sure, that the SikuliX features have access to a real or fake screen, that is not locked. 

BTW: `sikuli-core - 1.2.2` is not my work and not needed by `sikulixapi - 2.0.5`.

**Comment by Guter1988** [comment]
Hello, again @RaiMan  :) 
Can you suggest on fake screen option? We tried a few but they did not work.

Thanks.
Guy

**Comment by RaiMan** [comment]
@Guter1988 
Sorry no experience nor knowledge. Only seen some statements in the past.
Try on StackOverflow.

**Comment by Guter1988** [comment]
Got it.
Thanks a lot again!
