### ISSUE TITLE
Interactive mode in 2.x version

### ISSUE THREAD

**Issue by jakubpas** [RaiMan/SikuliX1#578]
Would it be possible to re-enable interactive mode for sikulix? It was used by some third party nuget extensions for c#. This way it was possible to use sikuli in .NET applications.

**Comment by RaiMan** [comment]
> interactive mode for sikulix

... I have no idea, what you are talking about.

Any hints or coding samples?

**Comment by jakubpas** [comment]
You might not be aware of such projects:

https://github.com/christianrondeau/SikuliSharp
https://sourceforge.net/p/sikuli4net/code/ci/master/tree/
https://github.com/OutSystems/SikuliSharp.NetCore

and so on. Thet work as wraper for sikuli java and use interactive mode to pass commads from c# to sikulix.

**Comment by RaiMan** [comment]
ok - understood.

... but that's not my work and I do not support it.

about `interactive mode ` (which in fact is the Jython feature):
- the former command line option `-i` is no longer there and will not come back (in the IDE you now can run one or more selected lines)
- with actual versions you might activate interactive mode yourself, by running from command line
   `java -cp some-SikuliXIDE.jar org.python.util.jython`
- this then would be the command to be used inside SikuliSharp to activate the interactive mode
