### ISSUE TITLE
MacOS 13 on M1 with not working with Java 17.0.7 (arm64) OpenJDK 17.0.7

### ISSUE THREAD

**Issue by opencoca** [RaiMan/SikuliX1#580]
Following the recommended setup including all the privacy settings is not working on my M1 systems.

Moreover using Oracle's older 1.8 presents the alert that it won't work and then does work. 

This problem isn't happening on older Mac systems.

**Comment by RaiMan** [comment]
What version of SikuliX?

**Comment by opencoca** [comment]
sikulixide-2.0.5 both mac jar and the multiplatform

Works with
```
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
```

Running with 1.8.0_291 works but with an odd warning that "Mouse usage is blocked". To be clear this is after toggling the Security&Privacy settings. The message doesn't need to pop up as Sikulixide is able to both capture screenshots and control keyboard and mouse.  Scripts are able to run from the ide.
