### ISSUE TITLE
SIKULI_IMAGE_PATH no longer supported

### ISSUE THREAD

**Issue by meisjohn** [RaiMan/SikuliX1#588]
In Sikuli-1.1.2 [here](https://github.com/RaiMan/SikuliX-2014/blob/20fa1e76ccd1a24117b09e73d907c120ab8fe853/API/src/main/java/org/sikuli/script/ImageLocator.java#L266) (and even in the [current documentation](https://sikulix-2014.readthedocs.io/en/latest/scripting.html?highlight=sikuli_image_path#getBundlePath)) there is an Environment Variable (`SIKULI_IMAGE_PATH`) that is no longer supported by version 1.1.3 and forward.  

We recently updated to 2.0.5 and have discovered this issue.  I think we can solve this on the client side by calling `sikuli.addImagePath()` with the value of the variable in our own initializer, but it seems like this is an oversight if it's still mentioned in the documentation, but is missing in the code.  Please consider restoring support for this variable.

**Comment by RaiMan** [comment]
Thanks for finding.

With version 2 any usage/support for SikuliX specific environment variables was removed and will not be restored.

That the word `SIKULI_IMAGE_PATH` was still in the latest docs, did not mean anything and is simply a doc-error.
I have revised the docs accordingly. 

Sorry for any inconveniences, but you have to implement your own solution.
