### ISSUE TITLE
[1.1.4] sikulixapi.jar should not use system.exit() - now throws SikuliXception instead --- revised build #172

### ISSUE THREAD

**Issue by THedoux** [RaiMan/SikuliX1#59]
If something goes wrong with the Sikulax jar API initilialisation, it makes a call to 'system.exit(...)'.

It is a major issue, because it is killing at the same time each application currently launched and running on the same JVM.

Rather than a 'system.exit' an exception should be raised, and let the host decides what to do with it.

**Comment by RaiMan** [comment]
ok, accepted - not helpful in your case ;-)

will fix it asap.

**Comment by THedoux** [comment]
thanks!

**Comment by THedoux** [comment]
Hello RaiMan,

Happy new year :)

Any news about this one? Did you have an idea of when you will have the time to fix it?

**Comment by RaiMan** [comment]
should work now.
tests would be appreciated.

**Comment by THedoux** [comment]
It works on the daily build.

But throwing a raw Java Runtime Exception is a bad idea :)

The main issue with the runtime exception is the calling program have no way to filter it, because it could come from everywhere. It makes integration better and easier if you could throw a specific exception (SikuliRuntimeException in example), even if this exception is just extending the raw RuntimeException class.

**Comment by RaiMan** [comment]
Thanks for feedback and suggestion.
Somehow I already  suspected your reaction ;-) (not much experience in the field you are busy)

Of course I will implement your suggestion. :)

**Comment by RaiMan** [comment]
The ready to use sikulixapi.jar can be downloaded  from here:
https://raiman.github.io/SikuliX1/downloads.html

The CI (TravisCI) is behind the green tick link at the end of every commit title.
