### ISSUE TITLE
Issue when trying to connect a tiger vnc server

### ISSUE THREAD

**Issue by lrabiet** [RaiMan/SikuliX1#599]
When I simply execute this command : 

`VNCScreen vnc = VNCScreen.start("X.X.X.X", Y,"Z", 30, 30)`

`Exception in thread "DefaultDispatcher-worker-1" com.tigervnc.rdr.SystemException: com.tigervnc.rdr.SystemException: class com.sikulix.vnc.VNCClient cannot be cast to class com.tigervnc.vncviewer.CConn (com.sikulix.vnc.VNCClient and com.tigervnc.vncviewer.CConn are in unnamed module of loader 'app')
`

Is it due to the java not being 1.8 ? or is it something else ?

**Comment by RaiMan** [comment]
The VNC solution is no longer supported.
