### ISSUE TITLE
vnc is not working on linux ubuntu 16.04 with jython 2.7

### ISSUE THREAD

**Issue by amir3code** [RaiMan/SikuliX1#6]
I have installed sikulix and when I write in the IDE:
```
vnc = vncStart(ip="192.168.1.1", port=5901, password="vncpassword")
print vnc
```
It gives me `None`
Why is this happening?

**Comment by rena-anju** [comment]
Since you are having quotes inside the string, you need to encapsulate the string with triple quotes, """ or ''' should work. Example below:

`vnc = """vncStart(ip="192.168.1.1", port=5901, password="vncpassword")"""`

**Comment by RaiMan** [comment]
try with 1.1.4
