### ISSUE TITLE
[request] [1.1.4] upgrade to Tess4J 4.3 which uses Tesseract 4

### ISSUE THREAD

**Issue by gilb771** [RaiMan/SikuliX1#60]
hi, 
There is a chance to update the OCR functionality to tesseract version 4, I know the based on Tess4J but tesseract version 4 make better work then Tess4J.

**Comment by RaiMan** [comment]
There is a Tess4J 4.3 on MavenCentral.
I have to test the usability with SikuliX, which will take a while. 

If you have the time, you could help me and test Tess4J 4.3 yourself.
The native libs for Windows are bundled. For Mac and Linux they have to be built/provided.

**Comment by gilb771** [comment]
I  think tesseract version 4.0.0-rc2-1.4.3 from a repository org.bytedeco.javacpp-presets is mach better than Tess4J 4.3. I check both of them and tesseract javacpp is much better.
There is a chance to use tesseract javacpp ?

**Comment by RaiMan** [comment]
> a chance to use tesseract javacpp

principally yes. I will check, how I can integrate it.

> tesseract javacpp is much better

can you tell me more, why you think it is better?

**Comment by RaiMan** [comment]
Woooow, very helpful :-) Thanks.

I will come back with my findings.

**Comment by balmma** [comment]
Can be closed I would say :-)

**Comment by RaiMan** [comment]
sure :-))
