### ISSUE TITLE
VS Code extension for SikuliX scripts

### ISSUE THREAD

**Issue by Alexander-Wilms** [RaiMan/SikuliX1#602]
Maybe a VS Code extension could be written that just shows the referenced images inline, like the SikuliX IDE.

This is just a suggestion, I don't know how much work it would be to implement this.

Editing SikuliX scripts in VS Code has the advantage that one can easily run a linter, auto-format the code, has Git integration etc.

Edit:

It seems like inline images are not possible: https://stackoverflow.com/a/44965967/2278742

However, the _Image Preview_ extension does add image previews on hover.

https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview

**Comment by RaiMan** [comment]
Surely the wrong place to ask for such a feature.
An extension for VS Code has to be created in the TypeScript eco-system.

My development is completely based on Java and I do not have plans to change that.

So you either have to try the mentioned extension or work in parallel with VS Code and the SX IDE.

What I have on the list: The IDE should watch for external script file changes and suggest a reload in case, which would allow to use other tools in parallel to The SX IDE.
