### ISSUE TITLE
Is there a way to generate long clicks (10 seconds +) on actionable elements?

### ISSUE THREAD

**Issue by ghevge** [RaiMan/SikuliX1#603]
I'm trying to execut a long click: 10 seconds ( from the moment I press the left click  until I release the left click) or more on a buttont.

Looking at the sikulix1 available methods, I'm not finding anything that could help me in triggering such events.

I found the` screen.delayClick()` method, which seem to do something like this, but I can only set a delay period of up to 1 second.

Any idea how I can chive this behavior?

Thanks

**Comment by MiguelDomingues** [comment]
Might worth trying using something like [mouseDown ](https://sikulix-2014.readthedocs.io/en/latest/region.html#Region.mouseDown)+ wait(10) + [mouseUp](https://sikulix-2014.readthedocs.io/en/latest/region.html#Region.mouseUp)

Haven't tested it but should be what you are looking for

**Comment by RaiMan** [comment]
@MiguelDomingues 
Correct suggestion.
