### ISSUE TITLE
[1.1.4]  findText(): NPE in FindInput2.java::isValid() --- fixed build #157

### ISSUE THREAD

**Issue by agum** [RaiMan/SikuliX1#61]
Hi, I'm using the project since several days. It's quite promising for my needs and has many great features. Thanks for your efforts.
I've encountered NullPointerException today when new snapshot version was pulled by maven into my project.
 
Adding this validation causes NullPointerException in case of findText() invocation since 'target' field is not set - only 'targetText' is set then.

https://github.com/RaiMan/SikuliX1/blob/dda8fe0ad89fb0ffba699574112bd616e985ec6b/API/src/main/java/org/sikuli/script/FindInput2.java#L63

Can You please investigate and fix that?

**Comment by RaiMan** [comment]
Should work now.
