### ISSUE TITLE
Question: Easy way to ignore the background for image search?

### ISSUE THREAD

**Issue by GarThor** [RaiMan/SikuliX1#612]
This may be a dumb question, but is there an easy way to automatically ignore the background for image searches?

**Comment by GeorgeChSakkas** [comment]
I use black background, no wallpapers.

**Comment by GarThor** [comment]
> I use black background, no wallpapers.

I'm automating an app I have no control over.  The background of the thing I'm trying to click on changes color randomly, which is why I ask.

**Comment by GeorgeChSakkas** [comment]
Oh, ok. I think you can't then. 
Maybe you can use OCR or you can set a specific area on screen to retrieve your data.

**Comment by RaiMan** [comment]
You might delete (make transparent) the background in your shots by using an external image tool.

Then with SikuliX you can rely on the transparency feature, which lets the search ignore the transparent parts if the given image is .png with transparency.

The isolation of the importtant parts of the image does not need to be very exact: about 10% - 20% of "wrong" background should still lead to a 80% - 90% score, which normally is ok.

**Comment by GarThor** [comment]
> You might delete (make transparent) the background in your shots by using an external image tool.
> 
> Then with SikuliX you can rely on the transparency feature, which lets the search ignore the transparent parts if the given image is .png with transparency.
> 
> The isolation of the importtant parts of the image does not need to be very exact: about 10% - 20% of "wrong" background should still lead to a 80% - 90% score, which normally is ok.

Does that work?  I think I saw an issue regarding transparancies when I was looking for solutions to my problem...

**Comment by RaiMan** [comment]
Again tested on Win11 with 2.0.5 and Java 11:
a .png with transparent background is found as expected.

But: there seems to be a problem with the IDE Preview (Java crash) - I will check again with 2.0.6-prefinal.

**Comment by RaiMan** [comment]
Same on 2.0.6: search works - Preview does not.

I make a bug.
