### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by songqingshududu** [RaiMan/SikuliX1#616]
my path: jdk1.8 and windows10
my dependency :
        <dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.0.5</version>
        </dependency>
my code:
`    @SneakyThrows
    @Test
    void test1() {
        Runtime.getRuntime().exec("calc.exe");
        Thread.sleep(2000);

        Screen screen = new Screen(true);
        screen.click("C:\\Users\\cl\\Desktop\\images\\6.png");
        screen.click("C:\\Users\\cl\\Desktop\\images\\x.png");
        screen.click("C:\\Users\\cl\\Desktop\\images\\7.png");
        screen.click("C:\\Users\\cl\\Desktop\\images\\=.png");

        if (screen.exists("C:\\Users\\cl\\Desktop\\images\\42.png").isValid()) {
            System.out.println("ok!!!!!!!!!!!!!!!!!!");
        }else {
            System.out.println("no!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        }

    }`

The following error occurred during the run: java.lang.NullPointerException

**Comment by songqingshududu** [comment]
![image](https://github.com/RaiMan/SikuliX1/assets/142251921/4ba84f85-0fde-481a-84d6-281ac874f01d)

**Comment by songqingshududu** [comment]
![image](https://github.com/RaiMan/SikuliX1/assets/142251921/73d9a027-182c-4e15-87df-24e033ec5522)

**Comment by songqingshududu** [comment]
![image](https://github.com/RaiMan/SikuliX1/assets/142251921/76360956-b1e5-45bd-bfb3-396188b96661)

**Comment by RaiMan** [comment]
`Screen screen = new Screen(true);`

should be:

`Screen screen = new Screen();`
