### ISSUE TITLE
[error] findWindow: Index 7 out of bounds for length 1

### ISSUE THREAD

**Issue by guohailin0323** [RaiMan/SikuliX1#634]
hello，
  Running code error
  App.open("/usr/bin/firefox")
  
  【error message】
  [error] findWindow: Index 7 out of bounds for length 1

  Description:	Ubuntu 24.04.1 LTS
  Release:	24.04
  Codename:	noble
 
  sikulixide-2.0.5.jar
  
  【my code】
  # coding=utf-8
  import sys
  sys.path.append("/home/user/sikuli_test/sikulixide-2.0.5.jar")
  from org.sikuli.script import Screen, App, Key, Pattern

  def main():
      App.open("/usr/bin/firefox")

  if __name__ == "__main__":
      main()
      
  【run mode】
  jython test.py

**Comment by RaiMan** [comment]
Not the intended use for running Python scripts - was never tested this way.

run a script
`App.open("/usr/bin/firefox")`

from a commandline using `java -jar ....`

or from inside the IDE.
