### ISSUE TITLE
[1.1.4] TextRecognizer start() should dereference textRecognizer variable if initialisation failed --- fixed 2019-01-03 build#175

### ISSUE THREAD

**Issue by THedoux** [RaiMan/SikuliX1#66]
Steps to reproduce
---------------------- 
1- With an incorrect setup (no Tesseract lib can be reach in example), run an OCR action once
2- Repeat step 1

Expected result
----------------------
An error is provided at step 1 and at step 2

Current results
----------------------
An error occurs only for the first step. 

Comments
----------------------
The call to *start* in TextRecognizer class is doing this : *textRecognizer = new TextRecognizer();*
At the next call, even if an exception was triggered, the text recognizer will be considered as initialised because it is not null.
A solution will be to do the whole initialization, and only if everything works properly to set the static textRecognizer variable.

**Comment by RaiMan** [comment]
Will check and fix asap.

**Comment by RaiMan** [comment]
see commit
https://github.com/RaiMan/SikuliX1/commit/6845a240dd853940f6d7ff6a918aded18bb419e5
