### ISSUE TITLE
[1.1.4] Sikulix doesn´t finish

### ISSUE THREAD

**Issue by PfrLisBerndt** [RaiMan/SikuliX1#67]
Hello and happy new year!

In the latest version it seems, that sikulix doesn´t care about terminating; even if let my script terminate explicitly, the api obviously continues running somehow. 

Best regards!

**Comment by RaiMan** [comment]
should be fixed with the builds from today.

**Comment by PfrLisBerndt** [comment]
It got worse ;) 

> Exception in thread "Thread-3" java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Screen
        at org.sikuli.script.RunTime.cleanUp(RunTime.java:766)
        at org.sikuli.script.RunTime$1.run(RunTime.java:405)
