### ISSUE TITLE
unicode logging issue?

### ISSUE THREAD

**Issue by SeanKim777** [RaiMan/SikuliX1#70]
https://github.com/RaiMan/SikuliX1/blob/a4f7bf403e19509ffc475a9186599c6563c9e54f/API/src/main/java/org/sikuli/basics/Debug.java#L454

I am having an issue with my new pc and found possible reason from [here](http://www.herongyang.com/Java-Tools/native2ascii-Set-UTF-8-Encoding-in-PrintStream.html) 
It may required to use 'UTF-8' argument for new PrintStream

**Comment by RaiMan** [comment]
just tested: works.

Take care: run your project with java command line option 
`-Dfile.encoding=UTF-8`

If you run as script from SikuliX IDE, you have to encode your unicode strings:
`Debug.user(unicd("T\uD804\uDD8C˄F̃脔Ŷﲝ捸\uD8E9\uDD00偆\uABA2ⷉ\uDAAE\uDDA9g쑔v"))`
