### ISSUE TITLE
[1.1.4] TextRecognizer.start() does not set default language given with Settings.OcrLanguage - fixed 2019-01-10 build#181

### ISSUE THREAD

**Issue by ruby186** [RaiMan/SikuliX1#71]
I may possible found some issues to TextRecognizer.start(). it setDatapath works, but language always default to eng.  

TextRecognizer has api to setLanguage.  

```java
TextRecognizer.start().setLanguage("chi_sim");  // need manual set this line.
Settings.OcrLanguage = "chi_sim";
Settings.OcrTextSearch = true;
Settings.OcrTextRead = true;

Screen screen = new Screen();
screen.waitText("维基百科").highlight(2);  // you can save wikipedia to have a try
```  

https://zh.wikipedia.org/zh/Wiki => Wiki - 维基百科，自由的百科全书

I think, when TextRecognizer.start(), it should read default language in global Settings.
please advise.

**Comment by RaiMan** [comment]
Thanks for finding. With the latest build #181 this should work as expected:
```
Settings.OcrLanguage = "chi_sim";
TextRecognizer.start();
```
assumed you have the traineddata files in place.

obsolete:
```
Settings.OcrTextRead = true; // is generally no longer needed, true anyways now
Settings.OcrTextSearch = true; // is generally no longer needed, true anyways now
```

The Settings generally are intended, to be set/changed before using respective features.
