### ISSUE TITLE
[1.1.4] Selecting a region takes very long the first time and returns null in javafx

### ISSUE THREAD

**Issue by Awlexus** [RaiMan/SikuliX1#72]
I'm currently writng a program with JavaFX and Sikulix to automate a certain process on mac/windows and the first time I try to select a region with `Screen.getPrimaryScreen().selectRegion("Test");` I have to wait around 30 seconds before the program responds again and I can select a region. But this first time the region is always `null`.

I'm working on a dual screen setup and even though I do `getPrimaryScreen()`, I get the overlay to select a region appears on both screens, but the program resumes once the first region is selected and therefore ignored the second region selected. 

## Code
This is the method I catpture the screen with. Prints the complete Path to the File on the second try and screen selection appears rather immediate
```java
    @FXML
    private void getRegion() {
        Region r = Main.primaryScreen.selectRegion("Test"); // Same as Screen.getPrimaryScreen().selectRegion("Test"); | Returns null the first time
        ScreenImage capture = null;
        try {
            capture = Main.primaryScreen.capture(r);
        } catch (NullPointerException e) {
            e.printStackTrace(); // To separate JavaFX errors and From the NullPointerException
            throw e;
        }
        System.out.println("Screenshot captured: " + capture.getFile());
    }
```

Selecting a region with the SikulixIDE 1.1.4 works perfectly fine. Is there some kind of setup i have to do before i can make screen captures?

My project currenly uses Java 8 (1.8.0_191) for compatibily with Javafx and also Kotlin in some other classes

Sidenote: I tried to wrap around but odd behaviour by wraping it with a do while loop like this
```java
Region region = null;
do {
  region = screen.selectRegion();
  System.out.plrintln(region == null);
} while (region == null);
```
But that turned into a "while true"-loop that never let me select a region and printed "true" every couple of seconds.

**Comment by RaiMan** [comment]
I have to check.

**Comment by RaiMan** [comment]
I checked with a normal Java Maven project: works as it should (no delays, no NPE)

So I guess, it is a problem with your JavaFX environment and probably has something to do with the fact, that the selectRegion() might be issued in a JavaFX feature running on the event loop.

That the delay is 30 seconds means, that the internal "wait for select action" is not triggered and hence stops waiting after 30 seconds of inactivity.

Inactivity in your case means, that your mouse actions are not given through to the action handler in the selectRegion() feature.

The usual way, to avoid such problems, is to detach the offending SikuliX features into a thread.
