### ISSUE TITLE
Region.text() doesnt properly detect numbers, can we specify font for better detection?

### ISSUE THREAD

**Issue by Angernoxo** [RaiMan/SikuliX1#73]
Hello,

I'm writing a trading bot , it works well but sometimes I have problems with region.text() ,sometimes it gives wrong data, and sometimes it fails to detect at all ( sometimes it returns an " ? " for number 7 ).

Since I'm only using numbers , would it be possible to specity the font for each number? This way I think detection would be greater and it will have no problems.

Added an example in this photo: https://i.imgur.com/MDQkyaC.png
![mdqkyac](https://user-images.githubusercontent.com/46788719/51331326-caf61280-1a79-11e9-9119-89581147d9cf.png)

On the FAQs it explains how to switch to a different language pack, but I don't know how to change font ( if possible at all ) and how to detect the font this game is running.

Any fix to this will be deeply appreciated, and properly rewarded.

Sorry I can't give more info, I'm not knowledgeable in programing enough to give more info, I just know that detection fails.

Thanks

**Comment by balmma** [comment]
Tesseract 4 in the current snapshot together with the enhancements in PR #200 (already merged) an PR #204 (not merged yet) seem to be able to recognize your image properly.

**Comment by Angernoxo** [comment]
Thank you @balmma  , I've had this issue almost a year ago but I definitely appreciate your reply, I gave up on that project but I'm up to trying it again now,, will check in the following weeks, hoping that I can detect numbers again

**Comment by balmma** [comment]
What also might help, since you mainly want to find digits, is to limit Tesseract to those characters:
```
tr = TextOCR.start()
tr.setPSM(12) # Sparse text with OSD.
tr.setVariable("tessedit_char_whitelist", "1234567890")
```
Notice that you even get rid of the "," this way. I you want to have it, just add the comma to the whitelist.

Output with your example picture:
```
1300
14300
550
14322
600
14332
825
14370
225
14371
```

**Comment by balmma** [comment]
But anyway, please wait until PR #204 got merged into master.

**Comment by balmma** [comment]
Merged.

Another (simpler) option to only recognize numbers is to use the config preset:
```
tr = TextOCR.start()
tr.setPSM(12)
tr.setConfigs(["digits"])
```
