### ISSUE TITLE
SikuliX1 in C#

### ISSUE THREAD

**Issue by AutomationSifu** [RaiMan/SikuliX1#75]
Good Evening,

I'm not sure if you've answered this already.  Is it possible to use this library within Visual Studio for c#.  I've tried some of the other libraries such as Sikuli Integrator, Sikuli4Net, and SikuliSharp. but I've encountered various issues or inconsistencies.

Sikuli Integrator was working but only when visual studio is started as an admin as there is an issue with the SikuliOutputlog file and valid permissions.

Thanks!

**Comment by RaiMan** [comment]
Sorry no.

Currently a direct usage of SikuliX from C# is not possible.
You always need some kind of wrapper, that translates the Java API to C#.

**Comment by AutomationSifu** [comment]
Thanks for your feedback!  Do you think there will be a way for Sikuli to work with c# in the future?

**Comment by RaiMan** [comment]
I have to admit, that C# is not my priority due to lack of knowledge and experience.
So I will surely not create a wrapper for C#.
Later this year I plan to implement SikuliX as a generic REST server, which would allow to use it from every context, that can issue GET requests.
