### ISSUE TITLE
NoSuchMethodError when using sikulixapi 1.1.4-SNAPSHOT

### ISSUE THREAD

**Issue by sgeorg5** [RaiMan/SikuliX1#76]
I have updated my project to the latest sikulixapi, version 1.1.4. I did this by adding the downloaded .jar file to my Java classpath as a library jar. However, upon running my test now, I get the following error:

java.lang.NoSuchMethodError: org.sikuli.script.Pattern.similar(F)Lorg/sikuli/script/Pattern;

It appears that Pattern is no loner found. Is this expected? If so, what is the replacement? 
Also, is there anything particular I should add to my pom.xml file for upgrading to 1.1.4 from 1.1.0?

**Comment by RaiMan** [comment]
see the Read.me on https://github.com/RaiMan/SikuliX1

1.1.4 currently only available as snapshot from OSSRH

**Comment by sgeorg5** [comment]
Has similar been removed in 1.1.4?
When trying something like this: 

target = new Pattern(file).similar(similarity) .targetOffset(Xoffset, Yoffset);

I get this error:

java.lang.NoSuchMethodError: org.sikuli.script.Pattern.similar(F)Lorg/sikuli/script/Pattern;

Is there a replacement for similar?

**Comment by sgeorg5** [comment]
I found my issue.  I still have 1.1.0 installing.
