### ISSUE TITLE
Main 'site' link on SikuliX1 Github page goes to incomplete page

### ISSUE THREAD

**Issue by paul-hammant** [RaiMan/SikuliX1#77]
![2019-02-15_1116](https://user-images.githubusercontent.com/82182/52853334-35e74780-3113-11e9-9589-055bc76e0546.png)

Might be better to delete that link, and the README that's inline in the main project page is fairly solid.

**Comment by RaiMan** [comment]
I agree, that the page might look a bit "naked", but every link leads to something else, that makes sense. 
So I will leave it as is.
