### ISSUE TITLE
screen.isNotPresent(locator, duration)

### ISSUE THREAD

**Issue by paul-hammant** [RaiMan/SikuliX1#78]
In a wrapper of Selenium called FluentSelenium, i made a `within(..)` and `without(..)` for [when the DOM changes slowly](https://github.com/SeleniumHQ/fluent-selenium#situations-where-the-dom-is-slowly-changing). I think there's functional equivalence for within() (a wrapper for WebDriver's `waitFor(..)` logic, but there's no wait ensuring that something has disappeared from the UI, or will disappear within a timeframe.  Well, not without doing some logic that involves try/catch.  Would it be possible to add something to the API:

* screen.isNotPresent("images/splash.png", 2);
* screen.shouldBeGone("images/splash.png", 2);
* screen.waitForDisappearanceOf("images/splash.png", 2);

Thoughts?

**Comment by RaiMan** [comment]
There is the Region feature waitVanish() and for the observing we have onVanish().
