### ISSUE TITLE
How to handle the resolution of the image if changes

### ISSUE THREAD

**Issue by prasanna532** [RaiMan/SikuliX1#80]
As i know sikuli will fail on the different resolution... But i am not getting how to use this to avoid those problems....

I how to use the sikuil how to integrate this to avoid the failure on the different resolutions...

**Comment by RaiMan** [comment]
You might try with:
[Pattern.resize()](https://sikulix-2014.readthedocs.io/en/latest/pattern.html#Pattern.resize)

This should work in situations, where you have the scaling factor.

In all other situations you need a dedicated image set for every resolution environment.

**Comment by prasanna532** [comment]
> In all other situations you need a dedicated image set for every resolution environment.


This means i need to keep the different images for different resolutions of monitors ?

**Comment by RaiMan** [comment]
See feature ImagePath
