### ISSUE TITLE
Dokumentation for matching algorithm

### ISSUE THREAD

**Issue by stoefln** [RaiMan/SikuliX1#81]
Thanks for this great tool!

Can I find some documentation about how the matching algorithm is working? I am talking specifically about this method:
https://github.com/RaiMan/SikuliX1/blob/5ee3e5bae084c94f19104c4b04f8b8a2d109ebeb/API/src/main/java/org/sikuli/script/Finder2.java#L343

More specifically:
1. why in some cases you use `TM_CCORR_NORMED` but in some others you use `TM_SQDIFF_NORMED`? 
2. Why is a `bitwise_not` applied in some other case? 
3. Why is `Core.subtract` applied in some case?

**Comment by RaiMan** [comment]
I guess you are talking about to this part:

```
      if (!findInput.isPlainColor()) {
        // normal images (not plain color)
        if (findInput.hasMask()) {
          // with transparency
          Mat mask = findInput.getMask();
          Imgproc.matchTemplate(mWhere, what, mResult, Imgproc.TM_CCORR_NORMED, mask);
        } else {
          // no transparency (opaque)
          Imgproc.matchTemplate(mWhere, what, mResult, Imgproc.TM_CCOEFF_NORMED);
        }
      } else {
        // plain color images
        Mat wherePlain = mWhere;
        Mat whatPlain = what;
        if (findInput.isBlack()) {
          // convert to white if black
          Core.bitwise_not(mWhere, wherePlain);
          Core.bitwise_not(what, whatPlain);
        }
        if (findInput.hasMask()) {
          // with transparency
          Imgproc.matchTemplate(wherePlain, what, mResult, Imgproc.TM_SQDIFF_NORMED, findInput.getMask());
        } else {
          // no transparency (opaque)
          Imgproc.matchTemplate(wherePlain, whatPlain, mResult, Imgproc.TM_SQDIFF_NORMED);
        }
         // this is how you get the results with TM_SQDIFF_NORMED
        Core.subtract(Mat.ones(mResult.size(), CvType.CV_32F), mResult, mResult);
      }
```
... I have added some comments here.
So no magic: just the optimal options/workflows for the image/pattern type

**Comment by stoefln** [comment]
Thanks very much, things are becoming more clear already!
I am still not sure why you are using `TM_CCOEFF_NORMED` on plain images and  `TM_SQDIFF_NORMED` on others?
And why are you are doing a `bitwise_not` on black images?

**Comment by RaiMan** [comment]
--- just the optimal options/workflows for the image/pattern type
the reason behind: the settings you see, are the result of some trials over the years and of course reading/understanding the relevant parts in OpenCV and in examples in the net, to get the best possible search results.
