### ISSUE TITLE
Sikuli False Positive issue

### ISSUE THREAD

**Issue by gigi199596** [RaiMan/SikuliX1#83]
Hello,

I encountered a false positive in Sikuli by doing a click on this picture:
![sikuliximage-1551781487184](https://user-images.githubusercontent.com/11850698/53807591-3fb0dd80-3f50-11e9-830b-4f5247ff00a2.png)
Instead this one was recognized:
![sikuliximage-1551453537838](https://user-images.githubusercontent.com/11850698/53807565-2dcf3a80-3f50-11e9-805c-f3e8294b0c3f.png)
How is it possible to get a so much difference in image recognition? 🤓 

thanks for your help
Gilles

**Comment by RaiMan** [comment]
your code snippet please

**Comment by RaiMan** [comment]
[Already know how SikuliX works?](https://sikulix-2014.readthedocs.io/en/latest/basicinfo.html#sikulix-how-does-it-find-images-on-the-screen)

**Comment by gigi199596** [comment]
I'm using robot framework with the help of SikuliLibrary. 
https://github.com/rainmanwy/robotframework-SikuliLibrary/

Here is the code snippet:
`Click    select_host/select_host_tab.png`

it does a call to https://github.com/rainmanwy/robotframework-SikuliLibrary/blob/3728c6d07fb5d2b06d3f08cddeda1b650fd2db6e/src/java/com/github/rainmanwy/robotframework/sikulilib/keywords/ScreenKeywords.java#L116


> [Already know how SikuliX works?](https://sikulix-2014.readthedocs.io/en/latest/basicinfo.html#sikulix-how-does-it-find-images-on-the-screen)
ok I red it but that doesn't help me much.

In my case, sometimes when the screenshot is not present on the screen i get false positive. I would like to know the reason why and how to reduce theses errors...

Maybe my issue is a bit vague 👎 sorry for that!

**Comment by RaiMan** [comment]
Without saying anything, the similarity score is taken as 0.7, which in many cases could lead to false positives, if the wanted image is not visible.

So instead of just using the image, you have to define it as a Pattern with a higher sim score.

Check the Sikuli-Library docs to find out how to do that.

**Comment by gigi199596** [comment]
> Without saying anything, the similarity score is taken as 0.7, which in many cases could lead to false positives, if the wanted image is not visible.

Thanks it answers my question!
> So instead of just using the image, you have to define it as a Pattern with a higher sim score.

It is what I tough 😄 

Keep on with the good work 🎆

**Comment by RaiMan** [comment]
Thanks for feedback
