### ISSUE TITLE
[1.1.4] UnsatisfiedLinkError: user32 --- fixed 2019-03-08 build #228

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [RaiMan/SikuliX1#86]
When trying Sikuliapi 1.1.4, I get this strange error:

```
java.lang.UnsatisfiedLinkError: Unable to load library 'user32': Native library (linux-x86-64/libuser32.so) not found in resource path
```
user32 looks like 32 bits and Windows, but I'm working on Linux CentOS 64 bits, and 
Java 8

tesseract-devel has been installed and compiled OpenCV 3.4.5

**Comment by DavidPerezIngeniero** [comment]
Clearly, it tries to load User32.dll in Linux:

```
$ grep -r user32 SikuliX1/
SikuliX1/API/src/main/java/com/tulskiy/keymaster/windows/User32.java:        Native.register(NativeLibrary.getInstance("user32", W32APIOptions.DEFAULT_OPTIONS));
SikuliX1/API/src/main/java/org/sikuli/natives/SXUser32.java:  SXUser32 INSTANCE = (SXUser32) Native.loadLibrary("user32", SXUser32.class, W32APIOptions.DEFAULT_OPTIONS);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:  static final SXUser32 sxuser32 = SXUser32.INSTANCE;
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:  static final User32 user32 = User32.INSTANCE;  
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    boolean result = user32.EnumWindows(
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:              if (user32.IsWindowVisible(hwnd)){
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:                user32.GetWindowThreadProcessId(hwnd, windowPid);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    int length = user32.GetWindowText(hWnd, text, 1024);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    sxuser32.EnumWindows(new WinUser.WNDENUMPROC() {
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    int state = sxuser32.GetKeyState(WinNumLock);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    int state = sxuser32.GetKeyState(WinScrollLock);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    int state = sxuser32.GetKeyState(WinCapsLock);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    user32.GetWindowPlacement(hwnd, lpwndpl);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:      user32.ShowWindow(hwnd, WinUser.SW_RESTORE);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    boolean success = user32.SetForegroundWindow(hwnd);             
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:      user32.SetFocus(hwnd);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:      user32.GetWindowThreadProcessId(hwnd, windowPid);
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    boolean success = user32.GetWindowRect(hwnd, rect);    
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    HWND hwnd = user32.GetForegroundWindow();
SikuliX1/API/src/main/java/org/sikuli/natives/WinUtil.java:    boolean success = user32.GetWindowRect(hwnd, rect);
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:  private static final SXUser32 sxuser32 = SXUser32.INSTANCE;
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:    int spaceScanCode = sxuser32.MapVirtualKeyExW(KeyEvent.VK_SPACE, MAPVK_VK_TO_VSC, keyboarLayoutId);
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:      int scanCode = sxuser32.MapVirtualKeyExW(vk.getCode(), MAPVK_VK_TO_VSC, keyboarLayoutId);
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:      int ret = sxuser32.ToUnicodeEx(vk.getCode(), scanCode, keyStates, buff, 1, 0, keyboarLayoutId);
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:        ret = sxuser32.ToUnicodeEx(KeyEvent.VK_SPACE, spaceScanCode, keyStates, buff, 1, 0, keyboarLayoutId);
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:      HWND hwnd = sxuser32.GetForegroundWindow();
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:          int threadID = sxuser32.GetWindowThreadProcessId(hwnd, null);               
SikuliX1/API/src/main/java/org/sikuli/script/KeyboardLayout.java:          keyboarLayoutId = sxuser32.GetKeyboardLayout(threadID);       
```

**Comment by RaiMan** [comment]
what exactly are you doing?

**Comment by genkicode** [comment]
same issue here, it tires to run an extremely outdated libuser32.so, havent seen that since using cedega in 2011.

i downloaded the sikulix.jar ide again, to run it on a new system.
- everything except the libuser32.so loads
used the jar from the old system
- sikulix ide loads
i thought there was a problem with the system (both lubuntu 18.04, installed from same iso) or that the jar file is corrupt, until i ran the old sikulix.jar
The problem was most likely triggered by the latest changes during the last 3 days.
But im glad to confirm that (the old 1.1.4) runs very well with opencv 4

**Comment by RaiMan** [comment]
ok, accepted as bug.
I have to check.

**Comment by DavidPerezIngeniero** [comment]
> what exactly are you doing?

I'm running a simple Python script, by using sikulixapi.jar.

**Comment by DavidPerezIngeniero** [comment]
> same issue here, it tries to run an extremely outdated libuser32.so, havent seen that since using cedega in 2011.
> 
> sikulix was running on an older system, i downloaded the sikulix.jar ide again, to run it on a new system.
> 
> * everything except the libuser32.so loads, GUI is stuck in loading screen
> 
> used the old jar from the old system
> 
> * sikulix ide loads
> 
> i thought there was a problem with the system (both lubuntu 18.04, installed from same iso) or that the jar file is corrupt, until i ran the old sikulix.jar
> 
> ran the "new" 1.1.4 on the old system
> 
> * same libuser32.so error
> 
> The problem was most likely triggered by the latest changes during the last 3 days.
> But im glad to confirm that (the old 1.1.4) runs very well with opencv 4

Thanks.  I'll try to use opencv 4 as well.

**Comment by DavidPerezIngeniero** [comment]
Is Sikuli 1.1.4 better than Sikuli 1.1.1, even though it's still in beta stage?

**Comment by RaiMan** [comment]
@DavidPerezIngeniero 
read: https://sikulix-2014.readthedocs.io/en/latest/news.html#new-in-version-1-1-4

**Comment by andreashoyerh2m** [comment]
I think I have the same problem on MacosX:
java.lang.UnsatisfiedLinkError: Unable to load library 'user32': Native library (darwin/libuser32.dylib) not found in resource path ...
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at org.sikuli.natives.SXUser32.<clinit>(SXUser32.java:9)
	at org.sikuli.script.KeyboardLayout.<clinit>(KeyboardLayout.java:20)
	at org.sikuli.script.Key.toJavaKeyCode(Key.java:514)
	at org.sikuli.script.Key.<clinit>(Key.java:399)
	at org.sikuli.script.Region.keyin(Region.java:4699)
	at org.sikuli.script.Region.type(Region.java:4595)

**Comment by andreashoyerh2m** [comment]
Your fix was faster than my report...
I can confirm that the problem is gone on Macosx.
Thanks a lot.

**Comment by DavidPerezIngeniero** [comment]
Thanks Raimund for your quick fix.  Is the fix already published to Maven?

**Comment by RaiMan** [comment]
@DavidPerezIngeniero 
When I push a fix to the GitHub repo, a build is triggered on TravisCI (the referenced build number).
As a result, the download page is updated with the appropriate links and the sikulixapi-snapshot-jar  is uploaded to OSSRH.

Hence asking for "already published to Maven" is the wrong answer, since snapshots are not published to Maven.

... but yes, if a new build is available, than also the appropriate snapshot jar is available for Maven/Gradle based projects.
