### ISSUE TITLE
[1.1.4] Unable to run Sikulix

### ISSUE THREAD

**Issue by raindropsfromsky** [RaiMan/SikuliX1#97]
I have Windows 10, 32 bit version.

I am unable to run Sikulix 1.1.4. 

I downloaded the latest version from here:
https://raiman.github.io/SikuliX1/downloads.html

But when I run it, it gives the following error:

![image](https://user-images.githubusercontent.com/9047168/54352925-c2384c00-4678-11e9-9950-5cb8fa9c042e.png)

I downloaded JRuby from here: https://www.jruby.org/
(https://s3.amazonaws.com/jruby.org/downloads/9.2.6.0/jruby_windows_9_2_6_0.exe)
During the installation, the installer asks whether to set up register path (recommended).
I let it happen.
And then restarted the PC. 

But still I get the same error.

The error mentions "consult the docs" but I don't find any pdf etc anywhere on the site.
The wiki link at GitHub is empty.

I do not have any IDEs (such as Netbeans) on this PC.

What could be the issue?

**Comment by RaiMan** [comment]
SikuliX 1.1.4+ does not run on 32-Bit systems any more.

Try with 1.1.3

**Comment by raindropsfromsky** [comment]
oh. Right, thanks!
