### ISSUE TITLE
Create custom Screen java object from screenshot

### ISSUE THREAD

**Issue by pascencio** [RaiMan/SikuliX1#98]
Hi @RaiMan,

I want to use Sikulix like a service in my project. My idea is send some image from screen and the pattern in base64 to get back the position match. The service may use the screen image to create the Screen java object and use the Sikulix API to get the pattern position.
Looking in documentation, I can't find some clue to customize the Screen object. Can you give me a hand with this?

Thanks in the advance!

**Comment by RaiMan** [comment]
Not sure, what you mean by customizing.

The Screen is only a subclass of Region.

So lets say, your project is the client and the SikuliX-as-a-service is the server.

**case one (capture on server):**
client sends a Region and an image/pattern, then the service simply makes a 
match = region.find(image)
and sends the match back.

**case two (capture on client):**
the client makes a screenshot and sends this as base64 to the client together with the Pattern/Image.
On the server you then have to turn the base64 to a Java BufferedImage and use:
finder = new Finder(BufferedImage)
finder.find(image)
match = finder.next()
and sends the match back.

**Comment by pascencio** [comment]
@RaiMan 

I'm think something like the case two. The Finder class it's that I want on my project.

Thanks!
