### ISSUE TITLE
[1.1.4] extensions menu not working anymore

### ISSUE THREAD

**Issue by kevin-innorules** [RaiMan/SikuliX1#99]
Hi!

I rebuilt with master branch and then I clicked the extensions menu error is occurred.
The error message is "[error] IDE: Problem when trying to invoke menu action extensions"
I looked for the reason what it does it's reason is classpath is null returned from ExtensionManagerFrame.getExtensionNames().

Is it a known issue or not ?
And how to fix it ?

Answer please.

**Comment by RaiMan** [comment]
seems to be broken. Does not do anything in the moment anyways.
Just do not use it until fixed.
